/*
SigNoz

Testing CloudintegrationAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package signozclient

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/harsh098/signoz-alert-operator/internal/signozclient"
)

func Test_signozclient_CloudintegrationAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test CloudintegrationAPIService AgentCheckIn", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var cloudProvider string

		resp, httpRes, err := apiClient.CloudintegrationAPI.AgentCheckIn(context.Background(), cloudProvider).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CloudintegrationAPIService AgentCheckInDeprecated", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var cloudProvider string

		resp, httpRes, err := apiClient.CloudintegrationAPI.AgentCheckInDeprecated(context.Background(), cloudProvider).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CloudintegrationAPIService CreateAccount", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var cloudProvider string

		resp, httpRes, err := apiClient.CloudintegrationAPI.CreateAccount(context.Background(), cloudProvider).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CloudintegrationAPIService DisconnectAccount", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var cloudProvider string
		var id string

		httpRes, err := apiClient.CloudintegrationAPI.DisconnectAccount(context.Background(), cloudProvider, id).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CloudintegrationAPIService GetAccount", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var cloudProvider string
		var id string

		resp, httpRes, err := apiClient.CloudintegrationAPI.GetAccount(context.Background(), cloudProvider, id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CloudintegrationAPIService GetConnectionCredentials", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var cloudProvider string

		resp, httpRes, err := apiClient.CloudintegrationAPI.GetConnectionCredentials(context.Background(), cloudProvider).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CloudintegrationAPIService GetService", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var cloudProvider string
		var serviceId string

		resp, httpRes, err := apiClient.CloudintegrationAPI.GetService(context.Background(), cloudProvider, serviceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CloudintegrationAPIService ListAccounts", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var cloudProvider string

		resp, httpRes, err := apiClient.CloudintegrationAPI.ListAccounts(context.Background(), cloudProvider).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CloudintegrationAPIService ListServicesMetadata", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var cloudProvider string

		resp, httpRes, err := apiClient.CloudintegrationAPI.ListServicesMetadata(context.Background(), cloudProvider).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CloudintegrationAPIService UpdateAccount", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var cloudProvider string
		var id string

		httpRes, err := apiClient.CloudintegrationAPI.UpdateAccount(context.Background(), cloudProvider, id).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CloudintegrationAPIService UpdateService", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var cloudProvider string
		var id string
		var serviceId string

		httpRes, err := apiClient.CloudintegrationAPI.UpdateService(context.Background(), cloudProvider, id, serviceId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
