apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: signoz-alert-operator
  name: signoz-prod-credentials
stringData:
  api-key: REPLACE_ME
type: Opaque
