apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: signoz-alert-operator
  name: signoz-alert-operator-endpoint-viewer-role
rules:
- apiGroups:
  - monitoring.hmx86.cloud
  resources:
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.hmx86.cloud
  resources:
  - endpoints/status
  verbs:
  - get
