apiVersion: monitoring.hmx86.cloud/v1alpha1
kind: Endpoint
metadata:
  labels:
    app.kubernetes.io/name: signoz-alert-operator
    app.kubernetes.io/managed-by: kustomize
  name: signoz-prod
spec:
  # https://<your-tenant>.signoz.cloud  for SigNoz Cloud,
  # or http://signoz-frontend.signoz-system.svc.cluster.local:8080 for self-hosted.
  instanceURL: https://example.signoz.cloud
  secretKeyRef:
    name: signoz-prod-credentials
    key: api-key
