/*
SigNoz

OpenTelemetry-Native Logs, Metrics and Traces in a single pane

API version: 
Contact: support@signoz.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package signozclient

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
)


// FieldsAPIService FieldsAPI service
type FieldsAPIService service

type ApiGetFieldsKeysRequest struct {
	ctx context.Context
	ApiService *FieldsAPIService
	signal *TelemetrytypesSignal
	source *TelemetrytypesSource
	limit *int32
	startUnixMilli *int64
	endUnixMilli *int64
	fieldContext *TelemetrytypesFieldContext
	fieldDataType *TelemetrytypesFieldDataType
	metricName *string
	metricNamespace *string
	searchText *string
}

func (r ApiGetFieldsKeysRequest) Signal(signal TelemetrytypesSignal) ApiGetFieldsKeysRequest {
	r.signal = &signal
	return r
}

func (r ApiGetFieldsKeysRequest) Source(source TelemetrytypesSource) ApiGetFieldsKeysRequest {
	r.source = &source
	return r
}

func (r ApiGetFieldsKeysRequest) Limit(limit int32) ApiGetFieldsKeysRequest {
	r.limit = &limit
	return r
}

func (r ApiGetFieldsKeysRequest) StartUnixMilli(startUnixMilli int64) ApiGetFieldsKeysRequest {
	r.startUnixMilli = &startUnixMilli
	return r
}

func (r ApiGetFieldsKeysRequest) EndUnixMilli(endUnixMilli int64) ApiGetFieldsKeysRequest {
	r.endUnixMilli = &endUnixMilli
	return r
}

func (r ApiGetFieldsKeysRequest) FieldContext(fieldContext TelemetrytypesFieldContext) ApiGetFieldsKeysRequest {
	r.fieldContext = &fieldContext
	return r
}

func (r ApiGetFieldsKeysRequest) FieldDataType(fieldDataType TelemetrytypesFieldDataType) ApiGetFieldsKeysRequest {
	r.fieldDataType = &fieldDataType
	return r
}

func (r ApiGetFieldsKeysRequest) MetricName(metricName string) ApiGetFieldsKeysRequest {
	r.metricName = &metricName
	return r
}

func (r ApiGetFieldsKeysRequest) MetricNamespace(metricNamespace string) ApiGetFieldsKeysRequest {
	r.metricNamespace = &metricNamespace
	return r
}

func (r ApiGetFieldsKeysRequest) SearchText(searchText string) ApiGetFieldsKeysRequest {
	r.searchText = &searchText
	return r
}

func (r ApiGetFieldsKeysRequest) Execute() (*GetFieldsKeys200Response, *http.Response, error) {
	return r.ApiService.GetFieldsKeysExecute(r)
}

/*
GetFieldsKeys Get field keys

This endpoint returns field keys

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiGetFieldsKeysRequest
*/
func (a *FieldsAPIService) GetFieldsKeys(ctx context.Context) ApiGetFieldsKeysRequest {
	return ApiGetFieldsKeysRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return GetFieldsKeys200Response
func (a *FieldsAPIService) GetFieldsKeysExecute(r ApiGetFieldsKeysRequest) (*GetFieldsKeys200Response, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *GetFieldsKeys200Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "FieldsAPIService.GetFieldsKeys")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/fields/keys"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.signal != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "signal", r.signal, "form", "")
	}
	if r.source != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "source", r.source, "form", "")
	}
	if r.limit != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "limit", r.limit, "form", "")
	}
	if r.startUnixMilli != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "startUnixMilli", r.startUnixMilli, "form", "")
	}
	if r.endUnixMilli != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "endUnixMilli", r.endUnixMilli, "form", "")
	}
	if r.fieldContext != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "fieldContext", r.fieldContext, "form", "")
	}
	if r.fieldDataType != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "fieldDataType", r.fieldDataType, "form", "")
	}
	if r.metricName != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "metricName", r.metricName, "form", "")
	}
	if r.metricNamespace != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "metricNamespace", r.metricNamespace, "form", "")
	}
	if r.searchText != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "searchText", r.searchText, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["api_key"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["SigNoz-Api-Key"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v RenderErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v RenderErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v RenderErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetFieldsValuesRequest struct {
	ctx context.Context
	ApiService *FieldsAPIService
	signal *TelemetrytypesSignal
	source *TelemetrytypesSource
	limit *int32
	startUnixMilli *int64
	endUnixMilli *int64
	fieldContext *TelemetrytypesFieldContext
	fieldDataType *TelemetrytypesFieldDataType
	metricName *string
	metricNamespace *string
	searchText *string
	name *string
	existingQuery *string
}

func (r ApiGetFieldsValuesRequest) Signal(signal TelemetrytypesSignal) ApiGetFieldsValuesRequest {
	r.signal = &signal
	return r
}

func (r ApiGetFieldsValuesRequest) Source(source TelemetrytypesSource) ApiGetFieldsValuesRequest {
	r.source = &source
	return r
}

func (r ApiGetFieldsValuesRequest) Limit(limit int32) ApiGetFieldsValuesRequest {
	r.limit = &limit
	return r
}

func (r ApiGetFieldsValuesRequest) StartUnixMilli(startUnixMilli int64) ApiGetFieldsValuesRequest {
	r.startUnixMilli = &startUnixMilli
	return r
}

func (r ApiGetFieldsValuesRequest) EndUnixMilli(endUnixMilli int64) ApiGetFieldsValuesRequest {
	r.endUnixMilli = &endUnixMilli
	return r
}

func (r ApiGetFieldsValuesRequest) FieldContext(fieldContext TelemetrytypesFieldContext) ApiGetFieldsValuesRequest {
	r.fieldContext = &fieldContext
	return r
}

func (r ApiGetFieldsValuesRequest) FieldDataType(fieldDataType TelemetrytypesFieldDataType) ApiGetFieldsValuesRequest {
	r.fieldDataType = &fieldDataType
	return r
}

func (r ApiGetFieldsValuesRequest) MetricName(metricName string) ApiGetFieldsValuesRequest {
	r.metricName = &metricName
	return r
}

func (r ApiGetFieldsValuesRequest) MetricNamespace(metricNamespace string) ApiGetFieldsValuesRequest {
	r.metricNamespace = &metricNamespace
	return r
}

func (r ApiGetFieldsValuesRequest) SearchText(searchText string) ApiGetFieldsValuesRequest {
	r.searchText = &searchText
	return r
}

func (r ApiGetFieldsValuesRequest) Name(name string) ApiGetFieldsValuesRequest {
	r.name = &name
	return r
}

func (r ApiGetFieldsValuesRequest) ExistingQuery(existingQuery string) ApiGetFieldsValuesRequest {
	r.existingQuery = &existingQuery
	return r
}

func (r ApiGetFieldsValuesRequest) Execute() (*GetFieldsValues200Response, *http.Response, error) {
	return r.ApiService.GetFieldsValuesExecute(r)
}

/*
GetFieldsValues Get field values

This endpoint returns field values

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiGetFieldsValuesRequest
*/
func (a *FieldsAPIService) GetFieldsValues(ctx context.Context) ApiGetFieldsValuesRequest {
	return ApiGetFieldsValuesRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return GetFieldsValues200Response
func (a *FieldsAPIService) GetFieldsValuesExecute(r ApiGetFieldsValuesRequest) (*GetFieldsValues200Response, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *GetFieldsValues200Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "FieldsAPIService.GetFieldsValues")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/fields/values"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.signal != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "signal", r.signal, "form", "")
	}
	if r.source != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "source", r.source, "form", "")
	}
	if r.limit != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "limit", r.limit, "form", "")
	}
	if r.startUnixMilli != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "startUnixMilli", r.startUnixMilli, "form", "")
	}
	if r.endUnixMilli != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "endUnixMilli", r.endUnixMilli, "form", "")
	}
	if r.fieldContext != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "fieldContext", r.fieldContext, "form", "")
	}
	if r.fieldDataType != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "fieldDataType", r.fieldDataType, "form", "")
	}
	if r.metricName != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "metricName", r.metricName, "form", "")
	}
	if r.metricNamespace != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "metricNamespace", r.metricNamespace, "form", "")
	}
	if r.searchText != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "searchText", r.searchText, "form", "")
	}
	if r.name != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "name", r.name, "form", "")
	}
	if r.existingQuery != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "existingQuery", r.existingQuery, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["api_key"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["SigNoz-Api-Key"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v RenderErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v RenderErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v RenderErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
