/*
SigNoz

OpenTelemetry-Native Logs, Metrics and Traces in a single pane

API version: 
Contact: support@signoz.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package signozclient

import (
	"encoding/json"
)

// checks if the ConfigPagerdutyConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigPagerdutyConfig{}

// ConfigPagerdutyConfig struct for ConfigPagerdutyConfig
type ConfigPagerdutyConfig struct {
	Class *string `json:"class,omitempty"`
	Client *string `json:"client,omitempty"`
	ClientUrl *string `json:"client_url,omitempty"`
	Component *string `json:"component,omitempty"`
	Description *string `json:"description,omitempty"`
	Details map[string]interface{} `json:"details,omitempty"`
	Group *string `json:"group,omitempty"`
	HttpConfig *ConfigHTTPClientConfig `json:"http_config,omitempty"`
	Images []ConfigPagerdutyImage `json:"images,omitempty"`
	Links []ConfigPagerdutyLink `json:"links,omitempty"`
	RoutingKey *string `json:"routing_key,omitempty"`
	RoutingKeyFile *string `json:"routing_key_file,omitempty"`
	SendResolved *bool `json:"send_resolved,omitempty"`
	ServiceKey *string `json:"service_key,omitempty"`
	ServiceKeyFile *string `json:"service_key_file,omitempty"`
	Severity *string `json:"severity,omitempty"`
	Source *string `json:"source,omitempty"`
	Timeout *int64 `json:"timeout,omitempty"`
	Url map[string]interface{} `json:"url,omitempty"`
}

// NewConfigPagerdutyConfig instantiates a new ConfigPagerdutyConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigPagerdutyConfig() *ConfigPagerdutyConfig {
	this := ConfigPagerdutyConfig{}
	return &this
}

// NewConfigPagerdutyConfigWithDefaults instantiates a new ConfigPagerdutyConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigPagerdutyConfigWithDefaults() *ConfigPagerdutyConfig {
	this := ConfigPagerdutyConfig{}
	return &this
}

// GetClass returns the Class field value if set, zero value otherwise.
func (o *ConfigPagerdutyConfig) GetClass() string {
	if o == nil || IsNil(o.Class) {
		var ret string
		return ret
	}
	return *o.Class
}

// GetClassOk returns a tuple with the Class field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPagerdutyConfig) GetClassOk() (*string, bool) {
	if o == nil || IsNil(o.Class) {
		return nil, false
	}
	return o.Class, true
}

// HasClass returns a boolean if a field has been set.
func (o *ConfigPagerdutyConfig) HasClass() bool {
	if o != nil && !IsNil(o.Class) {
		return true
	}

	return false
}

// SetClass gets a reference to the given string and assigns it to the Class field.
func (o *ConfigPagerdutyConfig) SetClass(v string) {
	o.Class = &v
}

// GetClient returns the Client field value if set, zero value otherwise.
func (o *ConfigPagerdutyConfig) GetClient() string {
	if o == nil || IsNil(o.Client) {
		var ret string
		return ret
	}
	return *o.Client
}

// GetClientOk returns a tuple with the Client field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPagerdutyConfig) GetClientOk() (*string, bool) {
	if o == nil || IsNil(o.Client) {
		return nil, false
	}
	return o.Client, true
}

// HasClient returns a boolean if a field has been set.
func (o *ConfigPagerdutyConfig) HasClient() bool {
	if o != nil && !IsNil(o.Client) {
		return true
	}

	return false
}

// SetClient gets a reference to the given string and assigns it to the Client field.
func (o *ConfigPagerdutyConfig) SetClient(v string) {
	o.Client = &v
}

// GetClientUrl returns the ClientUrl field value if set, zero value otherwise.
func (o *ConfigPagerdutyConfig) GetClientUrl() string {
	if o == nil || IsNil(o.ClientUrl) {
		var ret string
		return ret
	}
	return *o.ClientUrl
}

// GetClientUrlOk returns a tuple with the ClientUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPagerdutyConfig) GetClientUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ClientUrl) {
		return nil, false
	}
	return o.ClientUrl, true
}

// HasClientUrl returns a boolean if a field has been set.
func (o *ConfigPagerdutyConfig) HasClientUrl() bool {
	if o != nil && !IsNil(o.ClientUrl) {
		return true
	}

	return false
}

// SetClientUrl gets a reference to the given string and assigns it to the ClientUrl field.
func (o *ConfigPagerdutyConfig) SetClientUrl(v string) {
	o.ClientUrl = &v
}

// GetComponent returns the Component field value if set, zero value otherwise.
func (o *ConfigPagerdutyConfig) GetComponent() string {
	if o == nil || IsNil(o.Component) {
		var ret string
		return ret
	}
	return *o.Component
}

// GetComponentOk returns a tuple with the Component field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPagerdutyConfig) GetComponentOk() (*string, bool) {
	if o == nil || IsNil(o.Component) {
		return nil, false
	}
	return o.Component, true
}

// HasComponent returns a boolean if a field has been set.
func (o *ConfigPagerdutyConfig) HasComponent() bool {
	if o != nil && !IsNil(o.Component) {
		return true
	}

	return false
}

// SetComponent gets a reference to the given string and assigns it to the Component field.
func (o *ConfigPagerdutyConfig) SetComponent(v string) {
	o.Component = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ConfigPagerdutyConfig) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPagerdutyConfig) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ConfigPagerdutyConfig) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ConfigPagerdutyConfig) SetDescription(v string) {
	o.Description = &v
}

// GetDetails returns the Details field value if set, zero value otherwise.
func (o *ConfigPagerdutyConfig) GetDetails() map[string]interface{} {
	if o == nil || IsNil(o.Details) {
		var ret map[string]interface{}
		return ret
	}
	return o.Details
}

// GetDetailsOk returns a tuple with the Details field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPagerdutyConfig) GetDetailsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Details) {
		return map[string]interface{}{}, false
	}
	return o.Details, true
}

// HasDetails returns a boolean if a field has been set.
func (o *ConfigPagerdutyConfig) HasDetails() bool {
	if o != nil && !IsNil(o.Details) {
		return true
	}

	return false
}

// SetDetails gets a reference to the given map[string]interface{} and assigns it to the Details field.
func (o *ConfigPagerdutyConfig) SetDetails(v map[string]interface{}) {
	o.Details = v
}

// GetGroup returns the Group field value if set, zero value otherwise.
func (o *ConfigPagerdutyConfig) GetGroup() string {
	if o == nil || IsNil(o.Group) {
		var ret string
		return ret
	}
	return *o.Group
}

// GetGroupOk returns a tuple with the Group field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPagerdutyConfig) GetGroupOk() (*string, bool) {
	if o == nil || IsNil(o.Group) {
		return nil, false
	}
	return o.Group, true
}

// HasGroup returns a boolean if a field has been set.
func (o *ConfigPagerdutyConfig) HasGroup() bool {
	if o != nil && !IsNil(o.Group) {
		return true
	}

	return false
}

// SetGroup gets a reference to the given string and assigns it to the Group field.
func (o *ConfigPagerdutyConfig) SetGroup(v string) {
	o.Group = &v
}

// GetHttpConfig returns the HttpConfig field value if set, zero value otherwise.
func (o *ConfigPagerdutyConfig) GetHttpConfig() ConfigHTTPClientConfig {
	if o == nil || IsNil(o.HttpConfig) {
		var ret ConfigHTTPClientConfig
		return ret
	}
	return *o.HttpConfig
}

// GetHttpConfigOk returns a tuple with the HttpConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPagerdutyConfig) GetHttpConfigOk() (*ConfigHTTPClientConfig, bool) {
	if o == nil || IsNil(o.HttpConfig) {
		return nil, false
	}
	return o.HttpConfig, true
}

// HasHttpConfig returns a boolean if a field has been set.
func (o *ConfigPagerdutyConfig) HasHttpConfig() bool {
	if o != nil && !IsNil(o.HttpConfig) {
		return true
	}

	return false
}

// SetHttpConfig gets a reference to the given ConfigHTTPClientConfig and assigns it to the HttpConfig field.
func (o *ConfigPagerdutyConfig) SetHttpConfig(v ConfigHTTPClientConfig) {
	o.HttpConfig = &v
}

// GetImages returns the Images field value if set, zero value otherwise.
func (o *ConfigPagerdutyConfig) GetImages() []ConfigPagerdutyImage {
	if o == nil || IsNil(o.Images) {
		var ret []ConfigPagerdutyImage
		return ret
	}
	return o.Images
}

// GetImagesOk returns a tuple with the Images field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPagerdutyConfig) GetImagesOk() ([]ConfigPagerdutyImage, bool) {
	if o == nil || IsNil(o.Images) {
		return nil, false
	}
	return o.Images, true
}

// HasImages returns a boolean if a field has been set.
func (o *ConfigPagerdutyConfig) HasImages() bool {
	if o != nil && !IsNil(o.Images) {
		return true
	}

	return false
}

// SetImages gets a reference to the given []ConfigPagerdutyImage and assigns it to the Images field.
func (o *ConfigPagerdutyConfig) SetImages(v []ConfigPagerdutyImage) {
	o.Images = v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *ConfigPagerdutyConfig) GetLinks() []ConfigPagerdutyLink {
	if o == nil || IsNil(o.Links) {
		var ret []ConfigPagerdutyLink
		return ret
	}
	return o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPagerdutyConfig) GetLinksOk() ([]ConfigPagerdutyLink, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *ConfigPagerdutyConfig) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given []ConfigPagerdutyLink and assigns it to the Links field.
func (o *ConfigPagerdutyConfig) SetLinks(v []ConfigPagerdutyLink) {
	o.Links = v
}

// GetRoutingKey returns the RoutingKey field value if set, zero value otherwise.
func (o *ConfigPagerdutyConfig) GetRoutingKey() string {
	if o == nil || IsNil(o.RoutingKey) {
		var ret string
		return ret
	}
	return *o.RoutingKey
}

// GetRoutingKeyOk returns a tuple with the RoutingKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPagerdutyConfig) GetRoutingKeyOk() (*string, bool) {
	if o == nil || IsNil(o.RoutingKey) {
		return nil, false
	}
	return o.RoutingKey, true
}

// HasRoutingKey returns a boolean if a field has been set.
func (o *ConfigPagerdutyConfig) HasRoutingKey() bool {
	if o != nil && !IsNil(o.RoutingKey) {
		return true
	}

	return false
}

// SetRoutingKey gets a reference to the given string and assigns it to the RoutingKey field.
func (o *ConfigPagerdutyConfig) SetRoutingKey(v string) {
	o.RoutingKey = &v
}

// GetRoutingKeyFile returns the RoutingKeyFile field value if set, zero value otherwise.
func (o *ConfigPagerdutyConfig) GetRoutingKeyFile() string {
	if o == nil || IsNil(o.RoutingKeyFile) {
		var ret string
		return ret
	}
	return *o.RoutingKeyFile
}

// GetRoutingKeyFileOk returns a tuple with the RoutingKeyFile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPagerdutyConfig) GetRoutingKeyFileOk() (*string, bool) {
	if o == nil || IsNil(o.RoutingKeyFile) {
		return nil, false
	}
	return o.RoutingKeyFile, true
}

// HasRoutingKeyFile returns a boolean if a field has been set.
func (o *ConfigPagerdutyConfig) HasRoutingKeyFile() bool {
	if o != nil && !IsNil(o.RoutingKeyFile) {
		return true
	}

	return false
}

// SetRoutingKeyFile gets a reference to the given string and assigns it to the RoutingKeyFile field.
func (o *ConfigPagerdutyConfig) SetRoutingKeyFile(v string) {
	o.RoutingKeyFile = &v
}

// GetSendResolved returns the SendResolved field value if set, zero value otherwise.
func (o *ConfigPagerdutyConfig) GetSendResolved() bool {
	if o == nil || IsNil(o.SendResolved) {
		var ret bool
		return ret
	}
	return *o.SendResolved
}

// GetSendResolvedOk returns a tuple with the SendResolved field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPagerdutyConfig) GetSendResolvedOk() (*bool, bool) {
	if o == nil || IsNil(o.SendResolved) {
		return nil, false
	}
	return o.SendResolved, true
}

// HasSendResolved returns a boolean if a field has been set.
func (o *ConfigPagerdutyConfig) HasSendResolved() bool {
	if o != nil && !IsNil(o.SendResolved) {
		return true
	}

	return false
}

// SetSendResolved gets a reference to the given bool and assigns it to the SendResolved field.
func (o *ConfigPagerdutyConfig) SetSendResolved(v bool) {
	o.SendResolved = &v
}

// GetServiceKey returns the ServiceKey field value if set, zero value otherwise.
func (o *ConfigPagerdutyConfig) GetServiceKey() string {
	if o == nil || IsNil(o.ServiceKey) {
		var ret string
		return ret
	}
	return *o.ServiceKey
}

// GetServiceKeyOk returns a tuple with the ServiceKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPagerdutyConfig) GetServiceKeyOk() (*string, bool) {
	if o == nil || IsNil(o.ServiceKey) {
		return nil, false
	}
	return o.ServiceKey, true
}

// HasServiceKey returns a boolean if a field has been set.
func (o *ConfigPagerdutyConfig) HasServiceKey() bool {
	if o != nil && !IsNil(o.ServiceKey) {
		return true
	}

	return false
}

// SetServiceKey gets a reference to the given string and assigns it to the ServiceKey field.
func (o *ConfigPagerdutyConfig) SetServiceKey(v string) {
	o.ServiceKey = &v
}

// GetServiceKeyFile returns the ServiceKeyFile field value if set, zero value otherwise.
func (o *ConfigPagerdutyConfig) GetServiceKeyFile() string {
	if o == nil || IsNil(o.ServiceKeyFile) {
		var ret string
		return ret
	}
	return *o.ServiceKeyFile
}

// GetServiceKeyFileOk returns a tuple with the ServiceKeyFile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPagerdutyConfig) GetServiceKeyFileOk() (*string, bool) {
	if o == nil || IsNil(o.ServiceKeyFile) {
		return nil, false
	}
	return o.ServiceKeyFile, true
}

// HasServiceKeyFile returns a boolean if a field has been set.
func (o *ConfigPagerdutyConfig) HasServiceKeyFile() bool {
	if o != nil && !IsNil(o.ServiceKeyFile) {
		return true
	}

	return false
}

// SetServiceKeyFile gets a reference to the given string and assigns it to the ServiceKeyFile field.
func (o *ConfigPagerdutyConfig) SetServiceKeyFile(v string) {
	o.ServiceKeyFile = &v
}

// GetSeverity returns the Severity field value if set, zero value otherwise.
func (o *ConfigPagerdutyConfig) GetSeverity() string {
	if o == nil || IsNil(o.Severity) {
		var ret string
		return ret
	}
	return *o.Severity
}

// GetSeverityOk returns a tuple with the Severity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPagerdutyConfig) GetSeverityOk() (*string, bool) {
	if o == nil || IsNil(o.Severity) {
		return nil, false
	}
	return o.Severity, true
}

// HasSeverity returns a boolean if a field has been set.
func (o *ConfigPagerdutyConfig) HasSeverity() bool {
	if o != nil && !IsNil(o.Severity) {
		return true
	}

	return false
}

// SetSeverity gets a reference to the given string and assigns it to the Severity field.
func (o *ConfigPagerdutyConfig) SetSeverity(v string) {
	o.Severity = &v
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *ConfigPagerdutyConfig) GetSource() string {
	if o == nil || IsNil(o.Source) {
		var ret string
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPagerdutyConfig) GetSourceOk() (*string, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *ConfigPagerdutyConfig) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given string and assigns it to the Source field.
func (o *ConfigPagerdutyConfig) SetSource(v string) {
	o.Source = &v
}

// GetTimeout returns the Timeout field value if set, zero value otherwise.
func (o *ConfigPagerdutyConfig) GetTimeout() int64 {
	if o == nil || IsNil(o.Timeout) {
		var ret int64
		return ret
	}
	return *o.Timeout
}

// GetTimeoutOk returns a tuple with the Timeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPagerdutyConfig) GetTimeoutOk() (*int64, bool) {
	if o == nil || IsNil(o.Timeout) {
		return nil, false
	}
	return o.Timeout, true
}

// HasTimeout returns a boolean if a field has been set.
func (o *ConfigPagerdutyConfig) HasTimeout() bool {
	if o != nil && !IsNil(o.Timeout) {
		return true
	}

	return false
}

// SetTimeout gets a reference to the given int64 and assigns it to the Timeout field.
func (o *ConfigPagerdutyConfig) SetTimeout(v int64) {
	o.Timeout = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *ConfigPagerdutyConfig) GetUrl() map[string]interface{} {
	if o == nil || IsNil(o.Url) {
		var ret map[string]interface{}
		return ret
	}
	return o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPagerdutyConfig) GetUrlOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Url) {
		return map[string]interface{}{}, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *ConfigPagerdutyConfig) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given map[string]interface{} and assigns it to the Url field.
func (o *ConfigPagerdutyConfig) SetUrl(v map[string]interface{}) {
	o.Url = v
}

func (o ConfigPagerdutyConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigPagerdutyConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Class) {
		toSerialize["class"] = o.Class
	}
	if !IsNil(o.Client) {
		toSerialize["client"] = o.Client
	}
	if !IsNil(o.ClientUrl) {
		toSerialize["client_url"] = o.ClientUrl
	}
	if !IsNil(o.Component) {
		toSerialize["component"] = o.Component
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Details) {
		toSerialize["details"] = o.Details
	}
	if !IsNil(o.Group) {
		toSerialize["group"] = o.Group
	}
	if !IsNil(o.HttpConfig) {
		toSerialize["http_config"] = o.HttpConfig
	}
	if !IsNil(o.Images) {
		toSerialize["images"] = o.Images
	}
	if !IsNil(o.Links) {
		toSerialize["links"] = o.Links
	}
	if !IsNil(o.RoutingKey) {
		toSerialize["routing_key"] = o.RoutingKey
	}
	if !IsNil(o.RoutingKeyFile) {
		toSerialize["routing_key_file"] = o.RoutingKeyFile
	}
	if !IsNil(o.SendResolved) {
		toSerialize["send_resolved"] = o.SendResolved
	}
	if !IsNil(o.ServiceKey) {
		toSerialize["service_key"] = o.ServiceKey
	}
	if !IsNil(o.ServiceKeyFile) {
		toSerialize["service_key_file"] = o.ServiceKeyFile
	}
	if !IsNil(o.Severity) {
		toSerialize["severity"] = o.Severity
	}
	if !IsNil(o.Source) {
		toSerialize["source"] = o.Source
	}
	if !IsNil(o.Timeout) {
		toSerialize["timeout"] = o.Timeout
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	return toSerialize, nil
}

type NullableConfigPagerdutyConfig struct {
	value *ConfigPagerdutyConfig
	isSet bool
}

func (v NullableConfigPagerdutyConfig) Get() *ConfigPagerdutyConfig {
	return v.value
}

func (v *NullableConfigPagerdutyConfig) Set(val *ConfigPagerdutyConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigPagerdutyConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigPagerdutyConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigPagerdutyConfig(val *ConfigPagerdutyConfig) *NullableConfigPagerdutyConfig {
	return &NullableConfigPagerdutyConfig{value: val, isSet: true}
}

func (v NullableConfigPagerdutyConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigPagerdutyConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


