/*
SigNoz

OpenTelemetry-Native Logs, Metrics and Traces in a single pane

API version: 
Contact: support@signoz.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package signozclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateSessionByGoogleCallback303Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateSessionByGoogleCallback303Response{}

// CreateSessionByGoogleCallback303Response struct for CreateSessionByGoogleCallback303Response
type CreateSessionByGoogleCallback303Response struct {
	Data AuthtypesGettableToken `json:"data"`
	Status string `json:"status"`
}

type _CreateSessionByGoogleCallback303Response CreateSessionByGoogleCallback303Response

// NewCreateSessionByGoogleCallback303Response instantiates a new CreateSessionByGoogleCallback303Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateSessionByGoogleCallback303Response(data AuthtypesGettableToken, status string) *CreateSessionByGoogleCallback303Response {
	this := CreateSessionByGoogleCallback303Response{}
	this.Data = data
	this.Status = status
	return &this
}

// NewCreateSessionByGoogleCallback303ResponseWithDefaults instantiates a new CreateSessionByGoogleCallback303Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateSessionByGoogleCallback303ResponseWithDefaults() *CreateSessionByGoogleCallback303Response {
	this := CreateSessionByGoogleCallback303Response{}
	return &this
}

// GetData returns the Data field value
func (o *CreateSessionByGoogleCallback303Response) GetData() AuthtypesGettableToken {
	if o == nil {
		var ret AuthtypesGettableToken
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CreateSessionByGoogleCallback303Response) GetDataOk() (*AuthtypesGettableToken, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *CreateSessionByGoogleCallback303Response) SetData(v AuthtypesGettableToken) {
	o.Data = v
}

// GetStatus returns the Status field value
func (o *CreateSessionByGoogleCallback303Response) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *CreateSessionByGoogleCallback303Response) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *CreateSessionByGoogleCallback303Response) SetStatus(v string) {
	o.Status = v
}

func (o CreateSessionByGoogleCallback303Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateSessionByGoogleCallback303Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *CreateSessionByGoogleCallback303Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateSessionByGoogleCallback303Response := _CreateSessionByGoogleCallback303Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateSessionByGoogleCallback303Response)

	if err != nil {
		return err
	}

	*o = CreateSessionByGoogleCallback303Response(varCreateSessionByGoogleCallback303Response)

	return err
}

type NullableCreateSessionByGoogleCallback303Response struct {
	value *CreateSessionByGoogleCallback303Response
	isSet bool
}

func (v NullableCreateSessionByGoogleCallback303Response) Get() *CreateSessionByGoogleCallback303Response {
	return v.value
}

func (v *NullableCreateSessionByGoogleCallback303Response) Set(val *CreateSessionByGoogleCallback303Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateSessionByGoogleCallback303Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateSessionByGoogleCallback303Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateSessionByGoogleCallback303Response(val *CreateSessionByGoogleCallback303Response) *NullableCreateSessionByGoogleCallback303Response {
	return &NullableCreateSessionByGoogleCallback303Response{value: val, isSet: true}
}

func (v NullableCreateSessionByGoogleCallback303Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateSessionByGoogleCallback303Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


