/*
SigNoz

OpenTelemetry-Native Logs, Metrics and Traces in a single pane

API version: 
Contact: support@signoz.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package signozclient

import (
	"encoding/json"
)

// checks if the CloudintegrationtypesConnectionArtifact type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CloudintegrationtypesConnectionArtifact{}

// CloudintegrationtypesConnectionArtifact struct for CloudintegrationtypesConnectionArtifact
type CloudintegrationtypesConnectionArtifact struct {
	Aws *CloudintegrationtypesAWSConnectionArtifact `json:"aws,omitempty"`
	Azure *CloudintegrationtypesAzureConnectionArtifact `json:"azure,omitempty"`
}

// NewCloudintegrationtypesConnectionArtifact instantiates a new CloudintegrationtypesConnectionArtifact object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCloudintegrationtypesConnectionArtifact() *CloudintegrationtypesConnectionArtifact {
	this := CloudintegrationtypesConnectionArtifact{}
	return &this
}

// NewCloudintegrationtypesConnectionArtifactWithDefaults instantiates a new CloudintegrationtypesConnectionArtifact object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCloudintegrationtypesConnectionArtifactWithDefaults() *CloudintegrationtypesConnectionArtifact {
	this := CloudintegrationtypesConnectionArtifact{}
	return &this
}

// GetAws returns the Aws field value if set, zero value otherwise.
func (o *CloudintegrationtypesConnectionArtifact) GetAws() CloudintegrationtypesAWSConnectionArtifact {
	if o == nil || IsNil(o.Aws) {
		var ret CloudintegrationtypesAWSConnectionArtifact
		return ret
	}
	return *o.Aws
}

// GetAwsOk returns a tuple with the Aws field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudintegrationtypesConnectionArtifact) GetAwsOk() (*CloudintegrationtypesAWSConnectionArtifact, bool) {
	if o == nil || IsNil(o.Aws) {
		return nil, false
	}
	return o.Aws, true
}

// HasAws returns a boolean if a field has been set.
func (o *CloudintegrationtypesConnectionArtifact) HasAws() bool {
	if o != nil && !IsNil(o.Aws) {
		return true
	}

	return false
}

// SetAws gets a reference to the given CloudintegrationtypesAWSConnectionArtifact and assigns it to the Aws field.
func (o *CloudintegrationtypesConnectionArtifact) SetAws(v CloudintegrationtypesAWSConnectionArtifact) {
	o.Aws = &v
}

// GetAzure returns the Azure field value if set, zero value otherwise.
func (o *CloudintegrationtypesConnectionArtifact) GetAzure() CloudintegrationtypesAzureConnectionArtifact {
	if o == nil || IsNil(o.Azure) {
		var ret CloudintegrationtypesAzureConnectionArtifact
		return ret
	}
	return *o.Azure
}

// GetAzureOk returns a tuple with the Azure field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudintegrationtypesConnectionArtifact) GetAzureOk() (*CloudintegrationtypesAzureConnectionArtifact, bool) {
	if o == nil || IsNil(o.Azure) {
		return nil, false
	}
	return o.Azure, true
}

// HasAzure returns a boolean if a field has been set.
func (o *CloudintegrationtypesConnectionArtifact) HasAzure() bool {
	if o != nil && !IsNil(o.Azure) {
		return true
	}

	return false
}

// SetAzure gets a reference to the given CloudintegrationtypesAzureConnectionArtifact and assigns it to the Azure field.
func (o *CloudintegrationtypesConnectionArtifact) SetAzure(v CloudintegrationtypesAzureConnectionArtifact) {
	o.Azure = &v
}

func (o CloudintegrationtypesConnectionArtifact) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CloudintegrationtypesConnectionArtifact) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Aws) {
		toSerialize["aws"] = o.Aws
	}
	if !IsNil(o.Azure) {
		toSerialize["azure"] = o.Azure
	}
	return toSerialize, nil
}

type NullableCloudintegrationtypesConnectionArtifact struct {
	value *CloudintegrationtypesConnectionArtifact
	isSet bool
}

func (v NullableCloudintegrationtypesConnectionArtifact) Get() *CloudintegrationtypesConnectionArtifact {
	return v.value
}

func (v *NullableCloudintegrationtypesConnectionArtifact) Set(val *CloudintegrationtypesConnectionArtifact) {
	v.value = val
	v.isSet = true
}

func (v NullableCloudintegrationtypesConnectionArtifact) IsSet() bool {
	return v.isSet
}

func (v *NullableCloudintegrationtypesConnectionArtifact) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCloudintegrationtypesConnectionArtifact(val *CloudintegrationtypesConnectionArtifact) *NullableCloudintegrationtypesConnectionArtifact {
	return &NullableCloudintegrationtypesConnectionArtifact{value: val, isSet: true}
}

func (v NullableCloudintegrationtypesConnectionArtifact) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCloudintegrationtypesConnectionArtifact) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


