/*
SigNoz

OpenTelemetry-Native Logs, Metrics and Traces in a single pane

API version: 
Contact: support@signoz.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package signozclient

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the GatewaytypesPostableIngestionKey type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GatewaytypesPostableIngestionKey{}

// GatewaytypesPostableIngestionKey struct for GatewaytypesPostableIngestionKey
type GatewaytypesPostableIngestionKey struct {
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	Name string `json:"name"`
	Tags []string `json:"tags,omitempty"`
}

type _GatewaytypesPostableIngestionKey GatewaytypesPostableIngestionKey

// NewGatewaytypesPostableIngestionKey instantiates a new GatewaytypesPostableIngestionKey object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGatewaytypesPostableIngestionKey(name string) *GatewaytypesPostableIngestionKey {
	this := GatewaytypesPostableIngestionKey{}
	this.Name = name
	return &this
}

// NewGatewaytypesPostableIngestionKeyWithDefaults instantiates a new GatewaytypesPostableIngestionKey object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGatewaytypesPostableIngestionKeyWithDefaults() *GatewaytypesPostableIngestionKey {
	this := GatewaytypesPostableIngestionKey{}
	return &this
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise.
func (o *GatewaytypesPostableIngestionKey) GetExpiresAt() time.Time {
	if o == nil || IsNil(o.ExpiresAt) {
		var ret time.Time
		return ret
	}
	return *o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewaytypesPostableIngestionKey) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ExpiresAt) {
		return nil, false
	}
	return o.ExpiresAt, true
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *GatewaytypesPostableIngestionKey) HasExpiresAt() bool {
	if o != nil && !IsNil(o.ExpiresAt) {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given time.Time and assigns it to the ExpiresAt field.
func (o *GatewaytypesPostableIngestionKey) SetExpiresAt(v time.Time) {
	o.ExpiresAt = &v
}

// GetName returns the Name field value
func (o *GatewaytypesPostableIngestionKey) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GatewaytypesPostableIngestionKey) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GatewaytypesPostableIngestionKey) SetName(v string) {
	o.Name = v
}

// GetTags returns the Tags field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GatewaytypesPostableIngestionKey) GetTags() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GatewaytypesPostableIngestionKey) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *GatewaytypesPostableIngestionKey) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *GatewaytypesPostableIngestionKey) SetTags(v []string) {
	o.Tags = v
}

func (o GatewaytypesPostableIngestionKey) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GatewaytypesPostableIngestionKey) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ExpiresAt) {
		toSerialize["expires_at"] = o.ExpiresAt
	}
	toSerialize["name"] = o.Name
	if o.Tags != nil {
		toSerialize["tags"] = o.Tags
	}
	return toSerialize, nil
}

func (o *GatewaytypesPostableIngestionKey) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGatewaytypesPostableIngestionKey := _GatewaytypesPostableIngestionKey{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGatewaytypesPostableIngestionKey)

	if err != nil {
		return err
	}

	*o = GatewaytypesPostableIngestionKey(varGatewaytypesPostableIngestionKey)

	return err
}

type NullableGatewaytypesPostableIngestionKey struct {
	value *GatewaytypesPostableIngestionKey
	isSet bool
}

func (v NullableGatewaytypesPostableIngestionKey) Get() *GatewaytypesPostableIngestionKey {
	return v.value
}

func (v *NullableGatewaytypesPostableIngestionKey) Set(val *GatewaytypesPostableIngestionKey) {
	v.value = val
	v.isSet = true
}

func (v NullableGatewaytypesPostableIngestionKey) IsSet() bool {
	return v.isSet
}

func (v *NullableGatewaytypesPostableIngestionKey) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGatewaytypesPostableIngestionKey(val *GatewaytypesPostableIngestionKey) *NullableGatewaytypesPostableIngestionKey {
	return &NullableGatewaytypesPostableIngestionKey{value: val, isSet: true}
}

func (v NullableGatewaytypesPostableIngestionKey) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGatewaytypesPostableIngestionKey) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


