/*
SigNoz

OpenTelemetry-Native Logs, Metrics and Traces in a single pane

API version: 
Contact: support@signoz.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package signozclient

import (
	"encoding/json"
)

// checks if the AuthtypesUpdatableAuthDomain type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthtypesUpdatableAuthDomain{}

// AuthtypesUpdatableAuthDomain struct for AuthtypesUpdatableAuthDomain
type AuthtypesUpdatableAuthDomain struct {
	Config *AuthtypesAuthDomainConfig `json:"config,omitempty"`
}

// NewAuthtypesUpdatableAuthDomain instantiates a new AuthtypesUpdatableAuthDomain object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthtypesUpdatableAuthDomain() *AuthtypesUpdatableAuthDomain {
	this := AuthtypesUpdatableAuthDomain{}
	return &this
}

// NewAuthtypesUpdatableAuthDomainWithDefaults instantiates a new AuthtypesUpdatableAuthDomain object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthtypesUpdatableAuthDomainWithDefaults() *AuthtypesUpdatableAuthDomain {
	this := AuthtypesUpdatableAuthDomain{}
	return &this
}

// GetConfig returns the Config field value if set, zero value otherwise.
func (o *AuthtypesUpdatableAuthDomain) GetConfig() AuthtypesAuthDomainConfig {
	if o == nil || IsNil(o.Config) {
		var ret AuthtypesAuthDomainConfig
		return ret
	}
	return *o.Config
}

// GetConfigOk returns a tuple with the Config field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthtypesUpdatableAuthDomain) GetConfigOk() (*AuthtypesAuthDomainConfig, bool) {
	if o == nil || IsNil(o.Config) {
		return nil, false
	}
	return o.Config, true
}

// HasConfig returns a boolean if a field has been set.
func (o *AuthtypesUpdatableAuthDomain) HasConfig() bool {
	if o != nil && !IsNil(o.Config) {
		return true
	}

	return false
}

// SetConfig gets a reference to the given AuthtypesAuthDomainConfig and assigns it to the Config field.
func (o *AuthtypesUpdatableAuthDomain) SetConfig(v AuthtypesAuthDomainConfig) {
	o.Config = &v
}

func (o AuthtypesUpdatableAuthDomain) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthtypesUpdatableAuthDomain) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Config) {
		toSerialize["config"] = o.Config
	}
	return toSerialize, nil
}

type NullableAuthtypesUpdatableAuthDomain struct {
	value *AuthtypesUpdatableAuthDomain
	isSet bool
}

func (v NullableAuthtypesUpdatableAuthDomain) Get() *AuthtypesUpdatableAuthDomain {
	return v.value
}

func (v *NullableAuthtypesUpdatableAuthDomain) Set(val *AuthtypesUpdatableAuthDomain) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthtypesUpdatableAuthDomain) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthtypesUpdatableAuthDomain) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthtypesUpdatableAuthDomain(val *AuthtypesUpdatableAuthDomain) *NullableAuthtypesUpdatableAuthDomain {
	return &NullableAuthtypesUpdatableAuthDomain{value: val, isSet: true}
}

func (v NullableAuthtypesUpdatableAuthDomain) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthtypesUpdatableAuthDomain) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


