/*
SigNoz

OpenTelemetry-Native Logs, Metrics and Traces in a single pane

API version: 
Contact: support@signoz.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package signozclient

import (
	"encoding/json"
)

// checks if the GatewaytypesLimitValue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GatewaytypesLimitValue{}

// GatewaytypesLimitValue struct for GatewaytypesLimitValue
type GatewaytypesLimitValue struct {
	Count NullableInt32 `json:"count,omitempty"`
	Size NullableInt32 `json:"size,omitempty"`
}

// NewGatewaytypesLimitValue instantiates a new GatewaytypesLimitValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGatewaytypesLimitValue() *GatewaytypesLimitValue {
	this := GatewaytypesLimitValue{}
	return &this
}

// NewGatewaytypesLimitValueWithDefaults instantiates a new GatewaytypesLimitValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGatewaytypesLimitValueWithDefaults() *GatewaytypesLimitValue {
	this := GatewaytypesLimitValue{}
	return &this
}

// GetCount returns the Count field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GatewaytypesLimitValue) GetCount() int32 {
	if o == nil || IsNil(o.Count.Get()) {
		var ret int32
		return ret
	}
	return *o.Count.Get()
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GatewaytypesLimitValue) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Count.Get(), o.Count.IsSet()
}

// HasCount returns a boolean if a field has been set.
func (o *GatewaytypesLimitValue) HasCount() bool {
	if o != nil && o.Count.IsSet() {
		return true
	}

	return false
}

// SetCount gets a reference to the given NullableInt32 and assigns it to the Count field.
func (o *GatewaytypesLimitValue) SetCount(v int32) {
	o.Count.Set(&v)
}
// SetCountNil sets the value for Count to be an explicit nil
func (o *GatewaytypesLimitValue) SetCountNil() {
	o.Count.Set(nil)
}

// UnsetCount ensures that no value is present for Count, not even an explicit nil
func (o *GatewaytypesLimitValue) UnsetCount() {
	o.Count.Unset()
}

// GetSize returns the Size field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GatewaytypesLimitValue) GetSize() int32 {
	if o == nil || IsNil(o.Size.Get()) {
		var ret int32
		return ret
	}
	return *o.Size.Get()
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GatewaytypesLimitValue) GetSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Size.Get(), o.Size.IsSet()
}

// HasSize returns a boolean if a field has been set.
func (o *GatewaytypesLimitValue) HasSize() bool {
	if o != nil && o.Size.IsSet() {
		return true
	}

	return false
}

// SetSize gets a reference to the given NullableInt32 and assigns it to the Size field.
func (o *GatewaytypesLimitValue) SetSize(v int32) {
	o.Size.Set(&v)
}
// SetSizeNil sets the value for Size to be an explicit nil
func (o *GatewaytypesLimitValue) SetSizeNil() {
	o.Size.Set(nil)
}

// UnsetSize ensures that no value is present for Size, not even an explicit nil
func (o *GatewaytypesLimitValue) UnsetSize() {
	o.Size.Unset()
}

func (o GatewaytypesLimitValue) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GatewaytypesLimitValue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Count.IsSet() {
		toSerialize["count"] = o.Count.Get()
	}
	if o.Size.IsSet() {
		toSerialize["size"] = o.Size.Get()
	}
	return toSerialize, nil
}

type NullableGatewaytypesLimitValue struct {
	value *GatewaytypesLimitValue
	isSet bool
}

func (v NullableGatewaytypesLimitValue) Get() *GatewaytypesLimitValue {
	return v.value
}

func (v *NullableGatewaytypesLimitValue) Set(val *GatewaytypesLimitValue) {
	v.value = val
	v.isSet = true
}

func (v NullableGatewaytypesLimitValue) IsSet() bool {
	return v.isSet
}

func (v *NullableGatewaytypesLimitValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGatewaytypesLimitValue(val *GatewaytypesLimitValue) *NullableGatewaytypesLimitValue {
	return &NullableGatewaytypesLimitValue{value: val, isSet: true}
}

func (v NullableGatewaytypesLimitValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGatewaytypesLimitValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


