/*
SigNoz

OpenTelemetry-Native Logs, Metrics and Traces in a single pane

API version: 
Contact: support@signoz.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package signozclient

import (
	"encoding/json"
)

// checks if the AuthtypesRoleMapping type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthtypesRoleMapping{}

// AuthtypesRoleMapping struct for AuthtypesRoleMapping
type AuthtypesRoleMapping struct {
	DefaultRole *string `json:"defaultRole,omitempty"`
	GroupMappings map[string]string `json:"groupMappings,omitempty"`
	UseRoleAttribute *bool `json:"useRoleAttribute,omitempty"`
}

// NewAuthtypesRoleMapping instantiates a new AuthtypesRoleMapping object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthtypesRoleMapping() *AuthtypesRoleMapping {
	this := AuthtypesRoleMapping{}
	return &this
}

// NewAuthtypesRoleMappingWithDefaults instantiates a new AuthtypesRoleMapping object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthtypesRoleMappingWithDefaults() *AuthtypesRoleMapping {
	this := AuthtypesRoleMapping{}
	return &this
}

// GetDefaultRole returns the DefaultRole field value if set, zero value otherwise.
func (o *AuthtypesRoleMapping) GetDefaultRole() string {
	if o == nil || IsNil(o.DefaultRole) {
		var ret string
		return ret
	}
	return *o.DefaultRole
}

// GetDefaultRoleOk returns a tuple with the DefaultRole field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthtypesRoleMapping) GetDefaultRoleOk() (*string, bool) {
	if o == nil || IsNil(o.DefaultRole) {
		return nil, false
	}
	return o.DefaultRole, true
}

// HasDefaultRole returns a boolean if a field has been set.
func (o *AuthtypesRoleMapping) HasDefaultRole() bool {
	if o != nil && !IsNil(o.DefaultRole) {
		return true
	}

	return false
}

// SetDefaultRole gets a reference to the given string and assigns it to the DefaultRole field.
func (o *AuthtypesRoleMapping) SetDefaultRole(v string) {
	o.DefaultRole = &v
}

// GetGroupMappings returns the GroupMappings field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AuthtypesRoleMapping) GetGroupMappings() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}
	return o.GroupMappings
}

// GetGroupMappingsOk returns a tuple with the GroupMappings field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AuthtypesRoleMapping) GetGroupMappingsOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.GroupMappings) {
		return nil, false
	}
	return &o.GroupMappings, true
}

// HasGroupMappings returns a boolean if a field has been set.
func (o *AuthtypesRoleMapping) HasGroupMappings() bool {
	if o != nil && !IsNil(o.GroupMappings) {
		return true
	}

	return false
}

// SetGroupMappings gets a reference to the given map[string]string and assigns it to the GroupMappings field.
func (o *AuthtypesRoleMapping) SetGroupMappings(v map[string]string) {
	o.GroupMappings = v
}

// GetUseRoleAttribute returns the UseRoleAttribute field value if set, zero value otherwise.
func (o *AuthtypesRoleMapping) GetUseRoleAttribute() bool {
	if o == nil || IsNil(o.UseRoleAttribute) {
		var ret bool
		return ret
	}
	return *o.UseRoleAttribute
}

// GetUseRoleAttributeOk returns a tuple with the UseRoleAttribute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthtypesRoleMapping) GetUseRoleAttributeOk() (*bool, bool) {
	if o == nil || IsNil(o.UseRoleAttribute) {
		return nil, false
	}
	return o.UseRoleAttribute, true
}

// HasUseRoleAttribute returns a boolean if a field has been set.
func (o *AuthtypesRoleMapping) HasUseRoleAttribute() bool {
	if o != nil && !IsNil(o.UseRoleAttribute) {
		return true
	}

	return false
}

// SetUseRoleAttribute gets a reference to the given bool and assigns it to the UseRoleAttribute field.
func (o *AuthtypesRoleMapping) SetUseRoleAttribute(v bool) {
	o.UseRoleAttribute = &v
}

func (o AuthtypesRoleMapping) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthtypesRoleMapping) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DefaultRole) {
		toSerialize["defaultRole"] = o.DefaultRole
	}
	if o.GroupMappings != nil {
		toSerialize["groupMappings"] = o.GroupMappings
	}
	if !IsNil(o.UseRoleAttribute) {
		toSerialize["useRoleAttribute"] = o.UseRoleAttribute
	}
	return toSerialize, nil
}

type NullableAuthtypesRoleMapping struct {
	value *AuthtypesRoleMapping
	isSet bool
}

func (v NullableAuthtypesRoleMapping) Get() *AuthtypesRoleMapping {
	return v.value
}

func (v *NullableAuthtypesRoleMapping) Set(val *AuthtypesRoleMapping) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthtypesRoleMapping) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthtypesRoleMapping) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthtypesRoleMapping(val *AuthtypesRoleMapping) *NullableAuthtypesRoleMapping {
	return &NullableAuthtypesRoleMapping{value: val, isSet: true}
}

func (v NullableAuthtypesRoleMapping) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthtypesRoleMapping) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


