/*
SigNoz

OpenTelemetry-Native Logs, Metrics and Traces in a single pane

API version: 
Contact: support@signoz.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package signozclient

import (
	"encoding/json"
)

// checks if the CloudintegrationtypesAccountConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CloudintegrationtypesAccountConfig{}

// CloudintegrationtypesAccountConfig struct for CloudintegrationtypesAccountConfig
type CloudintegrationtypesAccountConfig struct {
	Aws *CloudintegrationtypesAWSAccountConfig `json:"aws,omitempty"`
	Azure *CloudintegrationtypesAzureAccountConfig `json:"azure,omitempty"`
}

// NewCloudintegrationtypesAccountConfig instantiates a new CloudintegrationtypesAccountConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCloudintegrationtypesAccountConfig() *CloudintegrationtypesAccountConfig {
	this := CloudintegrationtypesAccountConfig{}
	return &this
}

// NewCloudintegrationtypesAccountConfigWithDefaults instantiates a new CloudintegrationtypesAccountConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCloudintegrationtypesAccountConfigWithDefaults() *CloudintegrationtypesAccountConfig {
	this := CloudintegrationtypesAccountConfig{}
	return &this
}

// GetAws returns the Aws field value if set, zero value otherwise.
func (o *CloudintegrationtypesAccountConfig) GetAws() CloudintegrationtypesAWSAccountConfig {
	if o == nil || IsNil(o.Aws) {
		var ret CloudintegrationtypesAWSAccountConfig
		return ret
	}
	return *o.Aws
}

// GetAwsOk returns a tuple with the Aws field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudintegrationtypesAccountConfig) GetAwsOk() (*CloudintegrationtypesAWSAccountConfig, bool) {
	if o == nil || IsNil(o.Aws) {
		return nil, false
	}
	return o.Aws, true
}

// HasAws returns a boolean if a field has been set.
func (o *CloudintegrationtypesAccountConfig) HasAws() bool {
	if o != nil && !IsNil(o.Aws) {
		return true
	}

	return false
}

// SetAws gets a reference to the given CloudintegrationtypesAWSAccountConfig and assigns it to the Aws field.
func (o *CloudintegrationtypesAccountConfig) SetAws(v CloudintegrationtypesAWSAccountConfig) {
	o.Aws = &v
}

// GetAzure returns the Azure field value if set, zero value otherwise.
func (o *CloudintegrationtypesAccountConfig) GetAzure() CloudintegrationtypesAzureAccountConfig {
	if o == nil || IsNil(o.Azure) {
		var ret CloudintegrationtypesAzureAccountConfig
		return ret
	}
	return *o.Azure
}

// GetAzureOk returns a tuple with the Azure field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudintegrationtypesAccountConfig) GetAzureOk() (*CloudintegrationtypesAzureAccountConfig, bool) {
	if o == nil || IsNil(o.Azure) {
		return nil, false
	}
	return o.Azure, true
}

// HasAzure returns a boolean if a field has been set.
func (o *CloudintegrationtypesAccountConfig) HasAzure() bool {
	if o != nil && !IsNil(o.Azure) {
		return true
	}

	return false
}

// SetAzure gets a reference to the given CloudintegrationtypesAzureAccountConfig and assigns it to the Azure field.
func (o *CloudintegrationtypesAccountConfig) SetAzure(v CloudintegrationtypesAzureAccountConfig) {
	o.Azure = &v
}

func (o CloudintegrationtypesAccountConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CloudintegrationtypesAccountConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Aws) {
		toSerialize["aws"] = o.Aws
	}
	if !IsNil(o.Azure) {
		toSerialize["azure"] = o.Azure
	}
	return toSerialize, nil
}

type NullableCloudintegrationtypesAccountConfig struct {
	value *CloudintegrationtypesAccountConfig
	isSet bool
}

func (v NullableCloudintegrationtypesAccountConfig) Get() *CloudintegrationtypesAccountConfig {
	return v.value
}

func (v *NullableCloudintegrationtypesAccountConfig) Set(val *CloudintegrationtypesAccountConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableCloudintegrationtypesAccountConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableCloudintegrationtypesAccountConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCloudintegrationtypesAccountConfig(val *CloudintegrationtypesAccountConfig) *NullableCloudintegrationtypesAccountConfig {
	return &NullableCloudintegrationtypesAccountConfig{value: val, isSet: true}
}

func (v NullableCloudintegrationtypesAccountConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCloudintegrationtypesAccountConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


