/*
SigNoz

OpenTelemetry-Native Logs, Metrics and Traces in a single pane

API version: 
Contact: support@signoz.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package signozclient

import (
	"encoding/json"
)

// checks if the SpantypesUpdatableSpanMapperGroup type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SpantypesUpdatableSpanMapperGroup{}

// SpantypesUpdatableSpanMapperGroup struct for SpantypesUpdatableSpanMapperGroup
type SpantypesUpdatableSpanMapperGroup struct {
	Condition *SpantypesSpanMapperGroupCondition `json:"condition,omitempty"`
	Enabled NullableBool `json:"enabled,omitempty"`
	Name NullableString `json:"name,omitempty"`
}

// NewSpantypesUpdatableSpanMapperGroup instantiates a new SpantypesUpdatableSpanMapperGroup object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSpantypesUpdatableSpanMapperGroup() *SpantypesUpdatableSpanMapperGroup {
	this := SpantypesUpdatableSpanMapperGroup{}
	return &this
}

// NewSpantypesUpdatableSpanMapperGroupWithDefaults instantiates a new SpantypesUpdatableSpanMapperGroup object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSpantypesUpdatableSpanMapperGroupWithDefaults() *SpantypesUpdatableSpanMapperGroup {
	this := SpantypesUpdatableSpanMapperGroup{}
	return &this
}

// GetCondition returns the Condition field value if set, zero value otherwise.
func (o *SpantypesUpdatableSpanMapperGroup) GetCondition() SpantypesSpanMapperGroupCondition {
	if o == nil || IsNil(o.Condition) {
		var ret SpantypesSpanMapperGroupCondition
		return ret
	}
	return *o.Condition
}

// GetConditionOk returns a tuple with the Condition field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpantypesUpdatableSpanMapperGroup) GetConditionOk() (*SpantypesSpanMapperGroupCondition, bool) {
	if o == nil || IsNil(o.Condition) {
		return nil, false
	}
	return o.Condition, true
}

// HasCondition returns a boolean if a field has been set.
func (o *SpantypesUpdatableSpanMapperGroup) HasCondition() bool {
	if o != nil && !IsNil(o.Condition) {
		return true
	}

	return false
}

// SetCondition gets a reference to the given SpantypesSpanMapperGroupCondition and assigns it to the Condition field.
func (o *SpantypesUpdatableSpanMapperGroup) SetCondition(v SpantypesSpanMapperGroupCondition) {
	o.Condition = &v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SpantypesUpdatableSpanMapperGroup) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled.Get()) {
		var ret bool
		return ret
	}
	return *o.Enabled.Get()
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SpantypesUpdatableSpanMapperGroup) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Enabled.Get(), o.Enabled.IsSet()
}

// HasEnabled returns a boolean if a field has been set.
func (o *SpantypesUpdatableSpanMapperGroup) HasEnabled() bool {
	if o != nil && o.Enabled.IsSet() {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given NullableBool and assigns it to the Enabled field.
func (o *SpantypesUpdatableSpanMapperGroup) SetEnabled(v bool) {
	o.Enabled.Set(&v)
}
// SetEnabledNil sets the value for Enabled to be an explicit nil
func (o *SpantypesUpdatableSpanMapperGroup) SetEnabledNil() {
	o.Enabled.Set(nil)
}

// UnsetEnabled ensures that no value is present for Enabled, not even an explicit nil
func (o *SpantypesUpdatableSpanMapperGroup) UnsetEnabled() {
	o.Enabled.Unset()
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SpantypesUpdatableSpanMapperGroup) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SpantypesUpdatableSpanMapperGroup) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *SpantypesUpdatableSpanMapperGroup) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *SpantypesUpdatableSpanMapperGroup) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *SpantypesUpdatableSpanMapperGroup) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *SpantypesUpdatableSpanMapperGroup) UnsetName() {
	o.Name.Unset()
}

func (o SpantypesUpdatableSpanMapperGroup) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SpantypesUpdatableSpanMapperGroup) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Condition) {
		toSerialize["condition"] = o.Condition
	}
	if o.Enabled.IsSet() {
		toSerialize["enabled"] = o.Enabled.Get()
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	return toSerialize, nil
}

type NullableSpantypesUpdatableSpanMapperGroup struct {
	value *SpantypesUpdatableSpanMapperGroup
	isSet bool
}

func (v NullableSpantypesUpdatableSpanMapperGroup) Get() *SpantypesUpdatableSpanMapperGroup {
	return v.value
}

func (v *NullableSpantypesUpdatableSpanMapperGroup) Set(val *SpantypesUpdatableSpanMapperGroup) {
	v.value = val
	v.isSet = true
}

func (v NullableSpantypesUpdatableSpanMapperGroup) IsSet() bool {
	return v.isSet
}

func (v *NullableSpantypesUpdatableSpanMapperGroup) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSpantypesUpdatableSpanMapperGroup(val *SpantypesUpdatableSpanMapperGroup) *NullableSpantypesUpdatableSpanMapperGroup {
	return &NullableSpantypesUpdatableSpanMapperGroup{value: val, isSet: true}
}

func (v NullableSpantypesUpdatableSpanMapperGroup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSpantypesUpdatableSpanMapperGroup) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


