/*
SigNoz

OpenTelemetry-Native Logs, Metrics and Traces in a single pane

API version: 
Contact: support@signoz.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package signozclient

import (
	"encoding/json"
)

// checks if the AuthtypesAttributeMapping type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthtypesAttributeMapping{}

// AuthtypesAttributeMapping struct for AuthtypesAttributeMapping
type AuthtypesAttributeMapping struct {
	Email *string `json:"email,omitempty"`
	Groups *string `json:"groups,omitempty"`
	Name *string `json:"name,omitempty"`
	Role *string `json:"role,omitempty"`
}

// NewAuthtypesAttributeMapping instantiates a new AuthtypesAttributeMapping object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthtypesAttributeMapping() *AuthtypesAttributeMapping {
	this := AuthtypesAttributeMapping{}
	return &this
}

// NewAuthtypesAttributeMappingWithDefaults instantiates a new AuthtypesAttributeMapping object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthtypesAttributeMappingWithDefaults() *AuthtypesAttributeMapping {
	this := AuthtypesAttributeMapping{}
	return &this
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *AuthtypesAttributeMapping) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthtypesAttributeMapping) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *AuthtypesAttributeMapping) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *AuthtypesAttributeMapping) SetEmail(v string) {
	o.Email = &v
}

// GetGroups returns the Groups field value if set, zero value otherwise.
func (o *AuthtypesAttributeMapping) GetGroups() string {
	if o == nil || IsNil(o.Groups) {
		var ret string
		return ret
	}
	return *o.Groups
}

// GetGroupsOk returns a tuple with the Groups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthtypesAttributeMapping) GetGroupsOk() (*string, bool) {
	if o == nil || IsNil(o.Groups) {
		return nil, false
	}
	return o.Groups, true
}

// HasGroups returns a boolean if a field has been set.
func (o *AuthtypesAttributeMapping) HasGroups() bool {
	if o != nil && !IsNil(o.Groups) {
		return true
	}

	return false
}

// SetGroups gets a reference to the given string and assigns it to the Groups field.
func (o *AuthtypesAttributeMapping) SetGroups(v string) {
	o.Groups = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *AuthtypesAttributeMapping) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthtypesAttributeMapping) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *AuthtypesAttributeMapping) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *AuthtypesAttributeMapping) SetName(v string) {
	o.Name = &v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *AuthtypesAttributeMapping) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthtypesAttributeMapping) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *AuthtypesAttributeMapping) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *AuthtypesAttributeMapping) SetRole(v string) {
	o.Role = &v
}

func (o AuthtypesAttributeMapping) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthtypesAttributeMapping) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.Groups) {
		toSerialize["groups"] = o.Groups
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	return toSerialize, nil
}

type NullableAuthtypesAttributeMapping struct {
	value *AuthtypesAttributeMapping
	isSet bool
}

func (v NullableAuthtypesAttributeMapping) Get() *AuthtypesAttributeMapping {
	return v.value
}

func (v *NullableAuthtypesAttributeMapping) Set(val *AuthtypesAttributeMapping) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthtypesAttributeMapping) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthtypesAttributeMapping) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthtypesAttributeMapping(val *AuthtypesAttributeMapping) *NullableAuthtypesAttributeMapping {
	return &NullableAuthtypesAttributeMapping{value: val, isSet: true}
}

func (v NullableAuthtypesAttributeMapping) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthtypesAttributeMapping) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


