/*
SigNoz

OpenTelemetry-Native Logs, Metrics and Traces in a single pane

API version: 
Contact: support@signoz.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package signozclient

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// AuthtypesAuthDomainConfig - struct for AuthtypesAuthDomainConfig
type AuthtypesAuthDomainConfig struct {
	AuthtypesGoogleConfig *AuthtypesGoogleConfig
	AuthtypesOIDCConfig *AuthtypesOIDCConfig
	AuthtypesSamlConfig *AuthtypesSamlConfig
}

// AuthtypesGoogleConfigAsAuthtypesAuthDomainConfig is a convenience function that returns AuthtypesGoogleConfig wrapped in AuthtypesAuthDomainConfig
func AuthtypesGoogleConfigAsAuthtypesAuthDomainConfig(v *AuthtypesGoogleConfig) AuthtypesAuthDomainConfig {
	return AuthtypesAuthDomainConfig{
		AuthtypesGoogleConfig: v,
	}
}

// AuthtypesOIDCConfigAsAuthtypesAuthDomainConfig is a convenience function that returns AuthtypesOIDCConfig wrapped in AuthtypesAuthDomainConfig
func AuthtypesOIDCConfigAsAuthtypesAuthDomainConfig(v *AuthtypesOIDCConfig) AuthtypesAuthDomainConfig {
	return AuthtypesAuthDomainConfig{
		AuthtypesOIDCConfig: v,
	}
}

// AuthtypesSamlConfigAsAuthtypesAuthDomainConfig is a convenience function that returns AuthtypesSamlConfig wrapped in AuthtypesAuthDomainConfig
func AuthtypesSamlConfigAsAuthtypesAuthDomainConfig(v *AuthtypesSamlConfig) AuthtypesAuthDomainConfig {
	return AuthtypesAuthDomainConfig{
		AuthtypesSamlConfig: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *AuthtypesAuthDomainConfig) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into AuthtypesGoogleConfig
	err = newStrictDecoder(data).Decode(&dst.AuthtypesGoogleConfig)
	if err == nil {
		jsonAuthtypesGoogleConfig, _ := json.Marshal(dst.AuthtypesGoogleConfig)
		if string(jsonAuthtypesGoogleConfig) == "{}" { // empty struct
			dst.AuthtypesGoogleConfig = nil
		} else {
			if err = validator.Validate(dst.AuthtypesGoogleConfig); err != nil {
				dst.AuthtypesGoogleConfig = nil
			} else {
				match++
			}
		}
	} else {
		dst.AuthtypesGoogleConfig = nil
	}

	// try to unmarshal data into AuthtypesOIDCConfig
	err = newStrictDecoder(data).Decode(&dst.AuthtypesOIDCConfig)
	if err == nil {
		jsonAuthtypesOIDCConfig, _ := json.Marshal(dst.AuthtypesOIDCConfig)
		if string(jsonAuthtypesOIDCConfig) == "{}" { // empty struct
			dst.AuthtypesOIDCConfig = nil
		} else {
			if err = validator.Validate(dst.AuthtypesOIDCConfig); err != nil {
				dst.AuthtypesOIDCConfig = nil
			} else {
				match++
			}
		}
	} else {
		dst.AuthtypesOIDCConfig = nil
	}

	// try to unmarshal data into AuthtypesSamlConfig
	err = newStrictDecoder(data).Decode(&dst.AuthtypesSamlConfig)
	if err == nil {
		jsonAuthtypesSamlConfig, _ := json.Marshal(dst.AuthtypesSamlConfig)
		if string(jsonAuthtypesSamlConfig) == "{}" { // empty struct
			dst.AuthtypesSamlConfig = nil
		} else {
			if err = validator.Validate(dst.AuthtypesSamlConfig); err != nil {
				dst.AuthtypesSamlConfig = nil
			} else {
				match++
			}
		}
	} else {
		dst.AuthtypesSamlConfig = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.AuthtypesGoogleConfig = nil
		dst.AuthtypesOIDCConfig = nil
		dst.AuthtypesSamlConfig = nil

		return fmt.Errorf("data matches more than one schema in oneOf(AuthtypesAuthDomainConfig)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(AuthtypesAuthDomainConfig)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src AuthtypesAuthDomainConfig) MarshalJSON() ([]byte, error) {
	if src.AuthtypesGoogleConfig != nil {
		return json.Marshal(&src.AuthtypesGoogleConfig)
	}

	if src.AuthtypesOIDCConfig != nil {
		return json.Marshal(&src.AuthtypesOIDCConfig)
	}

	if src.AuthtypesSamlConfig != nil {
		return json.Marshal(&src.AuthtypesSamlConfig)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *AuthtypesAuthDomainConfig) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.AuthtypesGoogleConfig != nil {
		return obj.AuthtypesGoogleConfig
	}

	if obj.AuthtypesOIDCConfig != nil {
		return obj.AuthtypesOIDCConfig
	}

	if obj.AuthtypesSamlConfig != nil {
		return obj.AuthtypesSamlConfig
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj AuthtypesAuthDomainConfig) GetActualInstanceValue() (interface{}) {
	if obj.AuthtypesGoogleConfig != nil {
		return *obj.AuthtypesGoogleConfig
	}

	if obj.AuthtypesOIDCConfig != nil {
		return *obj.AuthtypesOIDCConfig
	}

	if obj.AuthtypesSamlConfig != nil {
		return *obj.AuthtypesSamlConfig
	}

	// all schemas are nil
	return nil
}

type NullableAuthtypesAuthDomainConfig struct {
	value *AuthtypesAuthDomainConfig
	isSet bool
}

func (v NullableAuthtypesAuthDomainConfig) Get() *AuthtypesAuthDomainConfig {
	return v.value
}

func (v *NullableAuthtypesAuthDomainConfig) Set(val *AuthtypesAuthDomainConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthtypesAuthDomainConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthtypesAuthDomainConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthtypesAuthDomainConfig(val *AuthtypesAuthDomainConfig) *NullableAuthtypesAuthDomainConfig {
	return &NullableAuthtypesAuthDomainConfig{value: val, isSet: true}
}

func (v NullableAuthtypesAuthDomainConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthtypesAuthDomainConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


