/*
SigNoz

OpenTelemetry-Native Logs, Metrics and Traces in a single pane

API version: 
Contact: support@signoz.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package signozclient

import (
	"encoding/json"
)

// checks if the Querybuildertypesv5Having type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Querybuildertypesv5Having{}

// Querybuildertypesv5Having struct for Querybuildertypesv5Having
type Querybuildertypesv5Having struct {
	Expression *string `json:"expression,omitempty"`
}

// NewQuerybuildertypesv5Having instantiates a new Querybuildertypesv5Having object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuerybuildertypesv5Having() *Querybuildertypesv5Having {
	this := Querybuildertypesv5Having{}
	return &this
}

// NewQuerybuildertypesv5HavingWithDefaults instantiates a new Querybuildertypesv5Having object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuerybuildertypesv5HavingWithDefaults() *Querybuildertypesv5Having {
	this := Querybuildertypesv5Having{}
	return &this
}

// GetExpression returns the Expression field value if set, zero value otherwise.
func (o *Querybuildertypesv5Having) GetExpression() string {
	if o == nil || IsNil(o.Expression) {
		var ret string
		return ret
	}
	return *o.Expression
}

// GetExpressionOk returns a tuple with the Expression field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Querybuildertypesv5Having) GetExpressionOk() (*string, bool) {
	if o == nil || IsNil(o.Expression) {
		return nil, false
	}
	return o.Expression, true
}

// HasExpression returns a boolean if a field has been set.
func (o *Querybuildertypesv5Having) HasExpression() bool {
	if o != nil && !IsNil(o.Expression) {
		return true
	}

	return false
}

// SetExpression gets a reference to the given string and assigns it to the Expression field.
func (o *Querybuildertypesv5Having) SetExpression(v string) {
	o.Expression = &v
}

func (o Querybuildertypesv5Having) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Querybuildertypesv5Having) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Expression) {
		toSerialize["expression"] = o.Expression
	}
	return toSerialize, nil
}

type NullableQuerybuildertypesv5Having struct {
	value *Querybuildertypesv5Having
	isSet bool
}

func (v NullableQuerybuildertypesv5Having) Get() *Querybuildertypesv5Having {
	return v.value
}

func (v *NullableQuerybuildertypesv5Having) Set(val *Querybuildertypesv5Having) {
	v.value = val
	v.isSet = true
}

func (v NullableQuerybuildertypesv5Having) IsSet() bool {
	return v.isSet
}

func (v *NullableQuerybuildertypesv5Having) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuerybuildertypesv5Having(val *Querybuildertypesv5Having) *NullableQuerybuildertypesv5Having {
	return &NullableQuerybuildertypesv5Having{value: val, isSet: true}
}

func (v NullableQuerybuildertypesv5Having) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuerybuildertypesv5Having) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


