/*
SigNoz

OpenTelemetry-Native Logs, Metrics and Traces in a single pane

API version: 
Contact: support@signoz.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package signozclient

import (
	"encoding/json"
)

// checks if the ConfigMSTeamsConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigMSTeamsConfig{}

// ConfigMSTeamsConfig struct for ConfigMSTeamsConfig
type ConfigMSTeamsConfig struct {
	HttpConfig *ConfigHTTPClientConfig `json:"http_config,omitempty"`
	SendResolved *bool `json:"send_resolved,omitempty"`
	Summary *string `json:"summary,omitempty"`
	Text *string `json:"text,omitempty"`
	Title *string `json:"title,omitempty"`
	WebhookUrl map[string]interface{} `json:"webhook_url,omitempty"`
	WebhookUrlFile *string `json:"webhook_url_file,omitempty"`
}

// NewConfigMSTeamsConfig instantiates a new ConfigMSTeamsConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigMSTeamsConfig() *ConfigMSTeamsConfig {
	this := ConfigMSTeamsConfig{}
	return &this
}

// NewConfigMSTeamsConfigWithDefaults instantiates a new ConfigMSTeamsConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigMSTeamsConfigWithDefaults() *ConfigMSTeamsConfig {
	this := ConfigMSTeamsConfig{}
	return &this
}

// GetHttpConfig returns the HttpConfig field value if set, zero value otherwise.
func (o *ConfigMSTeamsConfig) GetHttpConfig() ConfigHTTPClientConfig {
	if o == nil || IsNil(o.HttpConfig) {
		var ret ConfigHTTPClientConfig
		return ret
	}
	return *o.HttpConfig
}

// GetHttpConfigOk returns a tuple with the HttpConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigMSTeamsConfig) GetHttpConfigOk() (*ConfigHTTPClientConfig, bool) {
	if o == nil || IsNil(o.HttpConfig) {
		return nil, false
	}
	return o.HttpConfig, true
}

// HasHttpConfig returns a boolean if a field has been set.
func (o *ConfigMSTeamsConfig) HasHttpConfig() bool {
	if o != nil && !IsNil(o.HttpConfig) {
		return true
	}

	return false
}

// SetHttpConfig gets a reference to the given ConfigHTTPClientConfig and assigns it to the HttpConfig field.
func (o *ConfigMSTeamsConfig) SetHttpConfig(v ConfigHTTPClientConfig) {
	o.HttpConfig = &v
}

// GetSendResolved returns the SendResolved field value if set, zero value otherwise.
func (o *ConfigMSTeamsConfig) GetSendResolved() bool {
	if o == nil || IsNil(o.SendResolved) {
		var ret bool
		return ret
	}
	return *o.SendResolved
}

// GetSendResolvedOk returns a tuple with the SendResolved field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigMSTeamsConfig) GetSendResolvedOk() (*bool, bool) {
	if o == nil || IsNil(o.SendResolved) {
		return nil, false
	}
	return o.SendResolved, true
}

// HasSendResolved returns a boolean if a field has been set.
func (o *ConfigMSTeamsConfig) HasSendResolved() bool {
	if o != nil && !IsNil(o.SendResolved) {
		return true
	}

	return false
}

// SetSendResolved gets a reference to the given bool and assigns it to the SendResolved field.
func (o *ConfigMSTeamsConfig) SetSendResolved(v bool) {
	o.SendResolved = &v
}

// GetSummary returns the Summary field value if set, zero value otherwise.
func (o *ConfigMSTeamsConfig) GetSummary() string {
	if o == nil || IsNil(o.Summary) {
		var ret string
		return ret
	}
	return *o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigMSTeamsConfig) GetSummaryOk() (*string, bool) {
	if o == nil || IsNil(o.Summary) {
		return nil, false
	}
	return o.Summary, true
}

// HasSummary returns a boolean if a field has been set.
func (o *ConfigMSTeamsConfig) HasSummary() bool {
	if o != nil && !IsNil(o.Summary) {
		return true
	}

	return false
}

// SetSummary gets a reference to the given string and assigns it to the Summary field.
func (o *ConfigMSTeamsConfig) SetSummary(v string) {
	o.Summary = &v
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *ConfigMSTeamsConfig) GetText() string {
	if o == nil || IsNil(o.Text) {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigMSTeamsConfig) GetTextOk() (*string, bool) {
	if o == nil || IsNil(o.Text) {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *ConfigMSTeamsConfig) HasText() bool {
	if o != nil && !IsNil(o.Text) {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *ConfigMSTeamsConfig) SetText(v string) {
	o.Text = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *ConfigMSTeamsConfig) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigMSTeamsConfig) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *ConfigMSTeamsConfig) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *ConfigMSTeamsConfig) SetTitle(v string) {
	o.Title = &v
}

// GetWebhookUrl returns the WebhookUrl field value if set, zero value otherwise.
func (o *ConfigMSTeamsConfig) GetWebhookUrl() map[string]interface{} {
	if o == nil || IsNil(o.WebhookUrl) {
		var ret map[string]interface{}
		return ret
	}
	return o.WebhookUrl
}

// GetWebhookUrlOk returns a tuple with the WebhookUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigMSTeamsConfig) GetWebhookUrlOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.WebhookUrl) {
		return map[string]interface{}{}, false
	}
	return o.WebhookUrl, true
}

// HasWebhookUrl returns a boolean if a field has been set.
func (o *ConfigMSTeamsConfig) HasWebhookUrl() bool {
	if o != nil && !IsNil(o.WebhookUrl) {
		return true
	}

	return false
}

// SetWebhookUrl gets a reference to the given map[string]interface{} and assigns it to the WebhookUrl field.
func (o *ConfigMSTeamsConfig) SetWebhookUrl(v map[string]interface{}) {
	o.WebhookUrl = v
}

// GetWebhookUrlFile returns the WebhookUrlFile field value if set, zero value otherwise.
func (o *ConfigMSTeamsConfig) GetWebhookUrlFile() string {
	if o == nil || IsNil(o.WebhookUrlFile) {
		var ret string
		return ret
	}
	return *o.WebhookUrlFile
}

// GetWebhookUrlFileOk returns a tuple with the WebhookUrlFile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigMSTeamsConfig) GetWebhookUrlFileOk() (*string, bool) {
	if o == nil || IsNil(o.WebhookUrlFile) {
		return nil, false
	}
	return o.WebhookUrlFile, true
}

// HasWebhookUrlFile returns a boolean if a field has been set.
func (o *ConfigMSTeamsConfig) HasWebhookUrlFile() bool {
	if o != nil && !IsNil(o.WebhookUrlFile) {
		return true
	}

	return false
}

// SetWebhookUrlFile gets a reference to the given string and assigns it to the WebhookUrlFile field.
func (o *ConfigMSTeamsConfig) SetWebhookUrlFile(v string) {
	o.WebhookUrlFile = &v
}

func (o ConfigMSTeamsConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigMSTeamsConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.HttpConfig) {
		toSerialize["http_config"] = o.HttpConfig
	}
	if !IsNil(o.SendResolved) {
		toSerialize["send_resolved"] = o.SendResolved
	}
	if !IsNil(o.Summary) {
		toSerialize["summary"] = o.Summary
	}
	if !IsNil(o.Text) {
		toSerialize["text"] = o.Text
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.WebhookUrl) {
		toSerialize["webhook_url"] = o.WebhookUrl
	}
	if !IsNil(o.WebhookUrlFile) {
		toSerialize["webhook_url_file"] = o.WebhookUrlFile
	}
	return toSerialize, nil
}

type NullableConfigMSTeamsConfig struct {
	value *ConfigMSTeamsConfig
	isSet bool
}

func (v NullableConfigMSTeamsConfig) Get() *ConfigMSTeamsConfig {
	return v.value
}

func (v *NullableConfigMSTeamsConfig) Set(val *ConfigMSTeamsConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigMSTeamsConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigMSTeamsConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigMSTeamsConfig(val *ConfigMSTeamsConfig) *NullableConfigMSTeamsConfig {
	return &NullableConfigMSTeamsConfig{value: val, isSet: true}
}

func (v NullableConfigMSTeamsConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigMSTeamsConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


