/*
SigNoz

OpenTelemetry-Native Logs, Metrics and Traces in a single pane

API version: 
Contact: support@signoz.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package signozclient

import (
	"encoding/json"
)

// checks if the CloudintegrationtypesAWSServiceMetricsConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CloudintegrationtypesAWSServiceMetricsConfig{}

// CloudintegrationtypesAWSServiceMetricsConfig struct for CloudintegrationtypesAWSServiceMetricsConfig
type CloudintegrationtypesAWSServiceMetricsConfig struct {
	Enabled *bool `json:"enabled,omitempty"`
}

// NewCloudintegrationtypesAWSServiceMetricsConfig instantiates a new CloudintegrationtypesAWSServiceMetricsConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCloudintegrationtypesAWSServiceMetricsConfig() *CloudintegrationtypesAWSServiceMetricsConfig {
	this := CloudintegrationtypesAWSServiceMetricsConfig{}
	return &this
}

// NewCloudintegrationtypesAWSServiceMetricsConfigWithDefaults instantiates a new CloudintegrationtypesAWSServiceMetricsConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCloudintegrationtypesAWSServiceMetricsConfigWithDefaults() *CloudintegrationtypesAWSServiceMetricsConfig {
	this := CloudintegrationtypesAWSServiceMetricsConfig{}
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *CloudintegrationtypesAWSServiceMetricsConfig) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudintegrationtypesAWSServiceMetricsConfig) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *CloudintegrationtypesAWSServiceMetricsConfig) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *CloudintegrationtypesAWSServiceMetricsConfig) SetEnabled(v bool) {
	o.Enabled = &v
}

func (o CloudintegrationtypesAWSServiceMetricsConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CloudintegrationtypesAWSServiceMetricsConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	return toSerialize, nil
}

type NullableCloudintegrationtypesAWSServiceMetricsConfig struct {
	value *CloudintegrationtypesAWSServiceMetricsConfig
	isSet bool
}

func (v NullableCloudintegrationtypesAWSServiceMetricsConfig) Get() *CloudintegrationtypesAWSServiceMetricsConfig {
	return v.value
}

func (v *NullableCloudintegrationtypesAWSServiceMetricsConfig) Set(val *CloudintegrationtypesAWSServiceMetricsConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableCloudintegrationtypesAWSServiceMetricsConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableCloudintegrationtypesAWSServiceMetricsConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCloudintegrationtypesAWSServiceMetricsConfig(val *CloudintegrationtypesAWSServiceMetricsConfig) *NullableCloudintegrationtypesAWSServiceMetricsConfig {
	return &NullableCloudintegrationtypesAWSServiceMetricsConfig{value: val, isSet: true}
}

func (v NullableCloudintegrationtypesAWSServiceMetricsConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCloudintegrationtypesAWSServiceMetricsConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


