/*
SigNoz

OpenTelemetry-Native Logs, Metrics and Traces in a single pane

API version: 
Contact: support@signoz.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package signozclient

import (
	"encoding/json"
)

// checks if the AuthtypesGoogleConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthtypesGoogleConfig{}

// AuthtypesGoogleConfig struct for AuthtypesGoogleConfig
type AuthtypesGoogleConfig struct {
	AllowedGroups []string `json:"allowedGroups,omitempty"`
	ClientId *string `json:"clientId,omitempty"`
	ClientSecret *string `json:"clientSecret,omitempty"`
	DomainToAdminEmail *map[string]string `json:"domainToAdminEmail,omitempty"`
	FetchGroups *bool `json:"fetchGroups,omitempty"`
	FetchTransitiveGroupMembership *bool `json:"fetchTransitiveGroupMembership,omitempty"`
	InsecureSkipEmailVerified *bool `json:"insecureSkipEmailVerified,omitempty"`
	RedirectURI *string `json:"redirectURI,omitempty"`
	ServiceAccountJson *string `json:"serviceAccountJson,omitempty"`
}

// NewAuthtypesGoogleConfig instantiates a new AuthtypesGoogleConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthtypesGoogleConfig() *AuthtypesGoogleConfig {
	this := AuthtypesGoogleConfig{}
	return &this
}

// NewAuthtypesGoogleConfigWithDefaults instantiates a new AuthtypesGoogleConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthtypesGoogleConfigWithDefaults() *AuthtypesGoogleConfig {
	this := AuthtypesGoogleConfig{}
	return &this
}

// GetAllowedGroups returns the AllowedGroups field value if set, zero value otherwise.
func (o *AuthtypesGoogleConfig) GetAllowedGroups() []string {
	if o == nil || IsNil(o.AllowedGroups) {
		var ret []string
		return ret
	}
	return o.AllowedGroups
}

// GetAllowedGroupsOk returns a tuple with the AllowedGroups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthtypesGoogleConfig) GetAllowedGroupsOk() ([]string, bool) {
	if o == nil || IsNil(o.AllowedGroups) {
		return nil, false
	}
	return o.AllowedGroups, true
}

// HasAllowedGroups returns a boolean if a field has been set.
func (o *AuthtypesGoogleConfig) HasAllowedGroups() bool {
	if o != nil && !IsNil(o.AllowedGroups) {
		return true
	}

	return false
}

// SetAllowedGroups gets a reference to the given []string and assigns it to the AllowedGroups field.
func (o *AuthtypesGoogleConfig) SetAllowedGroups(v []string) {
	o.AllowedGroups = v
}

// GetClientId returns the ClientId field value if set, zero value otherwise.
func (o *AuthtypesGoogleConfig) GetClientId() string {
	if o == nil || IsNil(o.ClientId) {
		var ret string
		return ret
	}
	return *o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthtypesGoogleConfig) GetClientIdOk() (*string, bool) {
	if o == nil || IsNil(o.ClientId) {
		return nil, false
	}
	return o.ClientId, true
}

// HasClientId returns a boolean if a field has been set.
func (o *AuthtypesGoogleConfig) HasClientId() bool {
	if o != nil && !IsNil(o.ClientId) {
		return true
	}

	return false
}

// SetClientId gets a reference to the given string and assigns it to the ClientId field.
func (o *AuthtypesGoogleConfig) SetClientId(v string) {
	o.ClientId = &v
}

// GetClientSecret returns the ClientSecret field value if set, zero value otherwise.
func (o *AuthtypesGoogleConfig) GetClientSecret() string {
	if o == nil || IsNil(o.ClientSecret) {
		var ret string
		return ret
	}
	return *o.ClientSecret
}

// GetClientSecretOk returns a tuple with the ClientSecret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthtypesGoogleConfig) GetClientSecretOk() (*string, bool) {
	if o == nil || IsNil(o.ClientSecret) {
		return nil, false
	}
	return o.ClientSecret, true
}

// HasClientSecret returns a boolean if a field has been set.
func (o *AuthtypesGoogleConfig) HasClientSecret() bool {
	if o != nil && !IsNil(o.ClientSecret) {
		return true
	}

	return false
}

// SetClientSecret gets a reference to the given string and assigns it to the ClientSecret field.
func (o *AuthtypesGoogleConfig) SetClientSecret(v string) {
	o.ClientSecret = &v
}

// GetDomainToAdminEmail returns the DomainToAdminEmail field value if set, zero value otherwise.
func (o *AuthtypesGoogleConfig) GetDomainToAdminEmail() map[string]string {
	if o == nil || IsNil(o.DomainToAdminEmail) {
		var ret map[string]string
		return ret
	}
	return *o.DomainToAdminEmail
}

// GetDomainToAdminEmailOk returns a tuple with the DomainToAdminEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthtypesGoogleConfig) GetDomainToAdminEmailOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.DomainToAdminEmail) {
		return nil, false
	}
	return o.DomainToAdminEmail, true
}

// HasDomainToAdminEmail returns a boolean if a field has been set.
func (o *AuthtypesGoogleConfig) HasDomainToAdminEmail() bool {
	if o != nil && !IsNil(o.DomainToAdminEmail) {
		return true
	}

	return false
}

// SetDomainToAdminEmail gets a reference to the given map[string]string and assigns it to the DomainToAdminEmail field.
func (o *AuthtypesGoogleConfig) SetDomainToAdminEmail(v map[string]string) {
	o.DomainToAdminEmail = &v
}

// GetFetchGroups returns the FetchGroups field value if set, zero value otherwise.
func (o *AuthtypesGoogleConfig) GetFetchGroups() bool {
	if o == nil || IsNil(o.FetchGroups) {
		var ret bool
		return ret
	}
	return *o.FetchGroups
}

// GetFetchGroupsOk returns a tuple with the FetchGroups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthtypesGoogleConfig) GetFetchGroupsOk() (*bool, bool) {
	if o == nil || IsNil(o.FetchGroups) {
		return nil, false
	}
	return o.FetchGroups, true
}

// HasFetchGroups returns a boolean if a field has been set.
func (o *AuthtypesGoogleConfig) HasFetchGroups() bool {
	if o != nil && !IsNil(o.FetchGroups) {
		return true
	}

	return false
}

// SetFetchGroups gets a reference to the given bool and assigns it to the FetchGroups field.
func (o *AuthtypesGoogleConfig) SetFetchGroups(v bool) {
	o.FetchGroups = &v
}

// GetFetchTransitiveGroupMembership returns the FetchTransitiveGroupMembership field value if set, zero value otherwise.
func (o *AuthtypesGoogleConfig) GetFetchTransitiveGroupMembership() bool {
	if o == nil || IsNil(o.FetchTransitiveGroupMembership) {
		var ret bool
		return ret
	}
	return *o.FetchTransitiveGroupMembership
}

// GetFetchTransitiveGroupMembershipOk returns a tuple with the FetchTransitiveGroupMembership field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthtypesGoogleConfig) GetFetchTransitiveGroupMembershipOk() (*bool, bool) {
	if o == nil || IsNil(o.FetchTransitiveGroupMembership) {
		return nil, false
	}
	return o.FetchTransitiveGroupMembership, true
}

// HasFetchTransitiveGroupMembership returns a boolean if a field has been set.
func (o *AuthtypesGoogleConfig) HasFetchTransitiveGroupMembership() bool {
	if o != nil && !IsNil(o.FetchTransitiveGroupMembership) {
		return true
	}

	return false
}

// SetFetchTransitiveGroupMembership gets a reference to the given bool and assigns it to the FetchTransitiveGroupMembership field.
func (o *AuthtypesGoogleConfig) SetFetchTransitiveGroupMembership(v bool) {
	o.FetchTransitiveGroupMembership = &v
}

// GetInsecureSkipEmailVerified returns the InsecureSkipEmailVerified field value if set, zero value otherwise.
func (o *AuthtypesGoogleConfig) GetInsecureSkipEmailVerified() bool {
	if o == nil || IsNil(o.InsecureSkipEmailVerified) {
		var ret bool
		return ret
	}
	return *o.InsecureSkipEmailVerified
}

// GetInsecureSkipEmailVerifiedOk returns a tuple with the InsecureSkipEmailVerified field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthtypesGoogleConfig) GetInsecureSkipEmailVerifiedOk() (*bool, bool) {
	if o == nil || IsNil(o.InsecureSkipEmailVerified) {
		return nil, false
	}
	return o.InsecureSkipEmailVerified, true
}

// HasInsecureSkipEmailVerified returns a boolean if a field has been set.
func (o *AuthtypesGoogleConfig) HasInsecureSkipEmailVerified() bool {
	if o != nil && !IsNil(o.InsecureSkipEmailVerified) {
		return true
	}

	return false
}

// SetInsecureSkipEmailVerified gets a reference to the given bool and assigns it to the InsecureSkipEmailVerified field.
func (o *AuthtypesGoogleConfig) SetInsecureSkipEmailVerified(v bool) {
	o.InsecureSkipEmailVerified = &v
}

// GetRedirectURI returns the RedirectURI field value if set, zero value otherwise.
func (o *AuthtypesGoogleConfig) GetRedirectURI() string {
	if o == nil || IsNil(o.RedirectURI) {
		var ret string
		return ret
	}
	return *o.RedirectURI
}

// GetRedirectURIOk returns a tuple with the RedirectURI field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthtypesGoogleConfig) GetRedirectURIOk() (*string, bool) {
	if o == nil || IsNil(o.RedirectURI) {
		return nil, false
	}
	return o.RedirectURI, true
}

// HasRedirectURI returns a boolean if a field has been set.
func (o *AuthtypesGoogleConfig) HasRedirectURI() bool {
	if o != nil && !IsNil(o.RedirectURI) {
		return true
	}

	return false
}

// SetRedirectURI gets a reference to the given string and assigns it to the RedirectURI field.
func (o *AuthtypesGoogleConfig) SetRedirectURI(v string) {
	o.RedirectURI = &v
}

// GetServiceAccountJson returns the ServiceAccountJson field value if set, zero value otherwise.
func (o *AuthtypesGoogleConfig) GetServiceAccountJson() string {
	if o == nil || IsNil(o.ServiceAccountJson) {
		var ret string
		return ret
	}
	return *o.ServiceAccountJson
}

// GetServiceAccountJsonOk returns a tuple with the ServiceAccountJson field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthtypesGoogleConfig) GetServiceAccountJsonOk() (*string, bool) {
	if o == nil || IsNil(o.ServiceAccountJson) {
		return nil, false
	}
	return o.ServiceAccountJson, true
}

// HasServiceAccountJson returns a boolean if a field has been set.
func (o *AuthtypesGoogleConfig) HasServiceAccountJson() bool {
	if o != nil && !IsNil(o.ServiceAccountJson) {
		return true
	}

	return false
}

// SetServiceAccountJson gets a reference to the given string and assigns it to the ServiceAccountJson field.
func (o *AuthtypesGoogleConfig) SetServiceAccountJson(v string) {
	o.ServiceAccountJson = &v
}

func (o AuthtypesGoogleConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthtypesGoogleConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AllowedGroups) {
		toSerialize["allowedGroups"] = o.AllowedGroups
	}
	if !IsNil(o.ClientId) {
		toSerialize["clientId"] = o.ClientId
	}
	if !IsNil(o.ClientSecret) {
		toSerialize["clientSecret"] = o.ClientSecret
	}
	if !IsNil(o.DomainToAdminEmail) {
		toSerialize["domainToAdminEmail"] = o.DomainToAdminEmail
	}
	if !IsNil(o.FetchGroups) {
		toSerialize["fetchGroups"] = o.FetchGroups
	}
	if !IsNil(o.FetchTransitiveGroupMembership) {
		toSerialize["fetchTransitiveGroupMembership"] = o.FetchTransitiveGroupMembership
	}
	if !IsNil(o.InsecureSkipEmailVerified) {
		toSerialize["insecureSkipEmailVerified"] = o.InsecureSkipEmailVerified
	}
	if !IsNil(o.RedirectURI) {
		toSerialize["redirectURI"] = o.RedirectURI
	}
	if !IsNil(o.ServiceAccountJson) {
		toSerialize["serviceAccountJson"] = o.ServiceAccountJson
	}
	return toSerialize, nil
}

type NullableAuthtypesGoogleConfig struct {
	value *AuthtypesGoogleConfig
	isSet bool
}

func (v NullableAuthtypesGoogleConfig) Get() *AuthtypesGoogleConfig {
	return v.value
}

func (v *NullableAuthtypesGoogleConfig) Set(val *AuthtypesGoogleConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthtypesGoogleConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthtypesGoogleConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthtypesGoogleConfig(val *AuthtypesGoogleConfig) *NullableAuthtypesGoogleConfig {
	return &NullableAuthtypesGoogleConfig{value: val, isSet: true}
}

func (v NullableAuthtypesGoogleConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthtypesGoogleConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


