/*
SigNoz

OpenTelemetry-Native Logs, Metrics and Traces in a single pane

API version: 
Contact: support@signoz.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package signozclient

import (
	"encoding/json"
)

// checks if the Querybuildertypesv5AggregationBucket type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Querybuildertypesv5AggregationBucket{}

// Querybuildertypesv5AggregationBucket struct for Querybuildertypesv5AggregationBucket
type Querybuildertypesv5AggregationBucket struct {
	Alias *string `json:"alias,omitempty"`
	AnomalyScores []Querybuildertypesv5TimeSeries `json:"anomalyScores,omitempty"`
	Index *int32 `json:"index,omitempty"`
	LowerBoundSeries []Querybuildertypesv5TimeSeries `json:"lowerBoundSeries,omitempty"`
	Meta *Querybuildertypesv5AggregationBucketMeta `json:"meta,omitempty"`
	PredictedSeries []Querybuildertypesv5TimeSeries `json:"predictedSeries,omitempty"`
	Series []Querybuildertypesv5TimeSeries `json:"series,omitempty"`
	UpperBoundSeries []Querybuildertypesv5TimeSeries `json:"upperBoundSeries,omitempty"`
}

// NewQuerybuildertypesv5AggregationBucket instantiates a new Querybuildertypesv5AggregationBucket object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuerybuildertypesv5AggregationBucket() *Querybuildertypesv5AggregationBucket {
	this := Querybuildertypesv5AggregationBucket{}
	return &this
}

// NewQuerybuildertypesv5AggregationBucketWithDefaults instantiates a new Querybuildertypesv5AggregationBucket object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuerybuildertypesv5AggregationBucketWithDefaults() *Querybuildertypesv5AggregationBucket {
	this := Querybuildertypesv5AggregationBucket{}
	return &this
}

// GetAlias returns the Alias field value if set, zero value otherwise.
func (o *Querybuildertypesv5AggregationBucket) GetAlias() string {
	if o == nil || IsNil(o.Alias) {
		var ret string
		return ret
	}
	return *o.Alias
}

// GetAliasOk returns a tuple with the Alias field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Querybuildertypesv5AggregationBucket) GetAliasOk() (*string, bool) {
	if o == nil || IsNil(o.Alias) {
		return nil, false
	}
	return o.Alias, true
}

// HasAlias returns a boolean if a field has been set.
func (o *Querybuildertypesv5AggregationBucket) HasAlias() bool {
	if o != nil && !IsNil(o.Alias) {
		return true
	}

	return false
}

// SetAlias gets a reference to the given string and assigns it to the Alias field.
func (o *Querybuildertypesv5AggregationBucket) SetAlias(v string) {
	o.Alias = &v
}

// GetAnomalyScores returns the AnomalyScores field value if set, zero value otherwise.
func (o *Querybuildertypesv5AggregationBucket) GetAnomalyScores() []Querybuildertypesv5TimeSeries {
	if o == nil || IsNil(o.AnomalyScores) {
		var ret []Querybuildertypesv5TimeSeries
		return ret
	}
	return o.AnomalyScores
}

// GetAnomalyScoresOk returns a tuple with the AnomalyScores field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Querybuildertypesv5AggregationBucket) GetAnomalyScoresOk() ([]Querybuildertypesv5TimeSeries, bool) {
	if o == nil || IsNil(o.AnomalyScores) {
		return nil, false
	}
	return o.AnomalyScores, true
}

// HasAnomalyScores returns a boolean if a field has been set.
func (o *Querybuildertypesv5AggregationBucket) HasAnomalyScores() bool {
	if o != nil && !IsNil(o.AnomalyScores) {
		return true
	}

	return false
}

// SetAnomalyScores gets a reference to the given []Querybuildertypesv5TimeSeries and assigns it to the AnomalyScores field.
func (o *Querybuildertypesv5AggregationBucket) SetAnomalyScores(v []Querybuildertypesv5TimeSeries) {
	o.AnomalyScores = v
}

// GetIndex returns the Index field value if set, zero value otherwise.
func (o *Querybuildertypesv5AggregationBucket) GetIndex() int32 {
	if o == nil || IsNil(o.Index) {
		var ret int32
		return ret
	}
	return *o.Index
}

// GetIndexOk returns a tuple with the Index field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Querybuildertypesv5AggregationBucket) GetIndexOk() (*int32, bool) {
	if o == nil || IsNil(o.Index) {
		return nil, false
	}
	return o.Index, true
}

// HasIndex returns a boolean if a field has been set.
func (o *Querybuildertypesv5AggregationBucket) HasIndex() bool {
	if o != nil && !IsNil(o.Index) {
		return true
	}

	return false
}

// SetIndex gets a reference to the given int32 and assigns it to the Index field.
func (o *Querybuildertypesv5AggregationBucket) SetIndex(v int32) {
	o.Index = &v
}

// GetLowerBoundSeries returns the LowerBoundSeries field value if set, zero value otherwise.
func (o *Querybuildertypesv5AggregationBucket) GetLowerBoundSeries() []Querybuildertypesv5TimeSeries {
	if o == nil || IsNil(o.LowerBoundSeries) {
		var ret []Querybuildertypesv5TimeSeries
		return ret
	}
	return o.LowerBoundSeries
}

// GetLowerBoundSeriesOk returns a tuple with the LowerBoundSeries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Querybuildertypesv5AggregationBucket) GetLowerBoundSeriesOk() ([]Querybuildertypesv5TimeSeries, bool) {
	if o == nil || IsNil(o.LowerBoundSeries) {
		return nil, false
	}
	return o.LowerBoundSeries, true
}

// HasLowerBoundSeries returns a boolean if a field has been set.
func (o *Querybuildertypesv5AggregationBucket) HasLowerBoundSeries() bool {
	if o != nil && !IsNil(o.LowerBoundSeries) {
		return true
	}

	return false
}

// SetLowerBoundSeries gets a reference to the given []Querybuildertypesv5TimeSeries and assigns it to the LowerBoundSeries field.
func (o *Querybuildertypesv5AggregationBucket) SetLowerBoundSeries(v []Querybuildertypesv5TimeSeries) {
	o.LowerBoundSeries = v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *Querybuildertypesv5AggregationBucket) GetMeta() Querybuildertypesv5AggregationBucketMeta {
	if o == nil || IsNil(o.Meta) {
		var ret Querybuildertypesv5AggregationBucketMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Querybuildertypesv5AggregationBucket) GetMetaOk() (*Querybuildertypesv5AggregationBucketMeta, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *Querybuildertypesv5AggregationBucket) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given Querybuildertypesv5AggregationBucketMeta and assigns it to the Meta field.
func (o *Querybuildertypesv5AggregationBucket) SetMeta(v Querybuildertypesv5AggregationBucketMeta) {
	o.Meta = &v
}

// GetPredictedSeries returns the PredictedSeries field value if set, zero value otherwise.
func (o *Querybuildertypesv5AggregationBucket) GetPredictedSeries() []Querybuildertypesv5TimeSeries {
	if o == nil || IsNil(o.PredictedSeries) {
		var ret []Querybuildertypesv5TimeSeries
		return ret
	}
	return o.PredictedSeries
}

// GetPredictedSeriesOk returns a tuple with the PredictedSeries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Querybuildertypesv5AggregationBucket) GetPredictedSeriesOk() ([]Querybuildertypesv5TimeSeries, bool) {
	if o == nil || IsNil(o.PredictedSeries) {
		return nil, false
	}
	return o.PredictedSeries, true
}

// HasPredictedSeries returns a boolean if a field has been set.
func (o *Querybuildertypesv5AggregationBucket) HasPredictedSeries() bool {
	if o != nil && !IsNil(o.PredictedSeries) {
		return true
	}

	return false
}

// SetPredictedSeries gets a reference to the given []Querybuildertypesv5TimeSeries and assigns it to the PredictedSeries field.
func (o *Querybuildertypesv5AggregationBucket) SetPredictedSeries(v []Querybuildertypesv5TimeSeries) {
	o.PredictedSeries = v
}

// GetSeries returns the Series field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Querybuildertypesv5AggregationBucket) GetSeries() []Querybuildertypesv5TimeSeries {
	if o == nil {
		var ret []Querybuildertypesv5TimeSeries
		return ret
	}
	return o.Series
}

// GetSeriesOk returns a tuple with the Series field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Querybuildertypesv5AggregationBucket) GetSeriesOk() ([]Querybuildertypesv5TimeSeries, bool) {
	if o == nil || IsNil(o.Series) {
		return nil, false
	}
	return o.Series, true
}

// HasSeries returns a boolean if a field has been set.
func (o *Querybuildertypesv5AggregationBucket) HasSeries() bool {
	if o != nil && !IsNil(o.Series) {
		return true
	}

	return false
}

// SetSeries gets a reference to the given []Querybuildertypesv5TimeSeries and assigns it to the Series field.
func (o *Querybuildertypesv5AggregationBucket) SetSeries(v []Querybuildertypesv5TimeSeries) {
	o.Series = v
}

// GetUpperBoundSeries returns the UpperBoundSeries field value if set, zero value otherwise.
func (o *Querybuildertypesv5AggregationBucket) GetUpperBoundSeries() []Querybuildertypesv5TimeSeries {
	if o == nil || IsNil(o.UpperBoundSeries) {
		var ret []Querybuildertypesv5TimeSeries
		return ret
	}
	return o.UpperBoundSeries
}

// GetUpperBoundSeriesOk returns a tuple with the UpperBoundSeries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Querybuildertypesv5AggregationBucket) GetUpperBoundSeriesOk() ([]Querybuildertypesv5TimeSeries, bool) {
	if o == nil || IsNil(o.UpperBoundSeries) {
		return nil, false
	}
	return o.UpperBoundSeries, true
}

// HasUpperBoundSeries returns a boolean if a field has been set.
func (o *Querybuildertypesv5AggregationBucket) HasUpperBoundSeries() bool {
	if o != nil && !IsNil(o.UpperBoundSeries) {
		return true
	}

	return false
}

// SetUpperBoundSeries gets a reference to the given []Querybuildertypesv5TimeSeries and assigns it to the UpperBoundSeries field.
func (o *Querybuildertypesv5AggregationBucket) SetUpperBoundSeries(v []Querybuildertypesv5TimeSeries) {
	o.UpperBoundSeries = v
}

func (o Querybuildertypesv5AggregationBucket) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Querybuildertypesv5AggregationBucket) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Alias) {
		toSerialize["alias"] = o.Alias
	}
	if !IsNil(o.AnomalyScores) {
		toSerialize["anomalyScores"] = o.AnomalyScores
	}
	if !IsNil(o.Index) {
		toSerialize["index"] = o.Index
	}
	if !IsNil(o.LowerBoundSeries) {
		toSerialize["lowerBoundSeries"] = o.LowerBoundSeries
	}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	if !IsNil(o.PredictedSeries) {
		toSerialize["predictedSeries"] = o.PredictedSeries
	}
	if o.Series != nil {
		toSerialize["series"] = o.Series
	}
	if !IsNil(o.UpperBoundSeries) {
		toSerialize["upperBoundSeries"] = o.UpperBoundSeries
	}
	return toSerialize, nil
}

type NullableQuerybuildertypesv5AggregationBucket struct {
	value *Querybuildertypesv5AggregationBucket
	isSet bool
}

func (v NullableQuerybuildertypesv5AggregationBucket) Get() *Querybuildertypesv5AggregationBucket {
	return v.value
}

func (v *NullableQuerybuildertypesv5AggregationBucket) Set(val *Querybuildertypesv5AggregationBucket) {
	v.value = val
	v.isSet = true
}

func (v NullableQuerybuildertypesv5AggregationBucket) IsSet() bool {
	return v.isSet
}

func (v *NullableQuerybuildertypesv5AggregationBucket) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuerybuildertypesv5AggregationBucket(val *Querybuildertypesv5AggregationBucket) *NullableQuerybuildertypesv5AggregationBucket {
	return &NullableQuerybuildertypesv5AggregationBucket{value: val, isSet: true}
}

func (v NullableQuerybuildertypesv5AggregationBucket) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuerybuildertypesv5AggregationBucket) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


