/*
SigNoz

OpenTelemetry-Native Logs, Metrics and Traces in a single pane

API version: 
Contact: support@signoz.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package signozclient

import (
	"encoding/json"
)

// checks if the TypesPostableResetPassword type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TypesPostableResetPassword{}

// TypesPostableResetPassword struct for TypesPostableResetPassword
type TypesPostableResetPassword struct {
	Password *string `json:"password,omitempty"`
	Token *string `json:"token,omitempty"`
}

// NewTypesPostableResetPassword instantiates a new TypesPostableResetPassword object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTypesPostableResetPassword() *TypesPostableResetPassword {
	this := TypesPostableResetPassword{}
	return &this
}

// NewTypesPostableResetPasswordWithDefaults instantiates a new TypesPostableResetPassword object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTypesPostableResetPasswordWithDefaults() *TypesPostableResetPassword {
	this := TypesPostableResetPassword{}
	return &this
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *TypesPostableResetPassword) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypesPostableResetPassword) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *TypesPostableResetPassword) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *TypesPostableResetPassword) SetPassword(v string) {
	o.Password = &v
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *TypesPostableResetPassword) GetToken() string {
	if o == nil || IsNil(o.Token) {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypesPostableResetPassword) GetTokenOk() (*string, bool) {
	if o == nil || IsNil(o.Token) {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *TypesPostableResetPassword) HasToken() bool {
	if o != nil && !IsNil(o.Token) {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *TypesPostableResetPassword) SetToken(v string) {
	o.Token = &v
}

func (o TypesPostableResetPassword) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TypesPostableResetPassword) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	if !IsNil(o.Token) {
		toSerialize["token"] = o.Token
	}
	return toSerialize, nil
}

type NullableTypesPostableResetPassword struct {
	value *TypesPostableResetPassword
	isSet bool
}

func (v NullableTypesPostableResetPassword) Get() *TypesPostableResetPassword {
	return v.value
}

func (v *NullableTypesPostableResetPassword) Set(val *TypesPostableResetPassword) {
	v.value = val
	v.isSet = true
}

func (v NullableTypesPostableResetPassword) IsSet() bool {
	return v.isSet
}

func (v *NullableTypesPostableResetPassword) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTypesPostableResetPassword(val *TypesPostableResetPassword) *NullableTypesPostableResetPassword {
	return &NullableTypesPostableResetPassword{value: val, isSet: true}
}

func (v NullableTypesPostableResetPassword) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTypesPostableResetPassword) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


