/*
SigNoz

OpenTelemetry-Native Logs, Metrics and Traces in a single pane

API version: 
Contact: support@signoz.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package signozclient

import (
	"encoding/json"
)

// checks if the CloudintegrationtypesAWSTelemetryCollectionStrategy type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CloudintegrationtypesAWSTelemetryCollectionStrategy{}

// CloudintegrationtypesAWSTelemetryCollectionStrategy struct for CloudintegrationtypesAWSTelemetryCollectionStrategy
type CloudintegrationtypesAWSTelemetryCollectionStrategy struct {
	Logs *CloudintegrationtypesAWSLogsCollectionStrategy `json:"logs,omitempty"`
	Metrics *CloudintegrationtypesAWSMetricsCollectionStrategy `json:"metrics,omitempty"`
	S3Buckets *map[string][]string `json:"s3Buckets,omitempty"`
}

// NewCloudintegrationtypesAWSTelemetryCollectionStrategy instantiates a new CloudintegrationtypesAWSTelemetryCollectionStrategy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCloudintegrationtypesAWSTelemetryCollectionStrategy() *CloudintegrationtypesAWSTelemetryCollectionStrategy {
	this := CloudintegrationtypesAWSTelemetryCollectionStrategy{}
	return &this
}

// NewCloudintegrationtypesAWSTelemetryCollectionStrategyWithDefaults instantiates a new CloudintegrationtypesAWSTelemetryCollectionStrategy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCloudintegrationtypesAWSTelemetryCollectionStrategyWithDefaults() *CloudintegrationtypesAWSTelemetryCollectionStrategy {
	this := CloudintegrationtypesAWSTelemetryCollectionStrategy{}
	return &this
}

// GetLogs returns the Logs field value if set, zero value otherwise.
func (o *CloudintegrationtypesAWSTelemetryCollectionStrategy) GetLogs() CloudintegrationtypesAWSLogsCollectionStrategy {
	if o == nil || IsNil(o.Logs) {
		var ret CloudintegrationtypesAWSLogsCollectionStrategy
		return ret
	}
	return *o.Logs
}

// GetLogsOk returns a tuple with the Logs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudintegrationtypesAWSTelemetryCollectionStrategy) GetLogsOk() (*CloudintegrationtypesAWSLogsCollectionStrategy, bool) {
	if o == nil || IsNil(o.Logs) {
		return nil, false
	}
	return o.Logs, true
}

// HasLogs returns a boolean if a field has been set.
func (o *CloudintegrationtypesAWSTelemetryCollectionStrategy) HasLogs() bool {
	if o != nil && !IsNil(o.Logs) {
		return true
	}

	return false
}

// SetLogs gets a reference to the given CloudintegrationtypesAWSLogsCollectionStrategy and assigns it to the Logs field.
func (o *CloudintegrationtypesAWSTelemetryCollectionStrategy) SetLogs(v CloudintegrationtypesAWSLogsCollectionStrategy) {
	o.Logs = &v
}

// GetMetrics returns the Metrics field value if set, zero value otherwise.
func (o *CloudintegrationtypesAWSTelemetryCollectionStrategy) GetMetrics() CloudintegrationtypesAWSMetricsCollectionStrategy {
	if o == nil || IsNil(o.Metrics) {
		var ret CloudintegrationtypesAWSMetricsCollectionStrategy
		return ret
	}
	return *o.Metrics
}

// GetMetricsOk returns a tuple with the Metrics field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudintegrationtypesAWSTelemetryCollectionStrategy) GetMetricsOk() (*CloudintegrationtypesAWSMetricsCollectionStrategy, bool) {
	if o == nil || IsNil(o.Metrics) {
		return nil, false
	}
	return o.Metrics, true
}

// HasMetrics returns a boolean if a field has been set.
func (o *CloudintegrationtypesAWSTelemetryCollectionStrategy) HasMetrics() bool {
	if o != nil && !IsNil(o.Metrics) {
		return true
	}

	return false
}

// SetMetrics gets a reference to the given CloudintegrationtypesAWSMetricsCollectionStrategy and assigns it to the Metrics field.
func (o *CloudintegrationtypesAWSTelemetryCollectionStrategy) SetMetrics(v CloudintegrationtypesAWSMetricsCollectionStrategy) {
	o.Metrics = &v
}

// GetS3Buckets returns the S3Buckets field value if set, zero value otherwise.
func (o *CloudintegrationtypesAWSTelemetryCollectionStrategy) GetS3Buckets() map[string][]string {
	if o == nil || IsNil(o.S3Buckets) {
		var ret map[string][]string
		return ret
	}
	return *o.S3Buckets
}

// GetS3BucketsOk returns a tuple with the S3Buckets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudintegrationtypesAWSTelemetryCollectionStrategy) GetS3BucketsOk() (*map[string][]string, bool) {
	if o == nil || IsNil(o.S3Buckets) {
		return nil, false
	}
	return o.S3Buckets, true
}

// HasS3Buckets returns a boolean if a field has been set.
func (o *CloudintegrationtypesAWSTelemetryCollectionStrategy) HasS3Buckets() bool {
	if o != nil && !IsNil(o.S3Buckets) {
		return true
	}

	return false
}

// SetS3Buckets gets a reference to the given map[string][]string and assigns it to the S3Buckets field.
func (o *CloudintegrationtypesAWSTelemetryCollectionStrategy) SetS3Buckets(v map[string][]string) {
	o.S3Buckets = &v
}

func (o CloudintegrationtypesAWSTelemetryCollectionStrategy) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CloudintegrationtypesAWSTelemetryCollectionStrategy) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Logs) {
		toSerialize["logs"] = o.Logs
	}
	if !IsNil(o.Metrics) {
		toSerialize["metrics"] = o.Metrics
	}
	if !IsNil(o.S3Buckets) {
		toSerialize["s3Buckets"] = o.S3Buckets
	}
	return toSerialize, nil
}

type NullableCloudintegrationtypesAWSTelemetryCollectionStrategy struct {
	value *CloudintegrationtypesAWSTelemetryCollectionStrategy
	isSet bool
}

func (v NullableCloudintegrationtypesAWSTelemetryCollectionStrategy) Get() *CloudintegrationtypesAWSTelemetryCollectionStrategy {
	return v.value
}

func (v *NullableCloudintegrationtypesAWSTelemetryCollectionStrategy) Set(val *CloudintegrationtypesAWSTelemetryCollectionStrategy) {
	v.value = val
	v.isSet = true
}

func (v NullableCloudintegrationtypesAWSTelemetryCollectionStrategy) IsSet() bool {
	return v.isSet
}

func (v *NullableCloudintegrationtypesAWSTelemetryCollectionStrategy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCloudintegrationtypesAWSTelemetryCollectionStrategy(val *CloudintegrationtypesAWSTelemetryCollectionStrategy) *NullableCloudintegrationtypesAWSTelemetryCollectionStrategy {
	return &NullableCloudintegrationtypesAWSTelemetryCollectionStrategy{value: val, isSet: true}
}

func (v NullableCloudintegrationtypesAWSTelemetryCollectionStrategy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCloudintegrationtypesAWSTelemetryCollectionStrategy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


