/*
SigNoz

OpenTelemetry-Native Logs, Metrics and Traces in a single pane

API version: 
Contact: support@signoz.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package signozclient

import (
	"encoding/json"
)

// checks if the Querybuildertypesv5CompositeQuery type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Querybuildertypesv5CompositeQuery{}

// Querybuildertypesv5CompositeQuery Composite query containing one or more query envelopes. Each query envelope specifies its type and corresponding spec.
type Querybuildertypesv5CompositeQuery struct {
	Queries []Querybuildertypesv5QueryEnvelope `json:"queries,omitempty"`
}

// NewQuerybuildertypesv5CompositeQuery instantiates a new Querybuildertypesv5CompositeQuery object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuerybuildertypesv5CompositeQuery() *Querybuildertypesv5CompositeQuery {
	this := Querybuildertypesv5CompositeQuery{}
	return &this
}

// NewQuerybuildertypesv5CompositeQueryWithDefaults instantiates a new Querybuildertypesv5CompositeQuery object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuerybuildertypesv5CompositeQueryWithDefaults() *Querybuildertypesv5CompositeQuery {
	this := Querybuildertypesv5CompositeQuery{}
	return &this
}

// GetQueries returns the Queries field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Querybuildertypesv5CompositeQuery) GetQueries() []Querybuildertypesv5QueryEnvelope {
	if o == nil {
		var ret []Querybuildertypesv5QueryEnvelope
		return ret
	}
	return o.Queries
}

// GetQueriesOk returns a tuple with the Queries field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Querybuildertypesv5CompositeQuery) GetQueriesOk() ([]Querybuildertypesv5QueryEnvelope, bool) {
	if o == nil || IsNil(o.Queries) {
		return nil, false
	}
	return o.Queries, true
}

// HasQueries returns a boolean if a field has been set.
func (o *Querybuildertypesv5CompositeQuery) HasQueries() bool {
	if o != nil && !IsNil(o.Queries) {
		return true
	}

	return false
}

// SetQueries gets a reference to the given []Querybuildertypesv5QueryEnvelope and assigns it to the Queries field.
func (o *Querybuildertypesv5CompositeQuery) SetQueries(v []Querybuildertypesv5QueryEnvelope) {
	o.Queries = v
}

func (o Querybuildertypesv5CompositeQuery) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Querybuildertypesv5CompositeQuery) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Queries != nil {
		toSerialize["queries"] = o.Queries
	}
	return toSerialize, nil
}

type NullableQuerybuildertypesv5CompositeQuery struct {
	value *Querybuildertypesv5CompositeQuery
	isSet bool
}

func (v NullableQuerybuildertypesv5CompositeQuery) Get() *Querybuildertypesv5CompositeQuery {
	return v.value
}

func (v *NullableQuerybuildertypesv5CompositeQuery) Set(val *Querybuildertypesv5CompositeQuery) {
	v.value = val
	v.isSet = true
}

func (v NullableQuerybuildertypesv5CompositeQuery) IsSet() bool {
	return v.isSet
}

func (v *NullableQuerybuildertypesv5CompositeQuery) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuerybuildertypesv5CompositeQuery(val *Querybuildertypesv5CompositeQuery) *NullableQuerybuildertypesv5CompositeQuery {
	return &NullableQuerybuildertypesv5CompositeQuery{value: val, isSet: true}
}

func (v NullableQuerybuildertypesv5CompositeQuery) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuerybuildertypesv5CompositeQuery) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


