/*
SigNoz

OpenTelemetry-Native Logs, Metrics and Traces in a single pane

API version: 
Contact: support@signoz.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package signozclient

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the LlmpricingruletypesLLMPricingRule type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LlmpricingruletypesLLMPricingRule{}

// LlmpricingruletypesLLMPricingRule struct for LlmpricingruletypesLLMPricingRule
type LlmpricingruletypesLLMPricingRule struct {
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	CreatedBy *string `json:"createdBy,omitempty"`
	Enabled bool `json:"enabled"`
	Id string `json:"id"`
	IsOverride bool `json:"isOverride"`
	ModelName string `json:"modelName"`
	ModelPattern []string `json:"modelPattern"`
	OrgId string `json:"orgId"`
	Pricing LlmpricingruletypesLLMRulePricing `json:"pricing"`
	Provider string `json:"provider"`
	SourceId *string `json:"sourceId,omitempty"`
	SyncedAt NullableTime `json:"syncedAt,omitempty"`
	Unit LlmpricingruletypesLLMPricingRuleUnit `json:"unit"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	UpdatedBy *string `json:"updatedBy,omitempty"`
}

type _LlmpricingruletypesLLMPricingRule LlmpricingruletypesLLMPricingRule

// NewLlmpricingruletypesLLMPricingRule instantiates a new LlmpricingruletypesLLMPricingRule object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLlmpricingruletypesLLMPricingRule(enabled bool, id string, isOverride bool, modelName string, modelPattern []string, orgId string, pricing LlmpricingruletypesLLMRulePricing, provider string, unit LlmpricingruletypesLLMPricingRuleUnit) *LlmpricingruletypesLLMPricingRule {
	this := LlmpricingruletypesLLMPricingRule{}
	this.Enabled = enabled
	this.Id = id
	this.IsOverride = isOverride
	this.ModelName = modelName
	this.ModelPattern = modelPattern
	this.OrgId = orgId
	this.Pricing = pricing
	this.Provider = provider
	this.Unit = unit
	return &this
}

// NewLlmpricingruletypesLLMPricingRuleWithDefaults instantiates a new LlmpricingruletypesLLMPricingRule object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLlmpricingruletypesLLMPricingRuleWithDefaults() *LlmpricingruletypesLLMPricingRule {
	this := LlmpricingruletypesLLMPricingRule{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *LlmpricingruletypesLLMPricingRule) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LlmpricingruletypesLLMPricingRule) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *LlmpricingruletypesLLMPricingRule) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *LlmpricingruletypesLLMPricingRule) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetCreatedBy returns the CreatedBy field value if set, zero value otherwise.
func (o *LlmpricingruletypesLLMPricingRule) GetCreatedBy() string {
	if o == nil || IsNil(o.CreatedBy) {
		var ret string
		return ret
	}
	return *o.CreatedBy
}

// GetCreatedByOk returns a tuple with the CreatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LlmpricingruletypesLLMPricingRule) GetCreatedByOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedBy) {
		return nil, false
	}
	return o.CreatedBy, true
}

// HasCreatedBy returns a boolean if a field has been set.
func (o *LlmpricingruletypesLLMPricingRule) HasCreatedBy() bool {
	if o != nil && !IsNil(o.CreatedBy) {
		return true
	}

	return false
}

// SetCreatedBy gets a reference to the given string and assigns it to the CreatedBy field.
func (o *LlmpricingruletypesLLMPricingRule) SetCreatedBy(v string) {
	o.CreatedBy = &v
}

// GetEnabled returns the Enabled field value
func (o *LlmpricingruletypesLLMPricingRule) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *LlmpricingruletypesLLMPricingRule) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *LlmpricingruletypesLLMPricingRule) SetEnabled(v bool) {
	o.Enabled = v
}

// GetId returns the Id field value
func (o *LlmpricingruletypesLLMPricingRule) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *LlmpricingruletypesLLMPricingRule) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *LlmpricingruletypesLLMPricingRule) SetId(v string) {
	o.Id = v
}

// GetIsOverride returns the IsOverride field value
func (o *LlmpricingruletypesLLMPricingRule) GetIsOverride() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsOverride
}

// GetIsOverrideOk returns a tuple with the IsOverride field value
// and a boolean to check if the value has been set.
func (o *LlmpricingruletypesLLMPricingRule) GetIsOverrideOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsOverride, true
}

// SetIsOverride sets field value
func (o *LlmpricingruletypesLLMPricingRule) SetIsOverride(v bool) {
	o.IsOverride = v
}

// GetModelName returns the ModelName field value
func (o *LlmpricingruletypesLLMPricingRule) GetModelName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ModelName
}

// GetModelNameOk returns a tuple with the ModelName field value
// and a boolean to check if the value has been set.
func (o *LlmpricingruletypesLLMPricingRule) GetModelNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ModelName, true
}

// SetModelName sets field value
func (o *LlmpricingruletypesLLMPricingRule) SetModelName(v string) {
	o.ModelName = v
}

// GetModelPattern returns the ModelPattern field value
// If the value is explicit nil, the zero value for []string will be returned
func (o *LlmpricingruletypesLLMPricingRule) GetModelPattern() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.ModelPattern
}

// GetModelPatternOk returns a tuple with the ModelPattern field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LlmpricingruletypesLLMPricingRule) GetModelPatternOk() ([]string, bool) {
	if o == nil || IsNil(o.ModelPattern) {
		return nil, false
	}
	return o.ModelPattern, true
}

// SetModelPattern sets field value
func (o *LlmpricingruletypesLLMPricingRule) SetModelPattern(v []string) {
	o.ModelPattern = v
}

// GetOrgId returns the OrgId field value
func (o *LlmpricingruletypesLLMPricingRule) GetOrgId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrgId
}

// GetOrgIdOk returns a tuple with the OrgId field value
// and a boolean to check if the value has been set.
func (o *LlmpricingruletypesLLMPricingRule) GetOrgIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrgId, true
}

// SetOrgId sets field value
func (o *LlmpricingruletypesLLMPricingRule) SetOrgId(v string) {
	o.OrgId = v
}

// GetPricing returns the Pricing field value
func (o *LlmpricingruletypesLLMPricingRule) GetPricing() LlmpricingruletypesLLMRulePricing {
	if o == nil {
		var ret LlmpricingruletypesLLMRulePricing
		return ret
	}

	return o.Pricing
}

// GetPricingOk returns a tuple with the Pricing field value
// and a boolean to check if the value has been set.
func (o *LlmpricingruletypesLLMPricingRule) GetPricingOk() (*LlmpricingruletypesLLMRulePricing, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pricing, true
}

// SetPricing sets field value
func (o *LlmpricingruletypesLLMPricingRule) SetPricing(v LlmpricingruletypesLLMRulePricing) {
	o.Pricing = v
}

// GetProvider returns the Provider field value
func (o *LlmpricingruletypesLLMPricingRule) GetProvider() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Provider
}

// GetProviderOk returns a tuple with the Provider field value
// and a boolean to check if the value has been set.
func (o *LlmpricingruletypesLLMPricingRule) GetProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Provider, true
}

// SetProvider sets field value
func (o *LlmpricingruletypesLLMPricingRule) SetProvider(v string) {
	o.Provider = v
}

// GetSourceId returns the SourceId field value if set, zero value otherwise.
func (o *LlmpricingruletypesLLMPricingRule) GetSourceId() string {
	if o == nil || IsNil(o.SourceId) {
		var ret string
		return ret
	}
	return *o.SourceId
}

// GetSourceIdOk returns a tuple with the SourceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LlmpricingruletypesLLMPricingRule) GetSourceIdOk() (*string, bool) {
	if o == nil || IsNil(o.SourceId) {
		return nil, false
	}
	return o.SourceId, true
}

// HasSourceId returns a boolean if a field has been set.
func (o *LlmpricingruletypesLLMPricingRule) HasSourceId() bool {
	if o != nil && !IsNil(o.SourceId) {
		return true
	}

	return false
}

// SetSourceId gets a reference to the given string and assigns it to the SourceId field.
func (o *LlmpricingruletypesLLMPricingRule) SetSourceId(v string) {
	o.SourceId = &v
}

// GetSyncedAt returns the SyncedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LlmpricingruletypesLLMPricingRule) GetSyncedAt() time.Time {
	if o == nil || IsNil(o.SyncedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.SyncedAt.Get()
}

// GetSyncedAtOk returns a tuple with the SyncedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LlmpricingruletypesLLMPricingRule) GetSyncedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.SyncedAt.Get(), o.SyncedAt.IsSet()
}

// HasSyncedAt returns a boolean if a field has been set.
func (o *LlmpricingruletypesLLMPricingRule) HasSyncedAt() bool {
	if o != nil && o.SyncedAt.IsSet() {
		return true
	}

	return false
}

// SetSyncedAt gets a reference to the given NullableTime and assigns it to the SyncedAt field.
func (o *LlmpricingruletypesLLMPricingRule) SetSyncedAt(v time.Time) {
	o.SyncedAt.Set(&v)
}
// SetSyncedAtNil sets the value for SyncedAt to be an explicit nil
func (o *LlmpricingruletypesLLMPricingRule) SetSyncedAtNil() {
	o.SyncedAt.Set(nil)
}

// UnsetSyncedAt ensures that no value is present for SyncedAt, not even an explicit nil
func (o *LlmpricingruletypesLLMPricingRule) UnsetSyncedAt() {
	o.SyncedAt.Unset()
}

// GetUnit returns the Unit field value
func (o *LlmpricingruletypesLLMPricingRule) GetUnit() LlmpricingruletypesLLMPricingRuleUnit {
	if o == nil {
		var ret LlmpricingruletypesLLMPricingRuleUnit
		return ret
	}

	return o.Unit
}

// GetUnitOk returns a tuple with the Unit field value
// and a boolean to check if the value has been set.
func (o *LlmpricingruletypesLLMPricingRule) GetUnitOk() (*LlmpricingruletypesLLMPricingRuleUnit, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Unit, true
}

// SetUnit sets field value
func (o *LlmpricingruletypesLLMPricingRule) SetUnit(v LlmpricingruletypesLLMPricingRuleUnit) {
	o.Unit = v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *LlmpricingruletypesLLMPricingRule) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LlmpricingruletypesLLMPricingRule) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *LlmpricingruletypesLLMPricingRule) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *LlmpricingruletypesLLMPricingRule) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetUpdatedBy returns the UpdatedBy field value if set, zero value otherwise.
func (o *LlmpricingruletypesLLMPricingRule) GetUpdatedBy() string {
	if o == nil || IsNil(o.UpdatedBy) {
		var ret string
		return ret
	}
	return *o.UpdatedBy
}

// GetUpdatedByOk returns a tuple with the UpdatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LlmpricingruletypesLLMPricingRule) GetUpdatedByOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedBy) {
		return nil, false
	}
	return o.UpdatedBy, true
}

// HasUpdatedBy returns a boolean if a field has been set.
func (o *LlmpricingruletypesLLMPricingRule) HasUpdatedBy() bool {
	if o != nil && !IsNil(o.UpdatedBy) {
		return true
	}

	return false
}

// SetUpdatedBy gets a reference to the given string and assigns it to the UpdatedBy field.
func (o *LlmpricingruletypesLLMPricingRule) SetUpdatedBy(v string) {
	o.UpdatedBy = &v
}

func (o LlmpricingruletypesLLMPricingRule) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LlmpricingruletypesLLMPricingRule) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.CreatedBy) {
		toSerialize["createdBy"] = o.CreatedBy
	}
	toSerialize["enabled"] = o.Enabled
	toSerialize["id"] = o.Id
	toSerialize["isOverride"] = o.IsOverride
	toSerialize["modelName"] = o.ModelName
	if o.ModelPattern != nil {
		toSerialize["modelPattern"] = o.ModelPattern
	}
	toSerialize["orgId"] = o.OrgId
	toSerialize["pricing"] = o.Pricing
	toSerialize["provider"] = o.Provider
	if !IsNil(o.SourceId) {
		toSerialize["sourceId"] = o.SourceId
	}
	if o.SyncedAt.IsSet() {
		toSerialize["syncedAt"] = o.SyncedAt.Get()
	}
	toSerialize["unit"] = o.Unit
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	if !IsNil(o.UpdatedBy) {
		toSerialize["updatedBy"] = o.UpdatedBy
	}
	return toSerialize, nil
}

func (o *LlmpricingruletypesLLMPricingRule) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"enabled",
		"id",
		"isOverride",
		"modelName",
		"modelPattern",
		"orgId",
		"pricing",
		"provider",
		"unit",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLlmpricingruletypesLLMPricingRule := _LlmpricingruletypesLLMPricingRule{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLlmpricingruletypesLLMPricingRule)

	if err != nil {
		return err
	}

	*o = LlmpricingruletypesLLMPricingRule(varLlmpricingruletypesLLMPricingRule)

	return err
}

type NullableLlmpricingruletypesLLMPricingRule struct {
	value *LlmpricingruletypesLLMPricingRule
	isSet bool
}

func (v NullableLlmpricingruletypesLLMPricingRule) Get() *LlmpricingruletypesLLMPricingRule {
	return v.value
}

func (v *NullableLlmpricingruletypesLLMPricingRule) Set(val *LlmpricingruletypesLLMPricingRule) {
	v.value = val
	v.isSet = true
}

func (v NullableLlmpricingruletypesLLMPricingRule) IsSet() bool {
	return v.isSet
}

func (v *NullableLlmpricingruletypesLLMPricingRule) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLlmpricingruletypesLLMPricingRule(val *LlmpricingruletypesLLMPricingRule) *NullableLlmpricingruletypesLLMPricingRule {
	return &NullableLlmpricingruletypesLLMPricingRule{value: val, isSet: true}
}

func (v NullableLlmpricingruletypesLLMPricingRule) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLlmpricingruletypesLLMPricingRule) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


