/*
SigNoz

OpenTelemetry-Native Logs, Metrics and Traces in a single pane

API version: 
Contact: support@signoz.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package signozclient

import (
	"encoding/json"
)

// checks if the DashboardtypesPostablePublicDashboard type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DashboardtypesPostablePublicDashboard{}

// DashboardtypesPostablePublicDashboard struct for DashboardtypesPostablePublicDashboard
type DashboardtypesPostablePublicDashboard struct {
	DefaultTimeRange *string `json:"defaultTimeRange,omitempty"`
	TimeRangeEnabled *bool `json:"timeRangeEnabled,omitempty"`
}

// NewDashboardtypesPostablePublicDashboard instantiates a new DashboardtypesPostablePublicDashboard object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDashboardtypesPostablePublicDashboard() *DashboardtypesPostablePublicDashboard {
	this := DashboardtypesPostablePublicDashboard{}
	return &this
}

// NewDashboardtypesPostablePublicDashboardWithDefaults instantiates a new DashboardtypesPostablePublicDashboard object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDashboardtypesPostablePublicDashboardWithDefaults() *DashboardtypesPostablePublicDashboard {
	this := DashboardtypesPostablePublicDashboard{}
	return &this
}

// GetDefaultTimeRange returns the DefaultTimeRange field value if set, zero value otherwise.
func (o *DashboardtypesPostablePublicDashboard) GetDefaultTimeRange() string {
	if o == nil || IsNil(o.DefaultTimeRange) {
		var ret string
		return ret
	}
	return *o.DefaultTimeRange
}

// GetDefaultTimeRangeOk returns a tuple with the DefaultTimeRange field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardtypesPostablePublicDashboard) GetDefaultTimeRangeOk() (*string, bool) {
	if o == nil || IsNil(o.DefaultTimeRange) {
		return nil, false
	}
	return o.DefaultTimeRange, true
}

// HasDefaultTimeRange returns a boolean if a field has been set.
func (o *DashboardtypesPostablePublicDashboard) HasDefaultTimeRange() bool {
	if o != nil && !IsNil(o.DefaultTimeRange) {
		return true
	}

	return false
}

// SetDefaultTimeRange gets a reference to the given string and assigns it to the DefaultTimeRange field.
func (o *DashboardtypesPostablePublicDashboard) SetDefaultTimeRange(v string) {
	o.DefaultTimeRange = &v
}

// GetTimeRangeEnabled returns the TimeRangeEnabled field value if set, zero value otherwise.
func (o *DashboardtypesPostablePublicDashboard) GetTimeRangeEnabled() bool {
	if o == nil || IsNil(o.TimeRangeEnabled) {
		var ret bool
		return ret
	}
	return *o.TimeRangeEnabled
}

// GetTimeRangeEnabledOk returns a tuple with the TimeRangeEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardtypesPostablePublicDashboard) GetTimeRangeEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.TimeRangeEnabled) {
		return nil, false
	}
	return o.TimeRangeEnabled, true
}

// HasTimeRangeEnabled returns a boolean if a field has been set.
func (o *DashboardtypesPostablePublicDashboard) HasTimeRangeEnabled() bool {
	if o != nil && !IsNil(o.TimeRangeEnabled) {
		return true
	}

	return false
}

// SetTimeRangeEnabled gets a reference to the given bool and assigns it to the TimeRangeEnabled field.
func (o *DashboardtypesPostablePublicDashboard) SetTimeRangeEnabled(v bool) {
	o.TimeRangeEnabled = &v
}

func (o DashboardtypesPostablePublicDashboard) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DashboardtypesPostablePublicDashboard) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DefaultTimeRange) {
		toSerialize["defaultTimeRange"] = o.DefaultTimeRange
	}
	if !IsNil(o.TimeRangeEnabled) {
		toSerialize["timeRangeEnabled"] = o.TimeRangeEnabled
	}
	return toSerialize, nil
}

type NullableDashboardtypesPostablePublicDashboard struct {
	value *DashboardtypesPostablePublicDashboard
	isSet bool
}

func (v NullableDashboardtypesPostablePublicDashboard) Get() *DashboardtypesPostablePublicDashboard {
	return v.value
}

func (v *NullableDashboardtypesPostablePublicDashboard) Set(val *DashboardtypesPostablePublicDashboard) {
	v.value = val
	v.isSet = true
}

func (v NullableDashboardtypesPostablePublicDashboard) IsSet() bool {
	return v.isSet
}

func (v *NullableDashboardtypesPostablePublicDashboard) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDashboardtypesPostablePublicDashboard(val *DashboardtypesPostablePublicDashboard) *NullableDashboardtypesPostablePublicDashboard {
	return &NullableDashboardtypesPostablePublicDashboard{value: val, isSet: true}
}

func (v NullableDashboardtypesPostablePublicDashboard) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDashboardtypesPostablePublicDashboard) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


