/*
SigNoz

OpenTelemetry-Native Logs, Metrics and Traces in a single pane

API version: 
Contact: support@signoz.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package signozclient

import (
	"encoding/json"
)

// checks if the Querybuildertypesv5TraceAggregation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Querybuildertypesv5TraceAggregation{}

// Querybuildertypesv5TraceAggregation struct for Querybuildertypesv5TraceAggregation
type Querybuildertypesv5TraceAggregation struct {
	Alias *string `json:"alias,omitempty"`
	Expression *string `json:"expression,omitempty"`
}

// NewQuerybuildertypesv5TraceAggregation instantiates a new Querybuildertypesv5TraceAggregation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuerybuildertypesv5TraceAggregation() *Querybuildertypesv5TraceAggregation {
	this := Querybuildertypesv5TraceAggregation{}
	return &this
}

// NewQuerybuildertypesv5TraceAggregationWithDefaults instantiates a new Querybuildertypesv5TraceAggregation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuerybuildertypesv5TraceAggregationWithDefaults() *Querybuildertypesv5TraceAggregation {
	this := Querybuildertypesv5TraceAggregation{}
	return &this
}

// GetAlias returns the Alias field value if set, zero value otherwise.
func (o *Querybuildertypesv5TraceAggregation) GetAlias() string {
	if o == nil || IsNil(o.Alias) {
		var ret string
		return ret
	}
	return *o.Alias
}

// GetAliasOk returns a tuple with the Alias field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Querybuildertypesv5TraceAggregation) GetAliasOk() (*string, bool) {
	if o == nil || IsNil(o.Alias) {
		return nil, false
	}
	return o.Alias, true
}

// HasAlias returns a boolean if a field has been set.
func (o *Querybuildertypesv5TraceAggregation) HasAlias() bool {
	if o != nil && !IsNil(o.Alias) {
		return true
	}

	return false
}

// SetAlias gets a reference to the given string and assigns it to the Alias field.
func (o *Querybuildertypesv5TraceAggregation) SetAlias(v string) {
	o.Alias = &v
}

// GetExpression returns the Expression field value if set, zero value otherwise.
func (o *Querybuildertypesv5TraceAggregation) GetExpression() string {
	if o == nil || IsNil(o.Expression) {
		var ret string
		return ret
	}
	return *o.Expression
}

// GetExpressionOk returns a tuple with the Expression field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Querybuildertypesv5TraceAggregation) GetExpressionOk() (*string, bool) {
	if o == nil || IsNil(o.Expression) {
		return nil, false
	}
	return o.Expression, true
}

// HasExpression returns a boolean if a field has been set.
func (o *Querybuildertypesv5TraceAggregation) HasExpression() bool {
	if o != nil && !IsNil(o.Expression) {
		return true
	}

	return false
}

// SetExpression gets a reference to the given string and assigns it to the Expression field.
func (o *Querybuildertypesv5TraceAggregation) SetExpression(v string) {
	o.Expression = &v
}

func (o Querybuildertypesv5TraceAggregation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Querybuildertypesv5TraceAggregation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Alias) {
		toSerialize["alias"] = o.Alias
	}
	if !IsNil(o.Expression) {
		toSerialize["expression"] = o.Expression
	}
	return toSerialize, nil
}

type NullableQuerybuildertypesv5TraceAggregation struct {
	value *Querybuildertypesv5TraceAggregation
	isSet bool
}

func (v NullableQuerybuildertypesv5TraceAggregation) Get() *Querybuildertypesv5TraceAggregation {
	return v.value
}

func (v *NullableQuerybuildertypesv5TraceAggregation) Set(val *Querybuildertypesv5TraceAggregation) {
	v.value = val
	v.isSet = true
}

func (v NullableQuerybuildertypesv5TraceAggregation) IsSet() bool {
	return v.isSet
}

func (v *NullableQuerybuildertypesv5TraceAggregation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuerybuildertypesv5TraceAggregation(val *Querybuildertypesv5TraceAggregation) *NullableQuerybuildertypesv5TraceAggregation {
	return &NullableQuerybuildertypesv5TraceAggregation{value: val, isSet: true}
}

func (v NullableQuerybuildertypesv5TraceAggregation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuerybuildertypesv5TraceAggregation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


