/*
SigNoz

OpenTelemetry-Native Logs, Metrics and Traces in a single pane

API version: 
Contact: support@signoz.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package signozclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Healthz200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Healthz200Response{}

// Healthz200Response struct for Healthz200Response
type Healthz200Response struct {
	Data FactoryResponse `json:"data"`
	Status string `json:"status"`
}

type _Healthz200Response Healthz200Response

// NewHealthz200Response instantiates a new Healthz200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHealthz200Response(data FactoryResponse, status string) *Healthz200Response {
	this := Healthz200Response{}
	this.Data = data
	this.Status = status
	return &this
}

// NewHealthz200ResponseWithDefaults instantiates a new Healthz200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHealthz200ResponseWithDefaults() *Healthz200Response {
	this := Healthz200Response{}
	return &this
}

// GetData returns the Data field value
func (o *Healthz200Response) GetData() FactoryResponse {
	if o == nil {
		var ret FactoryResponse
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *Healthz200Response) GetDataOk() (*FactoryResponse, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *Healthz200Response) SetData(v FactoryResponse) {
	o.Data = v
}

// GetStatus returns the Status field value
func (o *Healthz200Response) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *Healthz200Response) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *Healthz200Response) SetStatus(v string) {
	o.Status = v
}

func (o Healthz200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Healthz200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *Healthz200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHealthz200Response := _Healthz200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHealthz200Response)

	if err != nil {
		return err
	}

	*o = Healthz200Response(varHealthz200Response)

	return err
}

type NullableHealthz200Response struct {
	value *Healthz200Response
	isSet bool
}

func (v NullableHealthz200Response) Get() *Healthz200Response {
	return v.value
}

func (v *NullableHealthz200Response) Set(val *Healthz200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableHealthz200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableHealthz200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHealthz200Response(val *Healthz200Response) *NullableHealthz200Response {
	return &NullableHealthz200Response{value: val, isSet: true}
}

func (v NullableHealthz200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHealthz200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


