/*
SigNoz

OpenTelemetry-Native Logs, Metrics and Traces in a single pane

API version: 
Contact: support@signoz.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package signozclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CloudintegrationtypesPostableAccount type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CloudintegrationtypesPostableAccount{}

// CloudintegrationtypesPostableAccount struct for CloudintegrationtypesPostableAccount
type CloudintegrationtypesPostableAccount struct {
	Config CloudintegrationtypesPostableAccountConfig `json:"config"`
	Credentials CloudintegrationtypesCredentials `json:"credentials"`
}

type _CloudintegrationtypesPostableAccount CloudintegrationtypesPostableAccount

// NewCloudintegrationtypesPostableAccount instantiates a new CloudintegrationtypesPostableAccount object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCloudintegrationtypesPostableAccount(config CloudintegrationtypesPostableAccountConfig, credentials CloudintegrationtypesCredentials) *CloudintegrationtypesPostableAccount {
	this := CloudintegrationtypesPostableAccount{}
	this.Config = config
	this.Credentials = credentials
	return &this
}

// NewCloudintegrationtypesPostableAccountWithDefaults instantiates a new CloudintegrationtypesPostableAccount object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCloudintegrationtypesPostableAccountWithDefaults() *CloudintegrationtypesPostableAccount {
	this := CloudintegrationtypesPostableAccount{}
	return &this
}

// GetConfig returns the Config field value
func (o *CloudintegrationtypesPostableAccount) GetConfig() CloudintegrationtypesPostableAccountConfig {
	if o == nil {
		var ret CloudintegrationtypesPostableAccountConfig
		return ret
	}

	return o.Config
}

// GetConfigOk returns a tuple with the Config field value
// and a boolean to check if the value has been set.
func (o *CloudintegrationtypesPostableAccount) GetConfigOk() (*CloudintegrationtypesPostableAccountConfig, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Config, true
}

// SetConfig sets field value
func (o *CloudintegrationtypesPostableAccount) SetConfig(v CloudintegrationtypesPostableAccountConfig) {
	o.Config = v
}

// GetCredentials returns the Credentials field value
func (o *CloudintegrationtypesPostableAccount) GetCredentials() CloudintegrationtypesCredentials {
	if o == nil {
		var ret CloudintegrationtypesCredentials
		return ret
	}

	return o.Credentials
}

// GetCredentialsOk returns a tuple with the Credentials field value
// and a boolean to check if the value has been set.
func (o *CloudintegrationtypesPostableAccount) GetCredentialsOk() (*CloudintegrationtypesCredentials, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Credentials, true
}

// SetCredentials sets field value
func (o *CloudintegrationtypesPostableAccount) SetCredentials(v CloudintegrationtypesCredentials) {
	o.Credentials = v
}

func (o CloudintegrationtypesPostableAccount) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CloudintegrationtypesPostableAccount) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["config"] = o.Config
	toSerialize["credentials"] = o.Credentials
	return toSerialize, nil
}

func (o *CloudintegrationtypesPostableAccount) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"config",
		"credentials",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCloudintegrationtypesPostableAccount := _CloudintegrationtypesPostableAccount{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCloudintegrationtypesPostableAccount)

	if err != nil {
		return err
	}

	*o = CloudintegrationtypesPostableAccount(varCloudintegrationtypesPostableAccount)

	return err
}

type NullableCloudintegrationtypesPostableAccount struct {
	value *CloudintegrationtypesPostableAccount
	isSet bool
}

func (v NullableCloudintegrationtypesPostableAccount) Get() *CloudintegrationtypesPostableAccount {
	return v.value
}

func (v *NullableCloudintegrationtypesPostableAccount) Set(val *CloudintegrationtypesPostableAccount) {
	v.value = val
	v.isSet = true
}

func (v NullableCloudintegrationtypesPostableAccount) IsSet() bool {
	return v.isSet
}

func (v *NullableCloudintegrationtypesPostableAccount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCloudintegrationtypesPostableAccount(val *CloudintegrationtypesPostableAccount) *NullableCloudintegrationtypesPostableAccount {
	return &NullableCloudintegrationtypesPostableAccount{value: val, isSet: true}
}

func (v NullableCloudintegrationtypesPostableAccount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCloudintegrationtypesPostableAccount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


