/*
SigNoz

OpenTelemetry-Native Logs, Metrics and Traces in a single pane

API version: 
Contact: support@signoz.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package signozclient

import (
	"encoding/json"
	"fmt"
)

// AlertmanagertypesExpressionKind the model 'AlertmanagertypesExpressionKind'
type AlertmanagertypesExpressionKind string

// List of AlertmanagertypesExpressionKind
const (
	RULE AlertmanagertypesExpressionKind = "rule"
	POLICY AlertmanagertypesExpressionKind = "policy"
)

// All allowed values of AlertmanagertypesExpressionKind enum
var AllowedAlertmanagertypesExpressionKindEnumValues = []AlertmanagertypesExpressionKind{
	"rule",
	"policy",
}

func (v *AlertmanagertypesExpressionKind) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := AlertmanagertypesExpressionKind(value)
	for _, existing := range AllowedAlertmanagertypesExpressionKindEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid AlertmanagertypesExpressionKind", value)
}

// NewAlertmanagertypesExpressionKindFromValue returns a pointer to a valid AlertmanagertypesExpressionKind
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewAlertmanagertypesExpressionKindFromValue(v string) (*AlertmanagertypesExpressionKind, error) {
	ev := AlertmanagertypesExpressionKind(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for AlertmanagertypesExpressionKind: valid values are %v", v, AllowedAlertmanagertypesExpressionKindEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v AlertmanagertypesExpressionKind) IsValid() bool {
	for _, existing := range AllowedAlertmanagertypesExpressionKindEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to AlertmanagertypesExpressionKind value
func (v AlertmanagertypesExpressionKind) Ptr() *AlertmanagertypesExpressionKind {
	return &v
}

type NullableAlertmanagertypesExpressionKind struct {
	value *AlertmanagertypesExpressionKind
	isSet bool
}

func (v NullableAlertmanagertypesExpressionKind) Get() *AlertmanagertypesExpressionKind {
	return v.value
}

func (v *NullableAlertmanagertypesExpressionKind) Set(val *AlertmanagertypesExpressionKind) {
	v.value = val
	v.isSet = true
}

func (v NullableAlertmanagertypesExpressionKind) IsSet() bool {
	return v.isSet
}

func (v *NullableAlertmanagertypesExpressionKind) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlertmanagertypesExpressionKind(val *AlertmanagertypesExpressionKind) *NullableAlertmanagertypesExpressionKind {
	return &NullableAlertmanagertypesExpressionKind{value: val, isSet: true}
}

func (v NullableAlertmanagertypesExpressionKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlertmanagertypesExpressionKind) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

