/*
SigNoz

OpenTelemetry-Native Logs, Metrics and Traces in a single pane

API version: 
Contact: support@signoz.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package signozclient

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the RuletypesRecurrence type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RuletypesRecurrence{}

// RuletypesRecurrence struct for RuletypesRecurrence
type RuletypesRecurrence struct {
	Duration string `json:"duration"`
	EndTime NullableTime `json:"endTime,omitempty"`
	RepeatOn []RuletypesRepeatOn `json:"repeatOn,omitempty"`
	RepeatType RuletypesRepeatType `json:"repeatType"`
	StartTime time.Time `json:"startTime"`
}

type _RuletypesRecurrence RuletypesRecurrence

// NewRuletypesRecurrence instantiates a new RuletypesRecurrence object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRuletypesRecurrence(duration string, repeatType RuletypesRepeatType, startTime time.Time) *RuletypesRecurrence {
	this := RuletypesRecurrence{}
	this.Duration = duration
	this.RepeatType = repeatType
	this.StartTime = startTime
	return &this
}

// NewRuletypesRecurrenceWithDefaults instantiates a new RuletypesRecurrence object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRuletypesRecurrenceWithDefaults() *RuletypesRecurrence {
	this := RuletypesRecurrence{}
	return &this
}

// GetDuration returns the Duration field value
func (o *RuletypesRecurrence) GetDuration() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Duration
}

// GetDurationOk returns a tuple with the Duration field value
// and a boolean to check if the value has been set.
func (o *RuletypesRecurrence) GetDurationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Duration, true
}

// SetDuration sets field value
func (o *RuletypesRecurrence) SetDuration(v string) {
	o.Duration = v
}

// GetEndTime returns the EndTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RuletypesRecurrence) GetEndTime() time.Time {
	if o == nil || IsNil(o.EndTime.Get()) {
		var ret time.Time
		return ret
	}
	return *o.EndTime.Get()
}

// GetEndTimeOk returns a tuple with the EndTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RuletypesRecurrence) GetEndTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.EndTime.Get(), o.EndTime.IsSet()
}

// HasEndTime returns a boolean if a field has been set.
func (o *RuletypesRecurrence) HasEndTime() bool {
	if o != nil && o.EndTime.IsSet() {
		return true
	}

	return false
}

// SetEndTime gets a reference to the given NullableTime and assigns it to the EndTime field.
func (o *RuletypesRecurrence) SetEndTime(v time.Time) {
	o.EndTime.Set(&v)
}
// SetEndTimeNil sets the value for EndTime to be an explicit nil
func (o *RuletypesRecurrence) SetEndTimeNil() {
	o.EndTime.Set(nil)
}

// UnsetEndTime ensures that no value is present for EndTime, not even an explicit nil
func (o *RuletypesRecurrence) UnsetEndTime() {
	o.EndTime.Unset()
}

// GetRepeatOn returns the RepeatOn field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RuletypesRecurrence) GetRepeatOn() []RuletypesRepeatOn {
	if o == nil {
		var ret []RuletypesRepeatOn
		return ret
	}
	return o.RepeatOn
}

// GetRepeatOnOk returns a tuple with the RepeatOn field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RuletypesRecurrence) GetRepeatOnOk() ([]RuletypesRepeatOn, bool) {
	if o == nil || IsNil(o.RepeatOn) {
		return nil, false
	}
	return o.RepeatOn, true
}

// HasRepeatOn returns a boolean if a field has been set.
func (o *RuletypesRecurrence) HasRepeatOn() bool {
	if o != nil && !IsNil(o.RepeatOn) {
		return true
	}

	return false
}

// SetRepeatOn gets a reference to the given []RuletypesRepeatOn and assigns it to the RepeatOn field.
func (o *RuletypesRecurrence) SetRepeatOn(v []RuletypesRepeatOn) {
	o.RepeatOn = v
}

// GetRepeatType returns the RepeatType field value
func (o *RuletypesRecurrence) GetRepeatType() RuletypesRepeatType {
	if o == nil {
		var ret RuletypesRepeatType
		return ret
	}

	return o.RepeatType
}

// GetRepeatTypeOk returns a tuple with the RepeatType field value
// and a boolean to check if the value has been set.
func (o *RuletypesRecurrence) GetRepeatTypeOk() (*RuletypesRepeatType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RepeatType, true
}

// SetRepeatType sets field value
func (o *RuletypesRecurrence) SetRepeatType(v RuletypesRepeatType) {
	o.RepeatType = v
}

// GetStartTime returns the StartTime field value
func (o *RuletypesRecurrence) GetStartTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.StartTime
}

// GetStartTimeOk returns a tuple with the StartTime field value
// and a boolean to check if the value has been set.
func (o *RuletypesRecurrence) GetStartTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartTime, true
}

// SetStartTime sets field value
func (o *RuletypesRecurrence) SetStartTime(v time.Time) {
	o.StartTime = v
}

func (o RuletypesRecurrence) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RuletypesRecurrence) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["duration"] = o.Duration
	if o.EndTime.IsSet() {
		toSerialize["endTime"] = o.EndTime.Get()
	}
	if o.RepeatOn != nil {
		toSerialize["repeatOn"] = o.RepeatOn
	}
	toSerialize["repeatType"] = o.RepeatType
	toSerialize["startTime"] = o.StartTime
	return toSerialize, nil
}

func (o *RuletypesRecurrence) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"duration",
		"repeatType",
		"startTime",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRuletypesRecurrence := _RuletypesRecurrence{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRuletypesRecurrence)

	if err != nil {
		return err
	}

	*o = RuletypesRecurrence(varRuletypesRecurrence)

	return err
}

type NullableRuletypesRecurrence struct {
	value *RuletypesRecurrence
	isSet bool
}

func (v NullableRuletypesRecurrence) Get() *RuletypesRecurrence {
	return v.value
}

func (v *NullableRuletypesRecurrence) Set(val *RuletypesRecurrence) {
	v.value = val
	v.isSet = true
}

func (v NullableRuletypesRecurrence) IsSet() bool {
	return v.isSet
}

func (v *NullableRuletypesRecurrence) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRuletypesRecurrence(val *RuletypesRecurrence) *NullableRuletypesRecurrence {
	return &NullableRuletypesRecurrence{value: val, isSet: true}
}

func (v NullableRuletypesRecurrence) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRuletypesRecurrence) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


