/*
SigNoz

OpenTelemetry-Native Logs, Metrics and Traces in a single pane

API version: 
Contact: support@signoz.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package signozclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RuletypesPostablePlannedMaintenance type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RuletypesPostablePlannedMaintenance{}

// RuletypesPostablePlannedMaintenance struct for RuletypesPostablePlannedMaintenance
type RuletypesPostablePlannedMaintenance struct {
	AlertIds []string `json:"alertIds,omitempty"`
	Description *string `json:"description,omitempty"`
	Name string `json:"name"`
	Schedule RuletypesSchedule `json:"schedule"`
}

type _RuletypesPostablePlannedMaintenance RuletypesPostablePlannedMaintenance

// NewRuletypesPostablePlannedMaintenance instantiates a new RuletypesPostablePlannedMaintenance object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRuletypesPostablePlannedMaintenance(name string, schedule RuletypesSchedule) *RuletypesPostablePlannedMaintenance {
	this := RuletypesPostablePlannedMaintenance{}
	this.Name = name
	this.Schedule = schedule
	return &this
}

// NewRuletypesPostablePlannedMaintenanceWithDefaults instantiates a new RuletypesPostablePlannedMaintenance object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRuletypesPostablePlannedMaintenanceWithDefaults() *RuletypesPostablePlannedMaintenance {
	this := RuletypesPostablePlannedMaintenance{}
	return &this
}

// GetAlertIds returns the AlertIds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RuletypesPostablePlannedMaintenance) GetAlertIds() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.AlertIds
}

// GetAlertIdsOk returns a tuple with the AlertIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RuletypesPostablePlannedMaintenance) GetAlertIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.AlertIds) {
		return nil, false
	}
	return o.AlertIds, true
}

// HasAlertIds returns a boolean if a field has been set.
func (o *RuletypesPostablePlannedMaintenance) HasAlertIds() bool {
	if o != nil && !IsNil(o.AlertIds) {
		return true
	}

	return false
}

// SetAlertIds gets a reference to the given []string and assigns it to the AlertIds field.
func (o *RuletypesPostablePlannedMaintenance) SetAlertIds(v []string) {
	o.AlertIds = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *RuletypesPostablePlannedMaintenance) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RuletypesPostablePlannedMaintenance) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *RuletypesPostablePlannedMaintenance) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *RuletypesPostablePlannedMaintenance) SetDescription(v string) {
	o.Description = &v
}

// GetName returns the Name field value
func (o *RuletypesPostablePlannedMaintenance) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *RuletypesPostablePlannedMaintenance) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *RuletypesPostablePlannedMaintenance) SetName(v string) {
	o.Name = v
}

// GetSchedule returns the Schedule field value
func (o *RuletypesPostablePlannedMaintenance) GetSchedule() RuletypesSchedule {
	if o == nil {
		var ret RuletypesSchedule
		return ret
	}

	return o.Schedule
}

// GetScheduleOk returns a tuple with the Schedule field value
// and a boolean to check if the value has been set.
func (o *RuletypesPostablePlannedMaintenance) GetScheduleOk() (*RuletypesSchedule, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Schedule, true
}

// SetSchedule sets field value
func (o *RuletypesPostablePlannedMaintenance) SetSchedule(v RuletypesSchedule) {
	o.Schedule = v
}

func (o RuletypesPostablePlannedMaintenance) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RuletypesPostablePlannedMaintenance) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.AlertIds != nil {
		toSerialize["alertIds"] = o.AlertIds
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["name"] = o.Name
	toSerialize["schedule"] = o.Schedule
	return toSerialize, nil
}

func (o *RuletypesPostablePlannedMaintenance) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"schedule",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRuletypesPostablePlannedMaintenance := _RuletypesPostablePlannedMaintenance{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRuletypesPostablePlannedMaintenance)

	if err != nil {
		return err
	}

	*o = RuletypesPostablePlannedMaintenance(varRuletypesPostablePlannedMaintenance)

	return err
}

type NullableRuletypesPostablePlannedMaintenance struct {
	value *RuletypesPostablePlannedMaintenance
	isSet bool
}

func (v NullableRuletypesPostablePlannedMaintenance) Get() *RuletypesPostablePlannedMaintenance {
	return v.value
}

func (v *NullableRuletypesPostablePlannedMaintenance) Set(val *RuletypesPostablePlannedMaintenance) {
	v.value = val
	v.isSet = true
}

func (v NullableRuletypesPostablePlannedMaintenance) IsSet() bool {
	return v.isSet
}

func (v *NullableRuletypesPostablePlannedMaintenance) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRuletypesPostablePlannedMaintenance(val *RuletypesPostablePlannedMaintenance) *NullableRuletypesPostablePlannedMaintenance {
	return &NullableRuletypesPostablePlannedMaintenance{value: val, isSet: true}
}

func (v NullableRuletypesPostablePlannedMaintenance) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRuletypesPostablePlannedMaintenance) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


