/*
SigNoz

OpenTelemetry-Native Logs, Metrics and Traces in a single pane

API version: 
Contact: support@signoz.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package signozclient

import (
	"encoding/json"
)

// checks if the ConfigHTTPClientConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigHTTPClientConfig{}

// ConfigHTTPClientConfig struct for ConfigHTTPClientConfig
type ConfigHTTPClientConfig struct {
	Authorization *ConfigAuthorization `json:"authorization,omitempty"`
	BasicAuth *ConfigBasicAuth `json:"basic_auth,omitempty"`
	BearerToken *string `json:"bearer_token,omitempty"`
	BearerTokenFile *string `json:"bearer_token_file,omitempty"`
	EnableHttp2 *bool `json:"enable_http2,omitempty"`
	FollowRedirects *bool `json:"follow_redirects,omitempty"`
	HttpHeaders map[string]interface{} `json:"http_headers,omitempty"`
	NoProxy *string `json:"no_proxy,omitempty"`
	Oauth2 *ConfigOAuth2 `json:"oauth2,omitempty"`
	ProxyConnectHeader *map[string][]string `json:"proxy_connect_header,omitempty"`
	ProxyFromEnvironment *bool `json:"proxy_from_environment,omitempty"`
	ProxyUrl map[string]interface{} `json:"proxy_url,omitempty"`
	TlsConfig *ConfigTLSConfig `json:"tls_config,omitempty"`
}

// NewConfigHTTPClientConfig instantiates a new ConfigHTTPClientConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigHTTPClientConfig() *ConfigHTTPClientConfig {
	this := ConfigHTTPClientConfig{}
	return &this
}

// NewConfigHTTPClientConfigWithDefaults instantiates a new ConfigHTTPClientConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigHTTPClientConfigWithDefaults() *ConfigHTTPClientConfig {
	this := ConfigHTTPClientConfig{}
	return &this
}

// GetAuthorization returns the Authorization field value if set, zero value otherwise.
func (o *ConfigHTTPClientConfig) GetAuthorization() ConfigAuthorization {
	if o == nil || IsNil(o.Authorization) {
		var ret ConfigAuthorization
		return ret
	}
	return *o.Authorization
}

// GetAuthorizationOk returns a tuple with the Authorization field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigHTTPClientConfig) GetAuthorizationOk() (*ConfigAuthorization, bool) {
	if o == nil || IsNil(o.Authorization) {
		return nil, false
	}
	return o.Authorization, true
}

// HasAuthorization returns a boolean if a field has been set.
func (o *ConfigHTTPClientConfig) HasAuthorization() bool {
	if o != nil && !IsNil(o.Authorization) {
		return true
	}

	return false
}

// SetAuthorization gets a reference to the given ConfigAuthorization and assigns it to the Authorization field.
func (o *ConfigHTTPClientConfig) SetAuthorization(v ConfigAuthorization) {
	o.Authorization = &v
}

// GetBasicAuth returns the BasicAuth field value if set, zero value otherwise.
func (o *ConfigHTTPClientConfig) GetBasicAuth() ConfigBasicAuth {
	if o == nil || IsNil(o.BasicAuth) {
		var ret ConfigBasicAuth
		return ret
	}
	return *o.BasicAuth
}

// GetBasicAuthOk returns a tuple with the BasicAuth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigHTTPClientConfig) GetBasicAuthOk() (*ConfigBasicAuth, bool) {
	if o == nil || IsNil(o.BasicAuth) {
		return nil, false
	}
	return o.BasicAuth, true
}

// HasBasicAuth returns a boolean if a field has been set.
func (o *ConfigHTTPClientConfig) HasBasicAuth() bool {
	if o != nil && !IsNil(o.BasicAuth) {
		return true
	}

	return false
}

// SetBasicAuth gets a reference to the given ConfigBasicAuth and assigns it to the BasicAuth field.
func (o *ConfigHTTPClientConfig) SetBasicAuth(v ConfigBasicAuth) {
	o.BasicAuth = &v
}

// GetBearerToken returns the BearerToken field value if set, zero value otherwise.
func (o *ConfigHTTPClientConfig) GetBearerToken() string {
	if o == nil || IsNil(o.BearerToken) {
		var ret string
		return ret
	}
	return *o.BearerToken
}

// GetBearerTokenOk returns a tuple with the BearerToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigHTTPClientConfig) GetBearerTokenOk() (*string, bool) {
	if o == nil || IsNil(o.BearerToken) {
		return nil, false
	}
	return o.BearerToken, true
}

// HasBearerToken returns a boolean if a field has been set.
func (o *ConfigHTTPClientConfig) HasBearerToken() bool {
	if o != nil && !IsNil(o.BearerToken) {
		return true
	}

	return false
}

// SetBearerToken gets a reference to the given string and assigns it to the BearerToken field.
func (o *ConfigHTTPClientConfig) SetBearerToken(v string) {
	o.BearerToken = &v
}

// GetBearerTokenFile returns the BearerTokenFile field value if set, zero value otherwise.
func (o *ConfigHTTPClientConfig) GetBearerTokenFile() string {
	if o == nil || IsNil(o.BearerTokenFile) {
		var ret string
		return ret
	}
	return *o.BearerTokenFile
}

// GetBearerTokenFileOk returns a tuple with the BearerTokenFile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigHTTPClientConfig) GetBearerTokenFileOk() (*string, bool) {
	if o == nil || IsNil(o.BearerTokenFile) {
		return nil, false
	}
	return o.BearerTokenFile, true
}

// HasBearerTokenFile returns a boolean if a field has been set.
func (o *ConfigHTTPClientConfig) HasBearerTokenFile() bool {
	if o != nil && !IsNil(o.BearerTokenFile) {
		return true
	}

	return false
}

// SetBearerTokenFile gets a reference to the given string and assigns it to the BearerTokenFile field.
func (o *ConfigHTTPClientConfig) SetBearerTokenFile(v string) {
	o.BearerTokenFile = &v
}

// GetEnableHttp2 returns the EnableHttp2 field value if set, zero value otherwise.
func (o *ConfigHTTPClientConfig) GetEnableHttp2() bool {
	if o == nil || IsNil(o.EnableHttp2) {
		var ret bool
		return ret
	}
	return *o.EnableHttp2
}

// GetEnableHttp2Ok returns a tuple with the EnableHttp2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigHTTPClientConfig) GetEnableHttp2Ok() (*bool, bool) {
	if o == nil || IsNil(o.EnableHttp2) {
		return nil, false
	}
	return o.EnableHttp2, true
}

// HasEnableHttp2 returns a boolean if a field has been set.
func (o *ConfigHTTPClientConfig) HasEnableHttp2() bool {
	if o != nil && !IsNil(o.EnableHttp2) {
		return true
	}

	return false
}

// SetEnableHttp2 gets a reference to the given bool and assigns it to the EnableHttp2 field.
func (o *ConfigHTTPClientConfig) SetEnableHttp2(v bool) {
	o.EnableHttp2 = &v
}

// GetFollowRedirects returns the FollowRedirects field value if set, zero value otherwise.
func (o *ConfigHTTPClientConfig) GetFollowRedirects() bool {
	if o == nil || IsNil(o.FollowRedirects) {
		var ret bool
		return ret
	}
	return *o.FollowRedirects
}

// GetFollowRedirectsOk returns a tuple with the FollowRedirects field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigHTTPClientConfig) GetFollowRedirectsOk() (*bool, bool) {
	if o == nil || IsNil(o.FollowRedirects) {
		return nil, false
	}
	return o.FollowRedirects, true
}

// HasFollowRedirects returns a boolean if a field has been set.
func (o *ConfigHTTPClientConfig) HasFollowRedirects() bool {
	if o != nil && !IsNil(o.FollowRedirects) {
		return true
	}

	return false
}

// SetFollowRedirects gets a reference to the given bool and assigns it to the FollowRedirects field.
func (o *ConfigHTTPClientConfig) SetFollowRedirects(v bool) {
	o.FollowRedirects = &v
}

// GetHttpHeaders returns the HttpHeaders field value if set, zero value otherwise.
func (o *ConfigHTTPClientConfig) GetHttpHeaders() map[string]interface{} {
	if o == nil || IsNil(o.HttpHeaders) {
		var ret map[string]interface{}
		return ret
	}
	return o.HttpHeaders
}

// GetHttpHeadersOk returns a tuple with the HttpHeaders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigHTTPClientConfig) GetHttpHeadersOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.HttpHeaders) {
		return map[string]interface{}{}, false
	}
	return o.HttpHeaders, true
}

// HasHttpHeaders returns a boolean if a field has been set.
func (o *ConfigHTTPClientConfig) HasHttpHeaders() bool {
	if o != nil && !IsNil(o.HttpHeaders) {
		return true
	}

	return false
}

// SetHttpHeaders gets a reference to the given map[string]interface{} and assigns it to the HttpHeaders field.
func (o *ConfigHTTPClientConfig) SetHttpHeaders(v map[string]interface{}) {
	o.HttpHeaders = v
}

// GetNoProxy returns the NoProxy field value if set, zero value otherwise.
func (o *ConfigHTTPClientConfig) GetNoProxy() string {
	if o == nil || IsNil(o.NoProxy) {
		var ret string
		return ret
	}
	return *o.NoProxy
}

// GetNoProxyOk returns a tuple with the NoProxy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigHTTPClientConfig) GetNoProxyOk() (*string, bool) {
	if o == nil || IsNil(o.NoProxy) {
		return nil, false
	}
	return o.NoProxy, true
}

// HasNoProxy returns a boolean if a field has been set.
func (o *ConfigHTTPClientConfig) HasNoProxy() bool {
	if o != nil && !IsNil(o.NoProxy) {
		return true
	}

	return false
}

// SetNoProxy gets a reference to the given string and assigns it to the NoProxy field.
func (o *ConfigHTTPClientConfig) SetNoProxy(v string) {
	o.NoProxy = &v
}

// GetOauth2 returns the Oauth2 field value if set, zero value otherwise.
func (o *ConfigHTTPClientConfig) GetOauth2() ConfigOAuth2 {
	if o == nil || IsNil(o.Oauth2) {
		var ret ConfigOAuth2
		return ret
	}
	return *o.Oauth2
}

// GetOauth2Ok returns a tuple with the Oauth2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigHTTPClientConfig) GetOauth2Ok() (*ConfigOAuth2, bool) {
	if o == nil || IsNil(o.Oauth2) {
		return nil, false
	}
	return o.Oauth2, true
}

// HasOauth2 returns a boolean if a field has been set.
func (o *ConfigHTTPClientConfig) HasOauth2() bool {
	if o != nil && !IsNil(o.Oauth2) {
		return true
	}

	return false
}

// SetOauth2 gets a reference to the given ConfigOAuth2 and assigns it to the Oauth2 field.
func (o *ConfigHTTPClientConfig) SetOauth2(v ConfigOAuth2) {
	o.Oauth2 = &v
}

// GetProxyConnectHeader returns the ProxyConnectHeader field value if set, zero value otherwise.
func (o *ConfigHTTPClientConfig) GetProxyConnectHeader() map[string][]string {
	if o == nil || IsNil(o.ProxyConnectHeader) {
		var ret map[string][]string
		return ret
	}
	return *o.ProxyConnectHeader
}

// GetProxyConnectHeaderOk returns a tuple with the ProxyConnectHeader field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigHTTPClientConfig) GetProxyConnectHeaderOk() (*map[string][]string, bool) {
	if o == nil || IsNil(o.ProxyConnectHeader) {
		return nil, false
	}
	return o.ProxyConnectHeader, true
}

// HasProxyConnectHeader returns a boolean if a field has been set.
func (o *ConfigHTTPClientConfig) HasProxyConnectHeader() bool {
	if o != nil && !IsNil(o.ProxyConnectHeader) {
		return true
	}

	return false
}

// SetProxyConnectHeader gets a reference to the given map[string][]string and assigns it to the ProxyConnectHeader field.
func (o *ConfigHTTPClientConfig) SetProxyConnectHeader(v map[string][]string) {
	o.ProxyConnectHeader = &v
}

// GetProxyFromEnvironment returns the ProxyFromEnvironment field value if set, zero value otherwise.
func (o *ConfigHTTPClientConfig) GetProxyFromEnvironment() bool {
	if o == nil || IsNil(o.ProxyFromEnvironment) {
		var ret bool
		return ret
	}
	return *o.ProxyFromEnvironment
}

// GetProxyFromEnvironmentOk returns a tuple with the ProxyFromEnvironment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigHTTPClientConfig) GetProxyFromEnvironmentOk() (*bool, bool) {
	if o == nil || IsNil(o.ProxyFromEnvironment) {
		return nil, false
	}
	return o.ProxyFromEnvironment, true
}

// HasProxyFromEnvironment returns a boolean if a field has been set.
func (o *ConfigHTTPClientConfig) HasProxyFromEnvironment() bool {
	if o != nil && !IsNil(o.ProxyFromEnvironment) {
		return true
	}

	return false
}

// SetProxyFromEnvironment gets a reference to the given bool and assigns it to the ProxyFromEnvironment field.
func (o *ConfigHTTPClientConfig) SetProxyFromEnvironment(v bool) {
	o.ProxyFromEnvironment = &v
}

// GetProxyUrl returns the ProxyUrl field value if set, zero value otherwise.
func (o *ConfigHTTPClientConfig) GetProxyUrl() map[string]interface{} {
	if o == nil || IsNil(o.ProxyUrl) {
		var ret map[string]interface{}
		return ret
	}
	return o.ProxyUrl
}

// GetProxyUrlOk returns a tuple with the ProxyUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigHTTPClientConfig) GetProxyUrlOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.ProxyUrl) {
		return map[string]interface{}{}, false
	}
	return o.ProxyUrl, true
}

// HasProxyUrl returns a boolean if a field has been set.
func (o *ConfigHTTPClientConfig) HasProxyUrl() bool {
	if o != nil && !IsNil(o.ProxyUrl) {
		return true
	}

	return false
}

// SetProxyUrl gets a reference to the given map[string]interface{} and assigns it to the ProxyUrl field.
func (o *ConfigHTTPClientConfig) SetProxyUrl(v map[string]interface{}) {
	o.ProxyUrl = v
}

// GetTlsConfig returns the TlsConfig field value if set, zero value otherwise.
func (o *ConfigHTTPClientConfig) GetTlsConfig() ConfigTLSConfig {
	if o == nil || IsNil(o.TlsConfig) {
		var ret ConfigTLSConfig
		return ret
	}
	return *o.TlsConfig
}

// GetTlsConfigOk returns a tuple with the TlsConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigHTTPClientConfig) GetTlsConfigOk() (*ConfigTLSConfig, bool) {
	if o == nil || IsNil(o.TlsConfig) {
		return nil, false
	}
	return o.TlsConfig, true
}

// HasTlsConfig returns a boolean if a field has been set.
func (o *ConfigHTTPClientConfig) HasTlsConfig() bool {
	if o != nil && !IsNil(o.TlsConfig) {
		return true
	}

	return false
}

// SetTlsConfig gets a reference to the given ConfigTLSConfig and assigns it to the TlsConfig field.
func (o *ConfigHTTPClientConfig) SetTlsConfig(v ConfigTLSConfig) {
	o.TlsConfig = &v
}

func (o ConfigHTTPClientConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigHTTPClientConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Authorization) {
		toSerialize["authorization"] = o.Authorization
	}
	if !IsNil(o.BasicAuth) {
		toSerialize["basic_auth"] = o.BasicAuth
	}
	if !IsNil(o.BearerToken) {
		toSerialize["bearer_token"] = o.BearerToken
	}
	if !IsNil(o.BearerTokenFile) {
		toSerialize["bearer_token_file"] = o.BearerTokenFile
	}
	if !IsNil(o.EnableHttp2) {
		toSerialize["enable_http2"] = o.EnableHttp2
	}
	if !IsNil(o.FollowRedirects) {
		toSerialize["follow_redirects"] = o.FollowRedirects
	}
	if !IsNil(o.HttpHeaders) {
		toSerialize["http_headers"] = o.HttpHeaders
	}
	if !IsNil(o.NoProxy) {
		toSerialize["no_proxy"] = o.NoProxy
	}
	if !IsNil(o.Oauth2) {
		toSerialize["oauth2"] = o.Oauth2
	}
	if !IsNil(o.ProxyConnectHeader) {
		toSerialize["proxy_connect_header"] = o.ProxyConnectHeader
	}
	if !IsNil(o.ProxyFromEnvironment) {
		toSerialize["proxy_from_environment"] = o.ProxyFromEnvironment
	}
	if !IsNil(o.ProxyUrl) {
		toSerialize["proxy_url"] = o.ProxyUrl
	}
	if !IsNil(o.TlsConfig) {
		toSerialize["tls_config"] = o.TlsConfig
	}
	return toSerialize, nil
}

type NullableConfigHTTPClientConfig struct {
	value *ConfigHTTPClientConfig
	isSet bool
}

func (v NullableConfigHTTPClientConfig) Get() *ConfigHTTPClientConfig {
	return v.value
}

func (v *NullableConfigHTTPClientConfig) Set(val *ConfigHTTPClientConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigHTTPClientConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigHTTPClientConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigHTTPClientConfig(val *ConfigHTTPClientConfig) *NullableConfigHTTPClientConfig {
	return &NullableConfigHTTPClientConfig{value: val, isSet: true}
}

func (v NullableConfigHTTPClientConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigHTTPClientConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


