/*
SigNoz

OpenTelemetry-Native Logs, Metrics and Traces in a single pane

API version: 
Contact: support@signoz.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package signozclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetResetPasswordTokenDeprecated200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetResetPasswordTokenDeprecated200Response{}

// GetResetPasswordTokenDeprecated200Response struct for GetResetPasswordTokenDeprecated200Response
type GetResetPasswordTokenDeprecated200Response struct {
	Data TypesResetPasswordToken `json:"data"`
	Status string `json:"status"`
}

type _GetResetPasswordTokenDeprecated200Response GetResetPasswordTokenDeprecated200Response

// NewGetResetPasswordTokenDeprecated200Response instantiates a new GetResetPasswordTokenDeprecated200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetResetPasswordTokenDeprecated200Response(data TypesResetPasswordToken, status string) *GetResetPasswordTokenDeprecated200Response {
	this := GetResetPasswordTokenDeprecated200Response{}
	this.Data = data
	this.Status = status
	return &this
}

// NewGetResetPasswordTokenDeprecated200ResponseWithDefaults instantiates a new GetResetPasswordTokenDeprecated200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetResetPasswordTokenDeprecated200ResponseWithDefaults() *GetResetPasswordTokenDeprecated200Response {
	this := GetResetPasswordTokenDeprecated200Response{}
	return &this
}

// GetData returns the Data field value
func (o *GetResetPasswordTokenDeprecated200Response) GetData() TypesResetPasswordToken {
	if o == nil {
		var ret TypesResetPasswordToken
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetResetPasswordTokenDeprecated200Response) GetDataOk() (*TypesResetPasswordToken, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GetResetPasswordTokenDeprecated200Response) SetData(v TypesResetPasswordToken) {
	o.Data = v
}

// GetStatus returns the Status field value
func (o *GetResetPasswordTokenDeprecated200Response) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *GetResetPasswordTokenDeprecated200Response) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *GetResetPasswordTokenDeprecated200Response) SetStatus(v string) {
	o.Status = v
}

func (o GetResetPasswordTokenDeprecated200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetResetPasswordTokenDeprecated200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *GetResetPasswordTokenDeprecated200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetResetPasswordTokenDeprecated200Response := _GetResetPasswordTokenDeprecated200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetResetPasswordTokenDeprecated200Response)

	if err != nil {
		return err
	}

	*o = GetResetPasswordTokenDeprecated200Response(varGetResetPasswordTokenDeprecated200Response)

	return err
}

type NullableGetResetPasswordTokenDeprecated200Response struct {
	value *GetResetPasswordTokenDeprecated200Response
	isSet bool
}

func (v NullableGetResetPasswordTokenDeprecated200Response) Get() *GetResetPasswordTokenDeprecated200Response {
	return v.value
}

func (v *NullableGetResetPasswordTokenDeprecated200Response) Set(val *GetResetPasswordTokenDeprecated200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetResetPasswordTokenDeprecated200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetResetPasswordTokenDeprecated200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetResetPasswordTokenDeprecated200Response(val *GetResetPasswordTokenDeprecated200Response) *NullableGetResetPasswordTokenDeprecated200Response {
	return &NullableGetResetPasswordTokenDeprecated200Response{value: val, isSet: true}
}

func (v NullableGetResetPasswordTokenDeprecated200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetResetPasswordTokenDeprecated200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


