/*
SigNoz

OpenTelemetry-Native Logs, Metrics and Traces in a single pane

API version: 
Contact: support@signoz.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package signozclient

import (
	"encoding/json"
)

// checks if the ConfigDiscordConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigDiscordConfig{}

// ConfigDiscordConfig struct for ConfigDiscordConfig
type ConfigDiscordConfig struct {
	AvatarUrl *string `json:"avatar_url,omitempty"`
	Content *string `json:"content,omitempty"`
	HttpConfig *ConfigHTTPClientConfig `json:"http_config,omitempty"`
	Message *string `json:"message,omitempty"`
	SendResolved *bool `json:"send_resolved,omitempty"`
	Title *string `json:"title,omitempty"`
	Username *string `json:"username,omitempty"`
	WebhookUrl map[string]interface{} `json:"webhook_url,omitempty"`
	WebhookUrlFile *string `json:"webhook_url_file,omitempty"`
}

// NewConfigDiscordConfig instantiates a new ConfigDiscordConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigDiscordConfig() *ConfigDiscordConfig {
	this := ConfigDiscordConfig{}
	return &this
}

// NewConfigDiscordConfigWithDefaults instantiates a new ConfigDiscordConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigDiscordConfigWithDefaults() *ConfigDiscordConfig {
	this := ConfigDiscordConfig{}
	return &this
}

// GetAvatarUrl returns the AvatarUrl field value if set, zero value otherwise.
func (o *ConfigDiscordConfig) GetAvatarUrl() string {
	if o == nil || IsNil(o.AvatarUrl) {
		var ret string
		return ret
	}
	return *o.AvatarUrl
}

// GetAvatarUrlOk returns a tuple with the AvatarUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigDiscordConfig) GetAvatarUrlOk() (*string, bool) {
	if o == nil || IsNil(o.AvatarUrl) {
		return nil, false
	}
	return o.AvatarUrl, true
}

// HasAvatarUrl returns a boolean if a field has been set.
func (o *ConfigDiscordConfig) HasAvatarUrl() bool {
	if o != nil && !IsNil(o.AvatarUrl) {
		return true
	}

	return false
}

// SetAvatarUrl gets a reference to the given string and assigns it to the AvatarUrl field.
func (o *ConfigDiscordConfig) SetAvatarUrl(v string) {
	o.AvatarUrl = &v
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *ConfigDiscordConfig) GetContent() string {
	if o == nil || IsNil(o.Content) {
		var ret string
		return ret
	}
	return *o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigDiscordConfig) GetContentOk() (*string, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *ConfigDiscordConfig) HasContent() bool {
	if o != nil && !IsNil(o.Content) {
		return true
	}

	return false
}

// SetContent gets a reference to the given string and assigns it to the Content field.
func (o *ConfigDiscordConfig) SetContent(v string) {
	o.Content = &v
}

// GetHttpConfig returns the HttpConfig field value if set, zero value otherwise.
func (o *ConfigDiscordConfig) GetHttpConfig() ConfigHTTPClientConfig {
	if o == nil || IsNil(o.HttpConfig) {
		var ret ConfigHTTPClientConfig
		return ret
	}
	return *o.HttpConfig
}

// GetHttpConfigOk returns a tuple with the HttpConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigDiscordConfig) GetHttpConfigOk() (*ConfigHTTPClientConfig, bool) {
	if o == nil || IsNil(o.HttpConfig) {
		return nil, false
	}
	return o.HttpConfig, true
}

// HasHttpConfig returns a boolean if a field has been set.
func (o *ConfigDiscordConfig) HasHttpConfig() bool {
	if o != nil && !IsNil(o.HttpConfig) {
		return true
	}

	return false
}

// SetHttpConfig gets a reference to the given ConfigHTTPClientConfig and assigns it to the HttpConfig field.
func (o *ConfigDiscordConfig) SetHttpConfig(v ConfigHTTPClientConfig) {
	o.HttpConfig = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ConfigDiscordConfig) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigDiscordConfig) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ConfigDiscordConfig) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ConfigDiscordConfig) SetMessage(v string) {
	o.Message = &v
}

// GetSendResolved returns the SendResolved field value if set, zero value otherwise.
func (o *ConfigDiscordConfig) GetSendResolved() bool {
	if o == nil || IsNil(o.SendResolved) {
		var ret bool
		return ret
	}
	return *o.SendResolved
}

// GetSendResolvedOk returns a tuple with the SendResolved field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigDiscordConfig) GetSendResolvedOk() (*bool, bool) {
	if o == nil || IsNil(o.SendResolved) {
		return nil, false
	}
	return o.SendResolved, true
}

// HasSendResolved returns a boolean if a field has been set.
func (o *ConfigDiscordConfig) HasSendResolved() bool {
	if o != nil && !IsNil(o.SendResolved) {
		return true
	}

	return false
}

// SetSendResolved gets a reference to the given bool and assigns it to the SendResolved field.
func (o *ConfigDiscordConfig) SetSendResolved(v bool) {
	o.SendResolved = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *ConfigDiscordConfig) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigDiscordConfig) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *ConfigDiscordConfig) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *ConfigDiscordConfig) SetTitle(v string) {
	o.Title = &v
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *ConfigDiscordConfig) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigDiscordConfig) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *ConfigDiscordConfig) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *ConfigDiscordConfig) SetUsername(v string) {
	o.Username = &v
}

// GetWebhookUrl returns the WebhookUrl field value if set, zero value otherwise.
func (o *ConfigDiscordConfig) GetWebhookUrl() map[string]interface{} {
	if o == nil || IsNil(o.WebhookUrl) {
		var ret map[string]interface{}
		return ret
	}
	return o.WebhookUrl
}

// GetWebhookUrlOk returns a tuple with the WebhookUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigDiscordConfig) GetWebhookUrlOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.WebhookUrl) {
		return map[string]interface{}{}, false
	}
	return o.WebhookUrl, true
}

// HasWebhookUrl returns a boolean if a field has been set.
func (o *ConfigDiscordConfig) HasWebhookUrl() bool {
	if o != nil && !IsNil(o.WebhookUrl) {
		return true
	}

	return false
}

// SetWebhookUrl gets a reference to the given map[string]interface{} and assigns it to the WebhookUrl field.
func (o *ConfigDiscordConfig) SetWebhookUrl(v map[string]interface{}) {
	o.WebhookUrl = v
}

// GetWebhookUrlFile returns the WebhookUrlFile field value if set, zero value otherwise.
func (o *ConfigDiscordConfig) GetWebhookUrlFile() string {
	if o == nil || IsNil(o.WebhookUrlFile) {
		var ret string
		return ret
	}
	return *o.WebhookUrlFile
}

// GetWebhookUrlFileOk returns a tuple with the WebhookUrlFile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigDiscordConfig) GetWebhookUrlFileOk() (*string, bool) {
	if o == nil || IsNil(o.WebhookUrlFile) {
		return nil, false
	}
	return o.WebhookUrlFile, true
}

// HasWebhookUrlFile returns a boolean if a field has been set.
func (o *ConfigDiscordConfig) HasWebhookUrlFile() bool {
	if o != nil && !IsNil(o.WebhookUrlFile) {
		return true
	}

	return false
}

// SetWebhookUrlFile gets a reference to the given string and assigns it to the WebhookUrlFile field.
func (o *ConfigDiscordConfig) SetWebhookUrlFile(v string) {
	o.WebhookUrlFile = &v
}

func (o ConfigDiscordConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigDiscordConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AvatarUrl) {
		toSerialize["avatar_url"] = o.AvatarUrl
	}
	if !IsNil(o.Content) {
		toSerialize["content"] = o.Content
	}
	if !IsNil(o.HttpConfig) {
		toSerialize["http_config"] = o.HttpConfig
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.SendResolved) {
		toSerialize["send_resolved"] = o.SendResolved
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	if !IsNil(o.WebhookUrl) {
		toSerialize["webhook_url"] = o.WebhookUrl
	}
	if !IsNil(o.WebhookUrlFile) {
		toSerialize["webhook_url_file"] = o.WebhookUrlFile
	}
	return toSerialize, nil
}

type NullableConfigDiscordConfig struct {
	value *ConfigDiscordConfig
	isSet bool
}

func (v NullableConfigDiscordConfig) Get() *ConfigDiscordConfig {
	return v.value
}

func (v *NullableConfigDiscordConfig) Set(val *ConfigDiscordConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigDiscordConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigDiscordConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigDiscordConfig(val *ConfigDiscordConfig) *NullableConfigDiscordConfig {
	return &NullableConfigDiscordConfig{value: val, isSet: true}
}

func (v NullableConfigDiscordConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigDiscordConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


