/*
SigNoz

OpenTelemetry-Native Logs, Metrics and Traces in a single pane

API version: 
Contact: support@signoz.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package signozclient

import (
	"encoding/json"
	"time"
)

// checks if the GatewaytypesLimit type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GatewaytypesLimit{}

// GatewaytypesLimit struct for GatewaytypesLimit
type GatewaytypesLimit struct {
	Config *GatewaytypesLimitConfig `json:"config,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Id *string `json:"id,omitempty"`
	KeyId *string `json:"key_id,omitempty"`
	Metric *GatewaytypesLimitMetric `json:"metric,omitempty"`
	Signal *string `json:"signal,omitempty"`
	Tags []string `json:"tags,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// NewGatewaytypesLimit instantiates a new GatewaytypesLimit object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGatewaytypesLimit() *GatewaytypesLimit {
	this := GatewaytypesLimit{}
	return &this
}

// NewGatewaytypesLimitWithDefaults instantiates a new GatewaytypesLimit object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGatewaytypesLimitWithDefaults() *GatewaytypesLimit {
	this := GatewaytypesLimit{}
	return &this
}

// GetConfig returns the Config field value if set, zero value otherwise.
func (o *GatewaytypesLimit) GetConfig() GatewaytypesLimitConfig {
	if o == nil || IsNil(o.Config) {
		var ret GatewaytypesLimitConfig
		return ret
	}
	return *o.Config
}

// GetConfigOk returns a tuple with the Config field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewaytypesLimit) GetConfigOk() (*GatewaytypesLimitConfig, bool) {
	if o == nil || IsNil(o.Config) {
		return nil, false
	}
	return o.Config, true
}

// HasConfig returns a boolean if a field has been set.
func (o *GatewaytypesLimit) HasConfig() bool {
	if o != nil && !IsNil(o.Config) {
		return true
	}

	return false
}

// SetConfig gets a reference to the given GatewaytypesLimitConfig and assigns it to the Config field.
func (o *GatewaytypesLimit) SetConfig(v GatewaytypesLimitConfig) {
	o.Config = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *GatewaytypesLimit) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewaytypesLimit) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *GatewaytypesLimit) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *GatewaytypesLimit) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GatewaytypesLimit) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewaytypesLimit) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GatewaytypesLimit) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *GatewaytypesLimit) SetId(v string) {
	o.Id = &v
}

// GetKeyId returns the KeyId field value if set, zero value otherwise.
func (o *GatewaytypesLimit) GetKeyId() string {
	if o == nil || IsNil(o.KeyId) {
		var ret string
		return ret
	}
	return *o.KeyId
}

// GetKeyIdOk returns a tuple with the KeyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewaytypesLimit) GetKeyIdOk() (*string, bool) {
	if o == nil || IsNil(o.KeyId) {
		return nil, false
	}
	return o.KeyId, true
}

// HasKeyId returns a boolean if a field has been set.
func (o *GatewaytypesLimit) HasKeyId() bool {
	if o != nil && !IsNil(o.KeyId) {
		return true
	}

	return false
}

// SetKeyId gets a reference to the given string and assigns it to the KeyId field.
func (o *GatewaytypesLimit) SetKeyId(v string) {
	o.KeyId = &v
}

// GetMetric returns the Metric field value if set, zero value otherwise.
func (o *GatewaytypesLimit) GetMetric() GatewaytypesLimitMetric {
	if o == nil || IsNil(o.Metric) {
		var ret GatewaytypesLimitMetric
		return ret
	}
	return *o.Metric
}

// GetMetricOk returns a tuple with the Metric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewaytypesLimit) GetMetricOk() (*GatewaytypesLimitMetric, bool) {
	if o == nil || IsNil(o.Metric) {
		return nil, false
	}
	return o.Metric, true
}

// HasMetric returns a boolean if a field has been set.
func (o *GatewaytypesLimit) HasMetric() bool {
	if o != nil && !IsNil(o.Metric) {
		return true
	}

	return false
}

// SetMetric gets a reference to the given GatewaytypesLimitMetric and assigns it to the Metric field.
func (o *GatewaytypesLimit) SetMetric(v GatewaytypesLimitMetric) {
	o.Metric = &v
}

// GetSignal returns the Signal field value if set, zero value otherwise.
func (o *GatewaytypesLimit) GetSignal() string {
	if o == nil || IsNil(o.Signal) {
		var ret string
		return ret
	}
	return *o.Signal
}

// GetSignalOk returns a tuple with the Signal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewaytypesLimit) GetSignalOk() (*string, bool) {
	if o == nil || IsNil(o.Signal) {
		return nil, false
	}
	return o.Signal, true
}

// HasSignal returns a boolean if a field has been set.
func (o *GatewaytypesLimit) HasSignal() bool {
	if o != nil && !IsNil(o.Signal) {
		return true
	}

	return false
}

// SetSignal gets a reference to the given string and assigns it to the Signal field.
func (o *GatewaytypesLimit) SetSignal(v string) {
	o.Signal = &v
}

// GetTags returns the Tags field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GatewaytypesLimit) GetTags() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GatewaytypesLimit) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *GatewaytypesLimit) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *GatewaytypesLimit) SetTags(v []string) {
	o.Tags = v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *GatewaytypesLimit) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewaytypesLimit) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *GatewaytypesLimit) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *GatewaytypesLimit) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o GatewaytypesLimit) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GatewaytypesLimit) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Config) {
		toSerialize["config"] = o.Config
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.KeyId) {
		toSerialize["key_id"] = o.KeyId
	}
	if !IsNil(o.Metric) {
		toSerialize["metric"] = o.Metric
	}
	if !IsNil(o.Signal) {
		toSerialize["signal"] = o.Signal
	}
	if o.Tags != nil {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableGatewaytypesLimit struct {
	value *GatewaytypesLimit
	isSet bool
}

func (v NullableGatewaytypesLimit) Get() *GatewaytypesLimit {
	return v.value
}

func (v *NullableGatewaytypesLimit) Set(val *GatewaytypesLimit) {
	v.value = val
	v.isSet = true
}

func (v NullableGatewaytypesLimit) IsSet() bool {
	return v.isSet
}

func (v *NullableGatewaytypesLimit) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGatewaytypesLimit(val *GatewaytypesLimit) *NullableGatewaytypesLimit {
	return &NullableGatewaytypesLimit{value: val, isSet: true}
}

func (v NullableGatewaytypesLimit) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGatewaytypesLimit) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


