/*
SigNoz

OpenTelemetry-Native Logs, Metrics and Traces in a single pane

API version: 
Contact: support@signoz.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package signozclient

import (
	"encoding/json"
)

// checks if the DashboardtypesGettablePublicDashboardData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DashboardtypesGettablePublicDashboardData{}

// DashboardtypesGettablePublicDashboardData struct for DashboardtypesGettablePublicDashboardData
type DashboardtypesGettablePublicDashboardData struct {
	Dashboard *DashboardtypesDashboard `json:"dashboard,omitempty"`
	PublicDashboard *DashboardtypesGettablePublicDasbhboard `json:"publicDashboard,omitempty"`
}

// NewDashboardtypesGettablePublicDashboardData instantiates a new DashboardtypesGettablePublicDashboardData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDashboardtypesGettablePublicDashboardData() *DashboardtypesGettablePublicDashboardData {
	this := DashboardtypesGettablePublicDashboardData{}
	return &this
}

// NewDashboardtypesGettablePublicDashboardDataWithDefaults instantiates a new DashboardtypesGettablePublicDashboardData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDashboardtypesGettablePublicDashboardDataWithDefaults() *DashboardtypesGettablePublicDashboardData {
	this := DashboardtypesGettablePublicDashboardData{}
	return &this
}

// GetDashboard returns the Dashboard field value if set, zero value otherwise.
func (o *DashboardtypesGettablePublicDashboardData) GetDashboard() DashboardtypesDashboard {
	if o == nil || IsNil(o.Dashboard) {
		var ret DashboardtypesDashboard
		return ret
	}
	return *o.Dashboard
}

// GetDashboardOk returns a tuple with the Dashboard field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardtypesGettablePublicDashboardData) GetDashboardOk() (*DashboardtypesDashboard, bool) {
	if o == nil || IsNil(o.Dashboard) {
		return nil, false
	}
	return o.Dashboard, true
}

// HasDashboard returns a boolean if a field has been set.
func (o *DashboardtypesGettablePublicDashboardData) HasDashboard() bool {
	if o != nil && !IsNil(o.Dashboard) {
		return true
	}

	return false
}

// SetDashboard gets a reference to the given DashboardtypesDashboard and assigns it to the Dashboard field.
func (o *DashboardtypesGettablePublicDashboardData) SetDashboard(v DashboardtypesDashboard) {
	o.Dashboard = &v
}

// GetPublicDashboard returns the PublicDashboard field value if set, zero value otherwise.
func (o *DashboardtypesGettablePublicDashboardData) GetPublicDashboard() DashboardtypesGettablePublicDasbhboard {
	if o == nil || IsNil(o.PublicDashboard) {
		var ret DashboardtypesGettablePublicDasbhboard
		return ret
	}
	return *o.PublicDashboard
}

// GetPublicDashboardOk returns a tuple with the PublicDashboard field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardtypesGettablePublicDashboardData) GetPublicDashboardOk() (*DashboardtypesGettablePublicDasbhboard, bool) {
	if o == nil || IsNil(o.PublicDashboard) {
		return nil, false
	}
	return o.PublicDashboard, true
}

// HasPublicDashboard returns a boolean if a field has been set.
func (o *DashboardtypesGettablePublicDashboardData) HasPublicDashboard() bool {
	if o != nil && !IsNil(o.PublicDashboard) {
		return true
	}

	return false
}

// SetPublicDashboard gets a reference to the given DashboardtypesGettablePublicDasbhboard and assigns it to the PublicDashboard field.
func (o *DashboardtypesGettablePublicDashboardData) SetPublicDashboard(v DashboardtypesGettablePublicDasbhboard) {
	o.PublicDashboard = &v
}

func (o DashboardtypesGettablePublicDashboardData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DashboardtypesGettablePublicDashboardData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Dashboard) {
		toSerialize["dashboard"] = o.Dashboard
	}
	if !IsNil(o.PublicDashboard) {
		toSerialize["publicDashboard"] = o.PublicDashboard
	}
	return toSerialize, nil
}

type NullableDashboardtypesGettablePublicDashboardData struct {
	value *DashboardtypesGettablePublicDashboardData
	isSet bool
}

func (v NullableDashboardtypesGettablePublicDashboardData) Get() *DashboardtypesGettablePublicDashboardData {
	return v.value
}

func (v *NullableDashboardtypesGettablePublicDashboardData) Set(val *DashboardtypesGettablePublicDashboardData) {
	v.value = val
	v.isSet = true
}

func (v NullableDashboardtypesGettablePublicDashboardData) IsSet() bool {
	return v.isSet
}

func (v *NullableDashboardtypesGettablePublicDashboardData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDashboardtypesGettablePublicDashboardData(val *DashboardtypesGettablePublicDashboardData) *NullableDashboardtypesGettablePublicDashboardData {
	return &NullableDashboardtypesGettablePublicDashboardData{value: val, isSet: true}
}

func (v NullableDashboardtypesGettablePublicDashboardData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDashboardtypesGettablePublicDashboardData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


