/*
SigNoz

OpenTelemetry-Native Logs, Metrics and Traces in a single pane

API version: 
Contact: support@signoz.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package signozclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetMetricAlerts200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetMetricAlerts200Response{}

// GetMetricAlerts200Response struct for GetMetricAlerts200Response
type GetMetricAlerts200Response struct {
	Data MetricsexplorertypesMetricAlertsResponse `json:"data"`
	Status string `json:"status"`
}

type _GetMetricAlerts200Response GetMetricAlerts200Response

// NewGetMetricAlerts200Response instantiates a new GetMetricAlerts200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetMetricAlerts200Response(data MetricsexplorertypesMetricAlertsResponse, status string) *GetMetricAlerts200Response {
	this := GetMetricAlerts200Response{}
	this.Data = data
	this.Status = status
	return &this
}

// NewGetMetricAlerts200ResponseWithDefaults instantiates a new GetMetricAlerts200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetMetricAlerts200ResponseWithDefaults() *GetMetricAlerts200Response {
	this := GetMetricAlerts200Response{}
	return &this
}

// GetData returns the Data field value
func (o *GetMetricAlerts200Response) GetData() MetricsexplorertypesMetricAlertsResponse {
	if o == nil {
		var ret MetricsexplorertypesMetricAlertsResponse
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetMetricAlerts200Response) GetDataOk() (*MetricsexplorertypesMetricAlertsResponse, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GetMetricAlerts200Response) SetData(v MetricsexplorertypesMetricAlertsResponse) {
	o.Data = v
}

// GetStatus returns the Status field value
func (o *GetMetricAlerts200Response) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *GetMetricAlerts200Response) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *GetMetricAlerts200Response) SetStatus(v string) {
	o.Status = v
}

func (o GetMetricAlerts200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetMetricAlerts200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *GetMetricAlerts200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetMetricAlerts200Response := _GetMetricAlerts200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetMetricAlerts200Response)

	if err != nil {
		return err
	}

	*o = GetMetricAlerts200Response(varGetMetricAlerts200Response)

	return err
}

type NullableGetMetricAlerts200Response struct {
	value *GetMetricAlerts200Response
	isSet bool
}

func (v NullableGetMetricAlerts200Response) Get() *GetMetricAlerts200Response {
	return v.value
}

func (v *NullableGetMetricAlerts200Response) Set(val *GetMetricAlerts200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetMetricAlerts200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetMetricAlerts200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetMetricAlerts200Response(val *GetMetricAlerts200Response) *NullableGetMetricAlerts200Response {
	return &NullableGetMetricAlerts200Response{value: val, isSet: true}
}

func (v NullableGetMetricAlerts200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetMetricAlerts200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


