/*
SigNoz

OpenTelemetry-Native Logs, Metrics and Traces in a single pane

API version: 
Contact: support@signoz.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package signozclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ServiceaccounttypesPostableServiceAccountRole type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceaccounttypesPostableServiceAccountRole{}

// ServiceaccounttypesPostableServiceAccountRole struct for ServiceaccounttypesPostableServiceAccountRole
type ServiceaccounttypesPostableServiceAccountRole struct {
	Id string `json:"id"`
}

type _ServiceaccounttypesPostableServiceAccountRole ServiceaccounttypesPostableServiceAccountRole

// NewServiceaccounttypesPostableServiceAccountRole instantiates a new ServiceaccounttypesPostableServiceAccountRole object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceaccounttypesPostableServiceAccountRole(id string) *ServiceaccounttypesPostableServiceAccountRole {
	this := ServiceaccounttypesPostableServiceAccountRole{}
	this.Id = id
	return &this
}

// NewServiceaccounttypesPostableServiceAccountRoleWithDefaults instantiates a new ServiceaccounttypesPostableServiceAccountRole object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceaccounttypesPostableServiceAccountRoleWithDefaults() *ServiceaccounttypesPostableServiceAccountRole {
	this := ServiceaccounttypesPostableServiceAccountRole{}
	return &this
}

// GetId returns the Id field value
func (o *ServiceaccounttypesPostableServiceAccountRole) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ServiceaccounttypesPostableServiceAccountRole) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ServiceaccounttypesPostableServiceAccountRole) SetId(v string) {
	o.Id = v
}

func (o ServiceaccounttypesPostableServiceAccountRole) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceaccounttypesPostableServiceAccountRole) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *ServiceaccounttypesPostableServiceAccountRole) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varServiceaccounttypesPostableServiceAccountRole := _ServiceaccounttypesPostableServiceAccountRole{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varServiceaccounttypesPostableServiceAccountRole)

	if err != nil {
		return err
	}

	*o = ServiceaccounttypesPostableServiceAccountRole(varServiceaccounttypesPostableServiceAccountRole)

	return err
}

type NullableServiceaccounttypesPostableServiceAccountRole struct {
	value *ServiceaccounttypesPostableServiceAccountRole
	isSet bool
}

func (v NullableServiceaccounttypesPostableServiceAccountRole) Get() *ServiceaccounttypesPostableServiceAccountRole {
	return v.value
}

func (v *NullableServiceaccounttypesPostableServiceAccountRole) Set(val *ServiceaccounttypesPostableServiceAccountRole) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceaccounttypesPostableServiceAccountRole) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceaccounttypesPostableServiceAccountRole) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceaccounttypesPostableServiceAccountRole(val *ServiceaccounttypesPostableServiceAccountRole) *NullableServiceaccounttypesPostableServiceAccountRole {
	return &NullableServiceaccounttypesPostableServiceAccountRole{value: val, isSet: true}
}

func (v NullableServiceaccounttypesPostableServiceAccountRole) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceaccounttypesPostableServiceAccountRole) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


