/*
SigNoz

OpenTelemetry-Native Logs, Metrics and Traces in a single pane

API version: 
Contact: support@signoz.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package signozclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetServiceAccountRoles200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetServiceAccountRoles200Response{}

// GetServiceAccountRoles200Response struct for GetServiceAccountRoles200Response
type GetServiceAccountRoles200Response struct {
	Data []AuthtypesRole `json:"data"`
	Status string `json:"status"`
}

type _GetServiceAccountRoles200Response GetServiceAccountRoles200Response

// NewGetServiceAccountRoles200Response instantiates a new GetServiceAccountRoles200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetServiceAccountRoles200Response(data []AuthtypesRole, status string) *GetServiceAccountRoles200Response {
	this := GetServiceAccountRoles200Response{}
	this.Data = data
	this.Status = status
	return &this
}

// NewGetServiceAccountRoles200ResponseWithDefaults instantiates a new GetServiceAccountRoles200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetServiceAccountRoles200ResponseWithDefaults() *GetServiceAccountRoles200Response {
	this := GetServiceAccountRoles200Response{}
	return &this
}

// GetData returns the Data field value
// If the value is explicit nil, the zero value for []AuthtypesRole will be returned
func (o *GetServiceAccountRoles200Response) GetData() []AuthtypesRole {
	if o == nil {
		var ret []AuthtypesRole
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetServiceAccountRoles200Response) GetDataOk() ([]AuthtypesRole, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *GetServiceAccountRoles200Response) SetData(v []AuthtypesRole) {
	o.Data = v
}

// GetStatus returns the Status field value
func (o *GetServiceAccountRoles200Response) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *GetServiceAccountRoles200Response) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *GetServiceAccountRoles200Response) SetStatus(v string) {
	o.Status = v
}

func (o GetServiceAccountRoles200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetServiceAccountRoles200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *GetServiceAccountRoles200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetServiceAccountRoles200Response := _GetServiceAccountRoles200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetServiceAccountRoles200Response)

	if err != nil {
		return err
	}

	*o = GetServiceAccountRoles200Response(varGetServiceAccountRoles200Response)

	return err
}

type NullableGetServiceAccountRoles200Response struct {
	value *GetServiceAccountRoles200Response
	isSet bool
}

func (v NullableGetServiceAccountRoles200Response) Get() *GetServiceAccountRoles200Response {
	return v.value
}

func (v *NullableGetServiceAccountRoles200Response) Set(val *GetServiceAccountRoles200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetServiceAccountRoles200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetServiceAccountRoles200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetServiceAccountRoles200Response(val *GetServiceAccountRoles200Response) *NullableGetServiceAccountRoles200Response {
	return &NullableGetServiceAccountRoles200Response{value: val, isSet: true}
}

func (v NullableGetServiceAccountRoles200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetServiceAccountRoles200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


