/*
SigNoz

OpenTelemetry-Native Logs, Metrics and Traces in a single pane

API version: 
Contact: support@signoz.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package signozclient

import (
	"encoding/json"
	"fmt"
)

// MetrictypesSpaceAggregation the model 'MetrictypesSpaceAggregation'
type MetrictypesSpaceAggregation string

// List of MetrictypesSpaceAggregation
const (
	SUM MetrictypesSpaceAggregation = "sum"
	AVG MetrictypesSpaceAggregation = "avg"
	MIN MetrictypesSpaceAggregation = "min"
	MAX MetrictypesSpaceAggregation = "max"
	COUNT MetrictypesSpaceAggregation = "count"
	P50 MetrictypesSpaceAggregation = "p50"
	P75 MetrictypesSpaceAggregation = "p75"
	P90 MetrictypesSpaceAggregation = "p90"
	P95 MetrictypesSpaceAggregation = "p95"
	P99 MetrictypesSpaceAggregation = "p99"
)

// All allowed values of MetrictypesSpaceAggregation enum
var AllowedMetrictypesSpaceAggregationEnumValues = []MetrictypesSpaceAggregation{
	"sum",
	"avg",
	"min",
	"max",
	"count",
	"p50",
	"p75",
	"p90",
	"p95",
	"p99",
}

func (v *MetrictypesSpaceAggregation) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := MetrictypesSpaceAggregation(value)
	for _, existing := range AllowedMetrictypesSpaceAggregationEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid MetrictypesSpaceAggregation", value)
}

// NewMetrictypesSpaceAggregationFromValue returns a pointer to a valid MetrictypesSpaceAggregation
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewMetrictypesSpaceAggregationFromValue(v string) (*MetrictypesSpaceAggregation, error) {
	ev := MetrictypesSpaceAggregation(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for MetrictypesSpaceAggregation: valid values are %v", v, AllowedMetrictypesSpaceAggregationEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v MetrictypesSpaceAggregation) IsValid() bool {
	for _, existing := range AllowedMetrictypesSpaceAggregationEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to MetrictypesSpaceAggregation value
func (v MetrictypesSpaceAggregation) Ptr() *MetrictypesSpaceAggregation {
	return &v
}

type NullableMetrictypesSpaceAggregation struct {
	value *MetrictypesSpaceAggregation
	isSet bool
}

func (v NullableMetrictypesSpaceAggregation) Get() *MetrictypesSpaceAggregation {
	return v.value
}

func (v *NullableMetrictypesSpaceAggregation) Set(val *MetrictypesSpaceAggregation) {
	v.value = val
	v.isSet = true
}

func (v NullableMetrictypesSpaceAggregation) IsSet() bool {
	return v.isSet
}

func (v *NullableMetrictypesSpaceAggregation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetrictypesSpaceAggregation(val *MetrictypesSpaceAggregation) *NullableMetrictypesSpaceAggregation {
	return &NullableMetrictypesSpaceAggregation{value: val, isSet: true}
}

func (v NullableMetrictypesSpaceAggregation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMetrictypesSpaceAggregation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

