/*
SigNoz

OpenTelemetry-Native Logs, Metrics and Traces in a single pane

API version: 
Contact: support@signoz.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package signozclient

import (
	"encoding/json"
)

// checks if the RuletypesNotificationSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RuletypesNotificationSettings{}

// RuletypesNotificationSettings struct for RuletypesNotificationSettings
type RuletypesNotificationSettings struct {
	GroupBy []string `json:"groupBy,omitempty"`
	NewGroupEvalDelay *string `json:"newGroupEvalDelay,omitempty"`
	Renotify *RuletypesRenotify `json:"renotify,omitempty"`
	UsePolicy *bool `json:"usePolicy,omitempty"`
}

// NewRuletypesNotificationSettings instantiates a new RuletypesNotificationSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRuletypesNotificationSettings() *RuletypesNotificationSettings {
	this := RuletypesNotificationSettings{}
	return &this
}

// NewRuletypesNotificationSettingsWithDefaults instantiates a new RuletypesNotificationSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRuletypesNotificationSettingsWithDefaults() *RuletypesNotificationSettings {
	this := RuletypesNotificationSettings{}
	return &this
}

// GetGroupBy returns the GroupBy field value if set, zero value otherwise.
func (o *RuletypesNotificationSettings) GetGroupBy() []string {
	if o == nil || IsNil(o.GroupBy) {
		var ret []string
		return ret
	}
	return o.GroupBy
}

// GetGroupByOk returns a tuple with the GroupBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RuletypesNotificationSettings) GetGroupByOk() ([]string, bool) {
	if o == nil || IsNil(o.GroupBy) {
		return nil, false
	}
	return o.GroupBy, true
}

// HasGroupBy returns a boolean if a field has been set.
func (o *RuletypesNotificationSettings) HasGroupBy() bool {
	if o != nil && !IsNil(o.GroupBy) {
		return true
	}

	return false
}

// SetGroupBy gets a reference to the given []string and assigns it to the GroupBy field.
func (o *RuletypesNotificationSettings) SetGroupBy(v []string) {
	o.GroupBy = v
}

// GetNewGroupEvalDelay returns the NewGroupEvalDelay field value if set, zero value otherwise.
func (o *RuletypesNotificationSettings) GetNewGroupEvalDelay() string {
	if o == nil || IsNil(o.NewGroupEvalDelay) {
		var ret string
		return ret
	}
	return *o.NewGroupEvalDelay
}

// GetNewGroupEvalDelayOk returns a tuple with the NewGroupEvalDelay field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RuletypesNotificationSettings) GetNewGroupEvalDelayOk() (*string, bool) {
	if o == nil || IsNil(o.NewGroupEvalDelay) {
		return nil, false
	}
	return o.NewGroupEvalDelay, true
}

// HasNewGroupEvalDelay returns a boolean if a field has been set.
func (o *RuletypesNotificationSettings) HasNewGroupEvalDelay() bool {
	if o != nil && !IsNil(o.NewGroupEvalDelay) {
		return true
	}

	return false
}

// SetNewGroupEvalDelay gets a reference to the given string and assigns it to the NewGroupEvalDelay field.
func (o *RuletypesNotificationSettings) SetNewGroupEvalDelay(v string) {
	o.NewGroupEvalDelay = &v
}

// GetRenotify returns the Renotify field value if set, zero value otherwise.
func (o *RuletypesNotificationSettings) GetRenotify() RuletypesRenotify {
	if o == nil || IsNil(o.Renotify) {
		var ret RuletypesRenotify
		return ret
	}
	return *o.Renotify
}

// GetRenotifyOk returns a tuple with the Renotify field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RuletypesNotificationSettings) GetRenotifyOk() (*RuletypesRenotify, bool) {
	if o == nil || IsNil(o.Renotify) {
		return nil, false
	}
	return o.Renotify, true
}

// HasRenotify returns a boolean if a field has been set.
func (o *RuletypesNotificationSettings) HasRenotify() bool {
	if o != nil && !IsNil(o.Renotify) {
		return true
	}

	return false
}

// SetRenotify gets a reference to the given RuletypesRenotify and assigns it to the Renotify field.
func (o *RuletypesNotificationSettings) SetRenotify(v RuletypesRenotify) {
	o.Renotify = &v
}

// GetUsePolicy returns the UsePolicy field value if set, zero value otherwise.
func (o *RuletypesNotificationSettings) GetUsePolicy() bool {
	if o == nil || IsNil(o.UsePolicy) {
		var ret bool
		return ret
	}
	return *o.UsePolicy
}

// GetUsePolicyOk returns a tuple with the UsePolicy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RuletypesNotificationSettings) GetUsePolicyOk() (*bool, bool) {
	if o == nil || IsNil(o.UsePolicy) {
		return nil, false
	}
	return o.UsePolicy, true
}

// HasUsePolicy returns a boolean if a field has been set.
func (o *RuletypesNotificationSettings) HasUsePolicy() bool {
	if o != nil && !IsNil(o.UsePolicy) {
		return true
	}

	return false
}

// SetUsePolicy gets a reference to the given bool and assigns it to the UsePolicy field.
func (o *RuletypesNotificationSettings) SetUsePolicy(v bool) {
	o.UsePolicy = &v
}

func (o RuletypesNotificationSettings) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RuletypesNotificationSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.GroupBy) {
		toSerialize["groupBy"] = o.GroupBy
	}
	if !IsNil(o.NewGroupEvalDelay) {
		toSerialize["newGroupEvalDelay"] = o.NewGroupEvalDelay
	}
	if !IsNil(o.Renotify) {
		toSerialize["renotify"] = o.Renotify
	}
	if !IsNil(o.UsePolicy) {
		toSerialize["usePolicy"] = o.UsePolicy
	}
	return toSerialize, nil
}

type NullableRuletypesNotificationSettings struct {
	value *RuletypesNotificationSettings
	isSet bool
}

func (v NullableRuletypesNotificationSettings) Get() *RuletypesNotificationSettings {
	return v.value
}

func (v *NullableRuletypesNotificationSettings) Set(val *RuletypesNotificationSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableRuletypesNotificationSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableRuletypesNotificationSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRuletypesNotificationSettings(val *RuletypesNotificationSettings) *NullableRuletypesNotificationSettings {
	return &NullableRuletypesNotificationSettings{value: val, isSet: true}
}

func (v NullableRuletypesNotificationSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRuletypesNotificationSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


