// Package signozclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package signozclient

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

const (
	Api_keyScopes   = "api_key.Scopes"
	TokenizerScopes = "tokenizer.Scopes"
)

// Defines values for MetrictypesSpaceAggregation.
const (
	MetrictypesSpaceAggregationAvg   MetrictypesSpaceAggregation = "avg"
	MetrictypesSpaceAggregationCount MetrictypesSpaceAggregation = "count"
	MetrictypesSpaceAggregationMax   MetrictypesSpaceAggregation = "max"
	MetrictypesSpaceAggregationMin   MetrictypesSpaceAggregation = "min"
	MetrictypesSpaceAggregationP50   MetrictypesSpaceAggregation = "p50"
	MetrictypesSpaceAggregationP75   MetrictypesSpaceAggregation = "p75"
	MetrictypesSpaceAggregationP90   MetrictypesSpaceAggregation = "p90"
	MetrictypesSpaceAggregationP95   MetrictypesSpaceAggregation = "p95"
	MetrictypesSpaceAggregationP99   MetrictypesSpaceAggregation = "p99"
	MetrictypesSpaceAggregationSum   MetrictypesSpaceAggregation = "sum"
)

// Defines values for MetrictypesTemporality.
const (
	MetrictypesTemporalityCumulative  MetrictypesTemporality = "cumulative"
	MetrictypesTemporalityDelta       MetrictypesTemporality = "delta"
	MetrictypesTemporalityUnspecified MetrictypesTemporality = "unspecified"
)

// Defines values for MetrictypesTimeAggregation.
const (
	MetrictypesTimeAggregationAvg           MetrictypesTimeAggregation = "avg"
	MetrictypesTimeAggregationCount         MetrictypesTimeAggregation = "count"
	MetrictypesTimeAggregationCountDistinct MetrictypesTimeAggregation = "count_distinct"
	MetrictypesTimeAggregationIncrease      MetrictypesTimeAggregation = "increase"
	MetrictypesTimeAggregationLatest        MetrictypesTimeAggregation = "latest"
	MetrictypesTimeAggregationMax           MetrictypesTimeAggregation = "max"
	MetrictypesTimeAggregationMin           MetrictypesTimeAggregation = "min"
	MetrictypesTimeAggregationRate          MetrictypesTimeAggregation = "rate"
	MetrictypesTimeAggregationSum           MetrictypesTimeAggregation = "sum"
)

// Defines values for Querybuildertypesv5FunctionName.
const (
	Absolute      Querybuildertypesv5FunctionName = "absolute"
	Anomaly       Querybuildertypesv5FunctionName = "anomaly"
	Clampmax      Querybuildertypesv5FunctionName = "clampmax"
	Clampmin      Querybuildertypesv5FunctionName = "clampmin"
	Cumulativesum Querybuildertypesv5FunctionName = "cumulativesum"
	Cutoffmax     Querybuildertypesv5FunctionName = "cutoffmax"
	Cutoffmin     Querybuildertypesv5FunctionName = "cutoffmin"
	Ewma3         Querybuildertypesv5FunctionName = "ewma3"
	Ewma5         Querybuildertypesv5FunctionName = "ewma5"
	Ewma7         Querybuildertypesv5FunctionName = "ewma7"
	Fillzero      Querybuildertypesv5FunctionName = "fillzero"
	Log10         Querybuildertypesv5FunctionName = "log10"
	Log2          Querybuildertypesv5FunctionName = "log2"
	Median3       Querybuildertypesv5FunctionName = "median3"
	Median5       Querybuildertypesv5FunctionName = "median5"
	Median7       Querybuildertypesv5FunctionName = "median7"
	Runningdiff   Querybuildertypesv5FunctionName = "runningdiff"
	Timeshift     Querybuildertypesv5FunctionName = "timeshift"
)

// Defines values for Querybuildertypesv5OrderDirection.
const (
	Asc  Querybuildertypesv5OrderDirection = "asc"
	Desc Querybuildertypesv5OrderDirection = "desc"
)

// Defines values for Querybuildertypesv5QueryType.
const (
	Querybuildertypesv5QueryTypeBuilderFormula       Querybuildertypesv5QueryType = "builder_formula"
	Querybuildertypesv5QueryTypeBuilderQuery         Querybuildertypesv5QueryType = "builder_query"
	Querybuildertypesv5QueryTypeBuilderTraceOperator Querybuildertypesv5QueryType = "builder_trace_operator"
	Querybuildertypesv5QueryTypeClickhouseSql        Querybuildertypesv5QueryType = "clickhouse_sql"
	Querybuildertypesv5QueryTypePromql               Querybuildertypesv5QueryType = "promql"
)

// Defines values for Querybuildertypesv5ReduceTo.
const (
	Querybuildertypesv5ReduceToAvg    Querybuildertypesv5ReduceTo = "avg"
	Querybuildertypesv5ReduceToCount  Querybuildertypesv5ReduceTo = "count"
	Querybuildertypesv5ReduceToLast   Querybuildertypesv5ReduceTo = "last"
	Querybuildertypesv5ReduceToMax    Querybuildertypesv5ReduceTo = "max"
	Querybuildertypesv5ReduceToMedian Querybuildertypesv5ReduceTo = "median"
	Querybuildertypesv5ReduceToMin    Querybuildertypesv5ReduceTo = "min"
	Querybuildertypesv5ReduceToSum    Querybuildertypesv5ReduceTo = "sum"
)

// Defines values for RuletypesAlertState.
const (
	Disabled   RuletypesAlertState = "disabled"
	Firing     RuletypesAlertState = "firing"
	Inactive   RuletypesAlertState = "inactive"
	Nodata     RuletypesAlertState = "nodata"
	Pending    RuletypesAlertState = "pending"
	Recovering RuletypesAlertState = "recovering"
)

// Defines values for RuletypesAlertType.
const (
	EXCEPTIONSBASEDALERT RuletypesAlertType = "EXCEPTIONS_BASED_ALERT"
	LOGSBASEDALERT       RuletypesAlertType = "LOGS_BASED_ALERT"
	METRICBASEDALERT     RuletypesAlertType = "METRIC_BASED_ALERT"
	TRACESBASEDALERT     RuletypesAlertType = "TRACES_BASED_ALERT"
)

// Defines values for RuletypesCompareOperator.
const (
	Above         RuletypesCompareOperator = "above"
	Below         RuletypesCompareOperator = "below"
	Equal         RuletypesCompareOperator = "equal"
	NotEqual      RuletypesCompareOperator = "not_equal"
	OutsideBounds RuletypesCompareOperator = "outside_bounds"
)

// Defines values for RuletypesEvaluationKind.
const (
	RuletypesEvaluationKindCumulative RuletypesEvaluationKind = "cumulative"
	RuletypesEvaluationKindRolling    RuletypesEvaluationKind = "rolling"
)

// Defines values for RuletypesMatchType.
const (
	RuletypesMatchTypeAllTheTimes RuletypesMatchType = "all_the_times"
	RuletypesMatchTypeAtLeastOnce RuletypesMatchType = "at_least_once"
	RuletypesMatchTypeInTotal     RuletypesMatchType = "in_total"
	RuletypesMatchTypeLast        RuletypesMatchType = "last"
	RuletypesMatchTypeOnAverage   RuletypesMatchType = "on_average"
)

// Defines values for RuletypesPanelType.
const (
	Graph RuletypesPanelType = "graph"
	Table RuletypesPanelType = "table"
	Value RuletypesPanelType = "value"
)

// Defines values for RuletypesQueryType.
const (
	RuletypesQueryTypeBuilder       RuletypesQueryType = "builder"
	RuletypesQueryTypeClickhouseSql RuletypesQueryType = "clickhouse_sql"
	RuletypesQueryTypePromql        RuletypesQueryType = "promql"
)

// Defines values for RuletypesRuleType.
const (
	AnomalyRule   RuletypesRuleType = "anomaly_rule"
	PromqlRule    RuletypesRuleType = "promql_rule"
	ThresholdRule RuletypesRuleType = "threshold_rule"
)

// Defines values for RuletypesScheduleType.
const (
	RuletypesScheduleTypeDaily   RuletypesScheduleType = "daily"
	RuletypesScheduleTypeHourly  RuletypesScheduleType = "hourly"
	RuletypesScheduleTypeMonthly RuletypesScheduleType = "monthly"
	RuletypesScheduleTypeWeekly  RuletypesScheduleType = "weekly"
)

// Defines values for RuletypesSeasonality.
const (
	RuletypesSeasonalityDaily  RuletypesSeasonality = "daily"
	RuletypesSeasonalityHourly RuletypesSeasonality = "hourly"
	RuletypesSeasonalityWeekly RuletypesSeasonality = "weekly"
)

// Defines values for RuletypesThresholdKind.
const (
	Basic RuletypesThresholdKind = "basic"
)

// Defines values for TelemetrytypesFieldContext.
const (
	Attribute TelemetrytypesFieldContext = "attribute"
	Body      TelemetrytypesFieldContext = "body"
	Log       TelemetrytypesFieldContext = "log"
	Metric    TelemetrytypesFieldContext = "metric"
	Resource  TelemetrytypesFieldContext = "resource"
	Span      TelemetrytypesFieldContext = "span"
)

// Defines values for TelemetrytypesFieldDataType.
const (
	Bool    TelemetrytypesFieldDataType = "bool"
	Float64 TelemetrytypesFieldDataType = "float64"
	Int64   TelemetrytypesFieldDataType = "int64"
	Number  TelemetrytypesFieldDataType = "number"
	String  TelemetrytypesFieldDataType = "string"
)

// Defines values for TelemetrytypesSignal.
const (
	Logs    TelemetrytypesSignal = "logs"
	Metrics TelemetrytypesSignal = "metrics"
	Traces  TelemetrytypesSignal = "traces"
)

// Defines values for TelemetrytypesSource.
const (
	Meter TelemetrytypesSource = "meter"
)

// ErrorsJSON defines model for ErrorsJSON.
type ErrorsJSON struct {
	Code    string                           `json:"code"`
	Errors  *[]ErrorsResponseerroradditional `json:"errors,omitempty"`
	Message string                           `json:"message"`
	Url     *string                          `json:"url,omitempty"`
}

// ErrorsResponseerroradditional defines model for ErrorsResponseerroradditional.
type ErrorsResponseerroradditional struct {
	Message *string `json:"message,omitempty"`
}

// MetrictypesComparisonSpaceAggregationParam defines model for MetrictypesComparisonSpaceAggregationParam.
type MetrictypesComparisonSpaceAggregationParam struct {
	Operator  string  `json:"operator"`
	Threshold float64 `json:"threshold"`
}

// MetrictypesSpaceAggregation defines model for MetrictypesSpaceAggregation.
type MetrictypesSpaceAggregation string

// MetrictypesTemporality defines model for MetrictypesTemporality.
type MetrictypesTemporality string

// MetrictypesTimeAggregation defines model for MetrictypesTimeAggregation.
type MetrictypesTimeAggregation string

// Querybuildertypesv5ClickHouseQuery defines model for Querybuildertypesv5ClickHouseQuery.
type Querybuildertypesv5ClickHouseQuery struct {
	Disabled *bool   `json:"disabled,omitempty"`
	Legend   *string `json:"legend,omitempty"`
	Name     *string `json:"name,omitempty"`
	Query    *string `json:"query,omitempty"`
}

// Querybuildertypesv5Filter defines model for Querybuildertypesv5Filter.
type Querybuildertypesv5Filter struct {
	Expression *string `json:"expression,omitempty"`
}

// Querybuildertypesv5Function defines model for Querybuildertypesv5Function.
type Querybuildertypesv5Function struct {
	Args *[]Querybuildertypesv5FunctionArg `json:"args,omitempty"`
	Name *Querybuildertypesv5FunctionName  `json:"name,omitempty"`
}

// Querybuildertypesv5FunctionArg defines model for Querybuildertypesv5FunctionArg.
type Querybuildertypesv5FunctionArg struct {
	Name  *string      `json:"name,omitempty"`
	Value *interface{} `json:"value,omitempty"`
}

// Querybuildertypesv5FunctionName defines model for Querybuildertypesv5FunctionName.
type Querybuildertypesv5FunctionName string

// Querybuildertypesv5GroupByKey defines model for Querybuildertypesv5GroupByKey.
type Querybuildertypesv5GroupByKey struct {
	Description   *string                      `json:"description,omitempty"`
	FieldContext  *TelemetrytypesFieldContext  `json:"fieldContext,omitempty"`
	FieldDataType *TelemetrytypesFieldDataType `json:"fieldDataType,omitempty"`
	Name          string                       `json:"name"`
	Signal        *TelemetrytypesSignal        `json:"signal,omitempty"`
	Unit          *string                      `json:"unit,omitempty"`
}

// Querybuildertypesv5Having defines model for Querybuildertypesv5Having.
type Querybuildertypesv5Having struct {
	Expression *string `json:"expression,omitempty"`
}

// Querybuildertypesv5LimitBy defines model for Querybuildertypesv5LimitBy.
type Querybuildertypesv5LimitBy struct {
	Keys  *[]string `json:"keys"`
	Value *string   `json:"value,omitempty"`
}

// Querybuildertypesv5LogAggregation defines model for Querybuildertypesv5LogAggregation.
type Querybuildertypesv5LogAggregation struct {
	Alias      *string `json:"alias,omitempty"`
	Expression *string `json:"expression,omitempty"`
}

// Querybuildertypesv5MetricAggregation defines model for Querybuildertypesv5MetricAggregation.
type Querybuildertypesv5MetricAggregation struct {
	ComparisonSpaceAggregationParam *MetrictypesComparisonSpaceAggregationParam `json:"comparisonSpaceAggregationParam,omitempty"`
	MetricName                      *string                                     `json:"metricName,omitempty"`
	ReduceTo                        *Querybuildertypesv5ReduceTo                `json:"reduceTo,omitempty"`
	SpaceAggregation                *MetrictypesSpaceAggregation                `json:"spaceAggregation,omitempty"`
	Temporality                     *MetrictypesTemporality                     `json:"temporality,omitempty"`
	TimeAggregation                 *MetrictypesTimeAggregation                 `json:"timeAggregation,omitempty"`
}

// Querybuildertypesv5OrderBy defines model for Querybuildertypesv5OrderBy.
type Querybuildertypesv5OrderBy struct {
	Direction *Querybuildertypesv5OrderDirection `json:"direction,omitempty"`
	Key       *Querybuildertypesv5OrderByKey     `json:"key,omitempty"`
}

// Querybuildertypesv5OrderByKey defines model for Querybuildertypesv5OrderByKey.
type Querybuildertypesv5OrderByKey struct {
	Description   *string                      `json:"description,omitempty"`
	FieldContext  *TelemetrytypesFieldContext  `json:"fieldContext,omitempty"`
	FieldDataType *TelemetrytypesFieldDataType `json:"fieldDataType,omitempty"`
	Name          string                       `json:"name"`
	Signal        *TelemetrytypesSignal        `json:"signal,omitempty"`
	Unit          *string                      `json:"unit,omitempty"`
}

// Querybuildertypesv5OrderDirection defines model for Querybuildertypesv5OrderDirection.
type Querybuildertypesv5OrderDirection string

// Querybuildertypesv5PromQuery defines model for Querybuildertypesv5PromQuery.
type Querybuildertypesv5PromQuery struct {
	Disabled *bool   `json:"disabled,omitempty"`
	Legend   *string `json:"legend,omitempty"`
	Name     *string `json:"name,omitempty"`
	Query    *string `json:"query,omitempty"`
	Stats    *bool   `json:"stats,omitempty"`

	// Step Step interval. Accepts a Go duration string (e.g., "60s", "1m", "1h") or a number representing seconds (e.g., 60).
	Step *Querybuildertypesv5Step `json:"step,omitempty"`
}

// Querybuildertypesv5QueryBuilderFormula defines model for Querybuildertypesv5QueryBuilderFormula.
type Querybuildertypesv5QueryBuilderFormula struct {
	Disabled   *bool                          `json:"disabled,omitempty"`
	Expression *string                        `json:"expression,omitempty"`
	Functions  *[]Querybuildertypesv5Function `json:"functions,omitempty"`
	Having     *Querybuildertypesv5Having     `json:"having,omitempty"`
	Legend     *string                        `json:"legend,omitempty"`
	Limit      *int                           `json:"limit,omitempty"`
	Name       *string                        `json:"name,omitempty"`
	Order      *[]Querybuildertypesv5OrderBy  `json:"order,omitempty"`
}

// Querybuildertypesv5QueryBuilderQueryGithubComSigNozSignozPkgTypesQuerybuildertypesQuerybuildertypesv5LogAggregation defines model for Querybuildertypesv5QueryBuilderQueryGithubComSigNozSignozPkgTypesQuerybuildertypesQuerybuildertypesv5LogAggregation.
type Querybuildertypesv5QueryBuilderQueryGithubComSigNozSignozPkgTypesQuerybuildertypesQuerybuildertypesv5LogAggregation struct {
	Aggregations          *[]Querybuildertypesv5LogAggregation       `json:"aggregations,omitempty"`
	Cursor                *string                                    `json:"cursor,omitempty"`
	Disabled              *bool                                      `json:"disabled,omitempty"`
	Filter                *Querybuildertypesv5Filter                 `json:"filter,omitempty"`
	Functions             *[]Querybuildertypesv5Function             `json:"functions,omitempty"`
	GroupBy               *[]Querybuildertypesv5GroupByKey           `json:"groupBy,omitempty"`
	Having                *Querybuildertypesv5Having                 `json:"having,omitempty"`
	Legend                *string                                    `json:"legend,omitempty"`
	Limit                 *int                                       `json:"limit,omitempty"`
	LimitBy               *Querybuildertypesv5LimitBy                `json:"limitBy,omitempty"`
	Name                  *string                                    `json:"name,omitempty"`
	Offset                *int                                       `json:"offset,omitempty"`
	Order                 *[]Querybuildertypesv5OrderBy              `json:"order,omitempty"`
	SecondaryAggregations *[]Querybuildertypesv5SecondaryAggregation `json:"secondaryAggregations,omitempty"`
	SelectFields          *[]TelemetrytypesTelemetryFieldKey         `json:"selectFields,omitempty"`
	Signal                *TelemetrytypesSignal                      `json:"signal,omitempty"`
	Source                *TelemetrytypesSource                      `json:"source,omitempty"`

	// StepInterval Step interval. Accepts a Go duration string (e.g., "60s", "1m", "1h") or a number representing seconds (e.g., 60).
	StepInterval *Querybuildertypesv5Step `json:"stepInterval,omitempty"`
}

// Querybuildertypesv5QueryBuilderQueryGithubComSigNozSignozPkgTypesQuerybuildertypesQuerybuildertypesv5MetricAggregation defines model for Querybuildertypesv5QueryBuilderQueryGithubComSigNozSignozPkgTypesQuerybuildertypesQuerybuildertypesv5MetricAggregation.
type Querybuildertypesv5QueryBuilderQueryGithubComSigNozSignozPkgTypesQuerybuildertypesQuerybuildertypesv5MetricAggregation struct {
	Aggregations          *[]Querybuildertypesv5MetricAggregation    `json:"aggregations,omitempty"`
	Cursor                *string                                    `json:"cursor,omitempty"`
	Disabled              *bool                                      `json:"disabled,omitempty"`
	Filter                *Querybuildertypesv5Filter                 `json:"filter,omitempty"`
	Functions             *[]Querybuildertypesv5Function             `json:"functions,omitempty"`
	GroupBy               *[]Querybuildertypesv5GroupByKey           `json:"groupBy,omitempty"`
	Having                *Querybuildertypesv5Having                 `json:"having,omitempty"`
	Legend                *string                                    `json:"legend,omitempty"`
	Limit                 *int                                       `json:"limit,omitempty"`
	LimitBy               *Querybuildertypesv5LimitBy                `json:"limitBy,omitempty"`
	Name                  *string                                    `json:"name,omitempty"`
	Offset                *int                                       `json:"offset,omitempty"`
	Order                 *[]Querybuildertypesv5OrderBy              `json:"order,omitempty"`
	SecondaryAggregations *[]Querybuildertypesv5SecondaryAggregation `json:"secondaryAggregations,omitempty"`
	SelectFields          *[]TelemetrytypesTelemetryFieldKey         `json:"selectFields,omitempty"`
	Signal                *TelemetrytypesSignal                      `json:"signal,omitempty"`
	Source                *TelemetrytypesSource                      `json:"source,omitempty"`

	// StepInterval Step interval. Accepts a Go duration string (e.g., "60s", "1m", "1h") or a number representing seconds (e.g., 60).
	StepInterval *Querybuildertypesv5Step `json:"stepInterval,omitempty"`
}

// Querybuildertypesv5QueryBuilderQueryGithubComSigNozSignozPkgTypesQuerybuildertypesQuerybuildertypesv5TraceAggregation defines model for Querybuildertypesv5QueryBuilderQueryGithubComSigNozSignozPkgTypesQuerybuildertypesQuerybuildertypesv5TraceAggregation.
type Querybuildertypesv5QueryBuilderQueryGithubComSigNozSignozPkgTypesQuerybuildertypesQuerybuildertypesv5TraceAggregation struct {
	Aggregations          *[]Querybuildertypesv5TraceAggregation     `json:"aggregations,omitempty"`
	Cursor                *string                                    `json:"cursor,omitempty"`
	Disabled              *bool                                      `json:"disabled,omitempty"`
	Filter                *Querybuildertypesv5Filter                 `json:"filter,omitempty"`
	Functions             *[]Querybuildertypesv5Function             `json:"functions,omitempty"`
	GroupBy               *[]Querybuildertypesv5GroupByKey           `json:"groupBy,omitempty"`
	Having                *Querybuildertypesv5Having                 `json:"having,omitempty"`
	Legend                *string                                    `json:"legend,omitempty"`
	Limit                 *int                                       `json:"limit,omitempty"`
	LimitBy               *Querybuildertypesv5LimitBy                `json:"limitBy,omitempty"`
	Name                  *string                                    `json:"name,omitempty"`
	Offset                *int                                       `json:"offset,omitempty"`
	Order                 *[]Querybuildertypesv5OrderBy              `json:"order,omitempty"`
	SecondaryAggregations *[]Querybuildertypesv5SecondaryAggregation `json:"secondaryAggregations,omitempty"`
	SelectFields          *[]TelemetrytypesTelemetryFieldKey         `json:"selectFields,omitempty"`
	Signal                *TelemetrytypesSignal                      `json:"signal,omitempty"`
	Source                *TelemetrytypesSource                      `json:"source,omitempty"`

	// StepInterval Step interval. Accepts a Go duration string (e.g., "60s", "1m", "1h") or a number representing seconds (e.g., 60).
	StepInterval *Querybuildertypesv5Step `json:"stepInterval,omitempty"`
}

// Querybuildertypesv5QueryBuilderTraceOperator defines model for Querybuildertypesv5QueryBuilderTraceOperator.
type Querybuildertypesv5QueryBuilderTraceOperator struct {
	Aggregations    *[]Querybuildertypesv5TraceAggregation `json:"aggregations,omitempty"`
	Cursor          *string                                `json:"cursor,omitempty"`
	Disabled        *bool                                  `json:"disabled,omitempty"`
	Expression      *string                                `json:"expression,omitempty"`
	Filter          *Querybuildertypesv5Filter             `json:"filter,omitempty"`
	Functions       *[]Querybuildertypesv5Function         `json:"functions,omitempty"`
	GroupBy         *[]Querybuildertypesv5GroupByKey       `json:"groupBy,omitempty"`
	Having          *Querybuildertypesv5Having             `json:"having,omitempty"`
	Legend          *string                                `json:"legend,omitempty"`
	Limit           *int                                   `json:"limit,omitempty"`
	Name            *string                                `json:"name,omitempty"`
	Offset          *int                                   `json:"offset,omitempty"`
	Order           *[]Querybuildertypesv5OrderBy          `json:"order,omitempty"`
	ReturnSpansFrom *string                                `json:"returnSpansFrom,omitempty"`
	SelectFields    *[]TelemetrytypesTelemetryFieldKey     `json:"selectFields,omitempty"`

	// StepInterval Step interval. Accepts a Go duration string (e.g., "60s", "1m", "1h") or a number representing seconds (e.g., 60).
	StepInterval *Querybuildertypesv5Step `json:"stepInterval,omitempty"`
}

// Querybuildertypesv5QueryEnvelope defines model for Querybuildertypesv5QueryEnvelope.
type Querybuildertypesv5QueryEnvelope struct {
	Spec  *interface{}                  `json:"spec,omitempty"`
	Type  *Querybuildertypesv5QueryType `json:"type,omitempty"`
	union json.RawMessage
}

// Querybuildertypesv5QueryEnvelopeBuilderLog defines model for Querybuildertypesv5QueryEnvelopeBuilderLog.
type Querybuildertypesv5QueryEnvelopeBuilderLog struct {
	Spec *Querybuildertypesv5QueryBuilderQueryGithubComSigNozSignozPkgTypesQuerybuildertypesQuerybuildertypesv5LogAggregation `json:"spec,omitempty"`
	Type *Querybuildertypesv5QueryType                                                                                        `json:"type,omitempty"`
}

// Querybuildertypesv5QueryEnvelopeBuilderMetric defines model for Querybuildertypesv5QueryEnvelopeBuilderMetric.
type Querybuildertypesv5QueryEnvelopeBuilderMetric struct {
	Spec *Querybuildertypesv5QueryBuilderQueryGithubComSigNozSignozPkgTypesQuerybuildertypesQuerybuildertypesv5MetricAggregation `json:"spec,omitempty"`
	Type *Querybuildertypesv5QueryType                                                                                           `json:"type,omitempty"`
}

// Querybuildertypesv5QueryEnvelopeBuilderTrace defines model for Querybuildertypesv5QueryEnvelopeBuilderTrace.
type Querybuildertypesv5QueryEnvelopeBuilderTrace struct {
	Spec *Querybuildertypesv5QueryBuilderQueryGithubComSigNozSignozPkgTypesQuerybuildertypesQuerybuildertypesv5TraceAggregation `json:"spec,omitempty"`
	Type *Querybuildertypesv5QueryType                                                                                          `json:"type,omitempty"`
}

// Querybuildertypesv5QueryEnvelopeClickHouseSQL defines model for Querybuildertypesv5QueryEnvelopeClickHouseSQL.
type Querybuildertypesv5QueryEnvelopeClickHouseSQL struct {
	Spec *Querybuildertypesv5ClickHouseQuery `json:"spec,omitempty"`
	Type *Querybuildertypesv5QueryType       `json:"type,omitempty"`
}

// Querybuildertypesv5QueryEnvelopeFormula defines model for Querybuildertypesv5QueryEnvelopeFormula.
type Querybuildertypesv5QueryEnvelopeFormula struct {
	Spec *Querybuildertypesv5QueryBuilderFormula `json:"spec,omitempty"`
	Type *Querybuildertypesv5QueryType           `json:"type,omitempty"`
}

// Querybuildertypesv5QueryEnvelopePromQL defines model for Querybuildertypesv5QueryEnvelopePromQL.
type Querybuildertypesv5QueryEnvelopePromQL struct {
	Spec *Querybuildertypesv5PromQuery `json:"spec,omitempty"`
	Type *Querybuildertypesv5QueryType `json:"type,omitempty"`
}

// Querybuildertypesv5QueryEnvelopeTraceOperator defines model for Querybuildertypesv5QueryEnvelopeTraceOperator.
type Querybuildertypesv5QueryEnvelopeTraceOperator struct {
	Spec *Querybuildertypesv5QueryBuilderTraceOperator `json:"spec,omitempty"`
	Type *Querybuildertypesv5QueryType                 `json:"type,omitempty"`
}

// Querybuildertypesv5QueryType defines model for Querybuildertypesv5QueryType.
type Querybuildertypesv5QueryType string

// Querybuildertypesv5ReduceTo defines model for Querybuildertypesv5ReduceTo.
type Querybuildertypesv5ReduceTo string

// Querybuildertypesv5SecondaryAggregation defines model for Querybuildertypesv5SecondaryAggregation.
type Querybuildertypesv5SecondaryAggregation struct {
	Alias      *string                          `json:"alias,omitempty"`
	Expression *string                          `json:"expression,omitempty"`
	GroupBy    *[]Querybuildertypesv5GroupByKey `json:"groupBy,omitempty"`
	Limit      *int                             `json:"limit,omitempty"`
	LimitBy    *Querybuildertypesv5LimitBy      `json:"limitBy,omitempty"`
	Order      *[]Querybuildertypesv5OrderBy    `json:"order,omitempty"`

	// StepInterval Step interval. Accepts a Go duration string (e.g., "60s", "1m", "1h") or a number representing seconds (e.g., 60).
	StepInterval *Querybuildertypesv5Step `json:"stepInterval,omitempty"`
}

// Querybuildertypesv5Step Step interval. Accepts a Go duration string (e.g., "60s", "1m", "1h") or a number representing seconds (e.g., 60).
type Querybuildertypesv5Step struct {
	union json.RawMessage
}

// Querybuildertypesv5Step0 Duration string (e.g., "60s", "5m", "1h").
type Querybuildertypesv5Step0 = string

// Querybuildertypesv5Step1 Duration in seconds.
type Querybuildertypesv5Step1 = float32

// Querybuildertypesv5TraceAggregation defines model for Querybuildertypesv5TraceAggregation.
type Querybuildertypesv5TraceAggregation struct {
	Alias      *string `json:"alias,omitempty"`
	Expression *string `json:"expression,omitempty"`
}

// RenderErrorResponse defines model for RenderErrorResponse.
type RenderErrorResponse struct {
	Error  ErrorsJSON `json:"error"`
	Status string     `json:"status"`
}

// RuletypesAlertCompositeQuery defines model for RuletypesAlertCompositeQuery.
type RuletypesAlertCompositeQuery struct {
	PanelType RuletypesPanelType                  `json:"panelType"`
	Queries   *[]Querybuildertypesv5QueryEnvelope `json:"queries"`
	QueryType RuletypesQueryType                  `json:"queryType"`
	Unit      *string                             `json:"unit,omitempty"`
}

// RuletypesAlertState defines model for RuletypesAlertState.
type RuletypesAlertState string

// RuletypesAlertType defines model for RuletypesAlertType.
type RuletypesAlertType string

// RuletypesBasicRuleThreshold defines model for RuletypesBasicRuleThreshold.
type RuletypesBasicRuleThreshold struct {
	Channels       *[]string                `json:"channels"`
	MatchType      RuletypesMatchType       `json:"matchType"`
	Name           string                   `json:"name"`
	Op             RuletypesCompareOperator `json:"op"`
	RecoveryTarget *float32                 `json:"recoveryTarget"`
	Target         *float32                 `json:"target"`
	TargetUnit     *string                  `json:"targetUnit,omitempty"`
}

// RuletypesBasicRuleThresholds defines model for RuletypesBasicRuleThresholds.
type RuletypesBasicRuleThresholds = []RuletypesBasicRuleThreshold

// RuletypesCompareOperator defines model for RuletypesCompareOperator.
type RuletypesCompareOperator string

// RuletypesCumulativeSchedule defines model for RuletypesCumulativeSchedule.
type RuletypesCumulativeSchedule struct {
	Day     *int                  `json:"day"`
	Hour    *int                  `json:"hour"`
	Minute  *int                  `json:"minute"`
	Type    RuletypesScheduleType `json:"type"`
	Weekday *int                  `json:"weekday"`
}

// RuletypesCumulativeWindow defines model for RuletypesCumulativeWindow.
type RuletypesCumulativeWindow struct {
	Frequency string                      `json:"frequency"`
	Schedule  RuletypesCumulativeSchedule `json:"schedule"`
	Timezone  string                      `json:"timezone"`
}

// RuletypesEvaluationCumulative defines model for RuletypesEvaluationCumulative.
type RuletypesEvaluationCumulative struct {
	Kind RuletypesEvaluationKind   `json:"kind"`
	Spec RuletypesCumulativeWindow `json:"spec"`
}

// RuletypesEvaluationEnvelope defines model for RuletypesEvaluationEnvelope.
type RuletypesEvaluationEnvelope struct {
	union json.RawMessage
}

// RuletypesEvaluationKind defines model for RuletypesEvaluationKind.
type RuletypesEvaluationKind string

// RuletypesEvaluationRolling defines model for RuletypesEvaluationRolling.
type RuletypesEvaluationRolling struct {
	Kind RuletypesEvaluationKind `json:"kind"`
	Spec RuletypesRollingWindow  `json:"spec"`
}

// RuletypesMatchType defines model for RuletypesMatchType.
type RuletypesMatchType string

// RuletypesNotificationSettings defines model for RuletypesNotificationSettings.
type RuletypesNotificationSettings struct {
	GroupBy           *[]string          `json:"groupBy,omitempty"`
	NewGroupEvalDelay *string            `json:"newGroupEvalDelay,omitempty"`
	Renotify          *RuletypesRenotify `json:"renotify,omitempty"`
	UsePolicy         *bool              `json:"usePolicy,omitempty"`
}

// RuletypesPanelType defines model for RuletypesPanelType.
type RuletypesPanelType string

// RuletypesPostableRule defines model for RuletypesPostableRule.
type RuletypesPostableRule struct {
	Alert                string                         `json:"alert"`
	AlertType            RuletypesAlertType             `json:"alertType"`
	Annotations          *map[string]string             `json:"annotations,omitempty"`
	Condition            RuletypesRuleCondition         `json:"condition"`
	Description          *string                        `json:"description,omitempty"`
	Disabled             *bool                          `json:"disabled,omitempty"`
	EvalWindow           *string                        `json:"evalWindow,omitempty"`
	Evaluation           *RuletypesEvaluationEnvelope   `json:"evaluation,omitempty"`
	Frequency            *string                        `json:"frequency,omitempty"`
	Labels               *map[string]string             `json:"labels,omitempty"`
	NotificationSettings *RuletypesNotificationSettings `json:"notificationSettings,omitempty"`
	PreferredChannels    *[]string                      `json:"preferredChannels,omitempty"`
	RuleType             RuletypesRuleType              `json:"ruleType"`
	SchemaVersion        *string                        `json:"schemaVersion,omitempty"`
	Source               *string                        `json:"source,omitempty"`
	Version              *string                        `json:"version,omitempty"`
}

// RuletypesQueryType defines model for RuletypesQueryType.
type RuletypesQueryType string

// RuletypesRenotify defines model for RuletypesRenotify.
type RuletypesRenotify struct {
	AlertStates *[]RuletypesAlertState `json:"alertStates,omitempty"`
	Enabled     *bool                  `json:"enabled,omitempty"`
	Interval    *string                `json:"interval,omitempty"`
}

// RuletypesRollingWindow defines model for RuletypesRollingWindow.
type RuletypesRollingWindow struct {
	EvalWindow string `json:"evalWindow"`
	Frequency  string `json:"frequency"`
}

// RuletypesRule defines model for RuletypesRule.
type RuletypesRule struct {
	Alert                string                         `json:"alert"`
	AlertType            RuletypesAlertType             `json:"alertType"`
	Annotations          *map[string]string             `json:"annotations,omitempty"`
	Condition            RuletypesRuleCondition         `json:"condition"`
	CreatedAt            *time.Time                     `json:"createdAt,omitempty"`
	CreatedBy            *string                        `json:"createdBy,omitempty"`
	Description          *string                        `json:"description,omitempty"`
	Disabled             *bool                          `json:"disabled,omitempty"`
	EvalWindow           *string                        `json:"evalWindow,omitempty"`
	Evaluation           *RuletypesEvaluationEnvelope   `json:"evaluation,omitempty"`
	Frequency            *string                        `json:"frequency,omitempty"`
	Id                   string                         `json:"id"`
	Labels               *map[string]string             `json:"labels,omitempty"`
	NotificationSettings *RuletypesNotificationSettings `json:"notificationSettings,omitempty"`
	PreferredChannels    *[]string                      `json:"preferredChannels,omitempty"`
	RuleType             RuletypesRuleType              `json:"ruleType"`
	SchemaVersion        *string                        `json:"schemaVersion,omitempty"`
	Source               *string                        `json:"source,omitempty"`
	State                RuletypesAlertState            `json:"state"`
	UpdatedAt            *time.Time                     `json:"updatedAt,omitempty"`
	UpdatedBy            *string                        `json:"updatedBy,omitempty"`
	Version              *string                        `json:"version,omitempty"`
}

// RuletypesRuleCondition defines model for RuletypesRuleCondition.
type RuletypesRuleCondition struct {
	AbsentFor         *int                         `json:"absentFor,omitempty"`
	AlertOnAbsent     *bool                        `json:"alertOnAbsent,omitempty"`
	Algorithm         *string                      `json:"algorithm,omitempty"`
	CompositeQuery    RuletypesAlertCompositeQuery `json:"compositeQuery"`
	MatchType         *RuletypesMatchType          `json:"matchType,omitempty"`
	Op                *RuletypesCompareOperator    `json:"op,omitempty"`
	RequireMinPoints  *bool                        `json:"requireMinPoints,omitempty"`
	RequiredNumPoints *int                         `json:"requiredNumPoints,omitempty"`
	Seasonality       *RuletypesSeasonality        `json:"seasonality,omitempty"`
	SelectedQueryName *string                      `json:"selectedQueryName,omitempty"`
	Target            *float32                     `json:"target"`
	TargetUnit        *string                      `json:"targetUnit,omitempty"`
	Thresholds        *RuletypesRuleThresholdData  `json:"thresholds,omitempty"`
}

// RuletypesRuleThresholdData defines model for RuletypesRuleThresholdData.
type RuletypesRuleThresholdData struct {
	union json.RawMessage
}

// RuletypesRuleType defines model for RuletypesRuleType.
type RuletypesRuleType string

// RuletypesScheduleType defines model for RuletypesScheduleType.
type RuletypesScheduleType string

// RuletypesSeasonality defines model for RuletypesSeasonality.
type RuletypesSeasonality string

// RuletypesThresholdBasic defines model for RuletypesThresholdBasic.
type RuletypesThresholdBasic struct {
	Kind RuletypesThresholdKind        `json:"kind"`
	Spec *RuletypesBasicRuleThresholds `json:"spec"`
}

// RuletypesThresholdKind defines model for RuletypesThresholdKind.
type RuletypesThresholdKind string

// TelemetrytypesFieldContext defines model for TelemetrytypesFieldContext.
type TelemetrytypesFieldContext string

// TelemetrytypesFieldDataType defines model for TelemetrytypesFieldDataType.
type TelemetrytypesFieldDataType string

// TelemetrytypesSignal defines model for TelemetrytypesSignal.
type TelemetrytypesSignal string

// TelemetrytypesSource defines model for TelemetrytypesSource.
type TelemetrytypesSource string

// TelemetrytypesTelemetryFieldKey defines model for TelemetrytypesTelemetryFieldKey.
type TelemetrytypesTelemetryFieldKey struct {
	Description   *string                      `json:"description,omitempty"`
	FieldContext  *TelemetrytypesFieldContext  `json:"fieldContext,omitempty"`
	FieldDataType *TelemetrytypesFieldDataType `json:"fieldDataType,omitempty"`
	Name          string                       `json:"name"`
	Signal        *TelemetrytypesSignal        `json:"signal,omitempty"`
	Unit          *string                      `json:"unit,omitempty"`
}

// CreateRuleJSONRequestBody defines body for CreateRule for application/json ContentType.
type CreateRuleJSONRequestBody = RuletypesPostableRule

// UpdateRuleByIDJSONRequestBody defines body for UpdateRuleByID for application/json ContentType.
type UpdateRuleByIDJSONRequestBody = RuletypesPostableRule

// AsQuerybuildertypesv5QueryEnvelopeBuilderTrace returns the union data inside the Querybuildertypesv5QueryEnvelope as a Querybuildertypesv5QueryEnvelopeBuilderTrace
func (t Querybuildertypesv5QueryEnvelope) AsQuerybuildertypesv5QueryEnvelopeBuilderTrace() (Querybuildertypesv5QueryEnvelopeBuilderTrace, error) {
	var body Querybuildertypesv5QueryEnvelopeBuilderTrace
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromQuerybuildertypesv5QueryEnvelopeBuilderTrace overwrites any union data inside the Querybuildertypesv5QueryEnvelope as the provided Querybuildertypesv5QueryEnvelopeBuilderTrace
func (t *Querybuildertypesv5QueryEnvelope) FromQuerybuildertypesv5QueryEnvelopeBuilderTrace(v Querybuildertypesv5QueryEnvelopeBuilderTrace) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeQuerybuildertypesv5QueryEnvelopeBuilderTrace performs a merge with any union data inside the Querybuildertypesv5QueryEnvelope, using the provided Querybuildertypesv5QueryEnvelopeBuilderTrace
func (t *Querybuildertypesv5QueryEnvelope) MergeQuerybuildertypesv5QueryEnvelopeBuilderTrace(v Querybuildertypesv5QueryEnvelopeBuilderTrace) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsQuerybuildertypesv5QueryEnvelopeBuilderLog returns the union data inside the Querybuildertypesv5QueryEnvelope as a Querybuildertypesv5QueryEnvelopeBuilderLog
func (t Querybuildertypesv5QueryEnvelope) AsQuerybuildertypesv5QueryEnvelopeBuilderLog() (Querybuildertypesv5QueryEnvelopeBuilderLog, error) {
	var body Querybuildertypesv5QueryEnvelopeBuilderLog
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromQuerybuildertypesv5QueryEnvelopeBuilderLog overwrites any union data inside the Querybuildertypesv5QueryEnvelope as the provided Querybuildertypesv5QueryEnvelopeBuilderLog
func (t *Querybuildertypesv5QueryEnvelope) FromQuerybuildertypesv5QueryEnvelopeBuilderLog(v Querybuildertypesv5QueryEnvelopeBuilderLog) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeQuerybuildertypesv5QueryEnvelopeBuilderLog performs a merge with any union data inside the Querybuildertypesv5QueryEnvelope, using the provided Querybuildertypesv5QueryEnvelopeBuilderLog
func (t *Querybuildertypesv5QueryEnvelope) MergeQuerybuildertypesv5QueryEnvelopeBuilderLog(v Querybuildertypesv5QueryEnvelopeBuilderLog) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsQuerybuildertypesv5QueryEnvelopeBuilderMetric returns the union data inside the Querybuildertypesv5QueryEnvelope as a Querybuildertypesv5QueryEnvelopeBuilderMetric
func (t Querybuildertypesv5QueryEnvelope) AsQuerybuildertypesv5QueryEnvelopeBuilderMetric() (Querybuildertypesv5QueryEnvelopeBuilderMetric, error) {
	var body Querybuildertypesv5QueryEnvelopeBuilderMetric
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromQuerybuildertypesv5QueryEnvelopeBuilderMetric overwrites any union data inside the Querybuildertypesv5QueryEnvelope as the provided Querybuildertypesv5QueryEnvelopeBuilderMetric
func (t *Querybuildertypesv5QueryEnvelope) FromQuerybuildertypesv5QueryEnvelopeBuilderMetric(v Querybuildertypesv5QueryEnvelopeBuilderMetric) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeQuerybuildertypesv5QueryEnvelopeBuilderMetric performs a merge with any union data inside the Querybuildertypesv5QueryEnvelope, using the provided Querybuildertypesv5QueryEnvelopeBuilderMetric
func (t *Querybuildertypesv5QueryEnvelope) MergeQuerybuildertypesv5QueryEnvelopeBuilderMetric(v Querybuildertypesv5QueryEnvelopeBuilderMetric) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsQuerybuildertypesv5QueryEnvelopeFormula returns the union data inside the Querybuildertypesv5QueryEnvelope as a Querybuildertypesv5QueryEnvelopeFormula
func (t Querybuildertypesv5QueryEnvelope) AsQuerybuildertypesv5QueryEnvelopeFormula() (Querybuildertypesv5QueryEnvelopeFormula, error) {
	var body Querybuildertypesv5QueryEnvelopeFormula
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromQuerybuildertypesv5QueryEnvelopeFormula overwrites any union data inside the Querybuildertypesv5QueryEnvelope as the provided Querybuildertypesv5QueryEnvelopeFormula
func (t *Querybuildertypesv5QueryEnvelope) FromQuerybuildertypesv5QueryEnvelopeFormula(v Querybuildertypesv5QueryEnvelopeFormula) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeQuerybuildertypesv5QueryEnvelopeFormula performs a merge with any union data inside the Querybuildertypesv5QueryEnvelope, using the provided Querybuildertypesv5QueryEnvelopeFormula
func (t *Querybuildertypesv5QueryEnvelope) MergeQuerybuildertypesv5QueryEnvelopeFormula(v Querybuildertypesv5QueryEnvelopeFormula) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsQuerybuildertypesv5QueryEnvelopeTraceOperator returns the union data inside the Querybuildertypesv5QueryEnvelope as a Querybuildertypesv5QueryEnvelopeTraceOperator
func (t Querybuildertypesv5QueryEnvelope) AsQuerybuildertypesv5QueryEnvelopeTraceOperator() (Querybuildertypesv5QueryEnvelopeTraceOperator, error) {
	var body Querybuildertypesv5QueryEnvelopeTraceOperator
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromQuerybuildertypesv5QueryEnvelopeTraceOperator overwrites any union data inside the Querybuildertypesv5QueryEnvelope as the provided Querybuildertypesv5QueryEnvelopeTraceOperator
func (t *Querybuildertypesv5QueryEnvelope) FromQuerybuildertypesv5QueryEnvelopeTraceOperator(v Querybuildertypesv5QueryEnvelopeTraceOperator) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeQuerybuildertypesv5QueryEnvelopeTraceOperator performs a merge with any union data inside the Querybuildertypesv5QueryEnvelope, using the provided Querybuildertypesv5QueryEnvelopeTraceOperator
func (t *Querybuildertypesv5QueryEnvelope) MergeQuerybuildertypesv5QueryEnvelopeTraceOperator(v Querybuildertypesv5QueryEnvelopeTraceOperator) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsQuerybuildertypesv5QueryEnvelopePromQL returns the union data inside the Querybuildertypesv5QueryEnvelope as a Querybuildertypesv5QueryEnvelopePromQL
func (t Querybuildertypesv5QueryEnvelope) AsQuerybuildertypesv5QueryEnvelopePromQL() (Querybuildertypesv5QueryEnvelopePromQL, error) {
	var body Querybuildertypesv5QueryEnvelopePromQL
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromQuerybuildertypesv5QueryEnvelopePromQL overwrites any union data inside the Querybuildertypesv5QueryEnvelope as the provided Querybuildertypesv5QueryEnvelopePromQL
func (t *Querybuildertypesv5QueryEnvelope) FromQuerybuildertypesv5QueryEnvelopePromQL(v Querybuildertypesv5QueryEnvelopePromQL) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeQuerybuildertypesv5QueryEnvelopePromQL performs a merge with any union data inside the Querybuildertypesv5QueryEnvelope, using the provided Querybuildertypesv5QueryEnvelopePromQL
func (t *Querybuildertypesv5QueryEnvelope) MergeQuerybuildertypesv5QueryEnvelopePromQL(v Querybuildertypesv5QueryEnvelopePromQL) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsQuerybuildertypesv5QueryEnvelopeClickHouseSQL returns the union data inside the Querybuildertypesv5QueryEnvelope as a Querybuildertypesv5QueryEnvelopeClickHouseSQL
func (t Querybuildertypesv5QueryEnvelope) AsQuerybuildertypesv5QueryEnvelopeClickHouseSQL() (Querybuildertypesv5QueryEnvelopeClickHouseSQL, error) {
	var body Querybuildertypesv5QueryEnvelopeClickHouseSQL
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromQuerybuildertypesv5QueryEnvelopeClickHouseSQL overwrites any union data inside the Querybuildertypesv5QueryEnvelope as the provided Querybuildertypesv5QueryEnvelopeClickHouseSQL
func (t *Querybuildertypesv5QueryEnvelope) FromQuerybuildertypesv5QueryEnvelopeClickHouseSQL(v Querybuildertypesv5QueryEnvelopeClickHouseSQL) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeQuerybuildertypesv5QueryEnvelopeClickHouseSQL performs a merge with any union data inside the Querybuildertypesv5QueryEnvelope, using the provided Querybuildertypesv5QueryEnvelopeClickHouseSQL
func (t *Querybuildertypesv5QueryEnvelope) MergeQuerybuildertypesv5QueryEnvelopeClickHouseSQL(v Querybuildertypesv5QueryEnvelopeClickHouseSQL) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Querybuildertypesv5QueryEnvelope) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	if t.Spec != nil {
		object["spec"], err = json.Marshal(t.Spec)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'spec': %w", err)
		}
	}

	if t.Type != nil {
		object["type"], err = json.Marshal(t.Type)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'type': %w", err)
		}
	}
	b, err = json.Marshal(object)
	return b, err
}

func (t *Querybuildertypesv5QueryEnvelope) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["spec"]; found {
		err = json.Unmarshal(raw, &t.Spec)
		if err != nil {
			return fmt.Errorf("error reading 'spec': %w", err)
		}
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &t.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
	}

	return err
}

// AsQuerybuildertypesv5Step0 returns the union data inside the Querybuildertypesv5Step as a Querybuildertypesv5Step0
func (t Querybuildertypesv5Step) AsQuerybuildertypesv5Step0() (Querybuildertypesv5Step0, error) {
	var body Querybuildertypesv5Step0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromQuerybuildertypesv5Step0 overwrites any union data inside the Querybuildertypesv5Step as the provided Querybuildertypesv5Step0
func (t *Querybuildertypesv5Step) FromQuerybuildertypesv5Step0(v Querybuildertypesv5Step0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeQuerybuildertypesv5Step0 performs a merge with any union data inside the Querybuildertypesv5Step, using the provided Querybuildertypesv5Step0
func (t *Querybuildertypesv5Step) MergeQuerybuildertypesv5Step0(v Querybuildertypesv5Step0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsQuerybuildertypesv5Step1 returns the union data inside the Querybuildertypesv5Step as a Querybuildertypesv5Step1
func (t Querybuildertypesv5Step) AsQuerybuildertypesv5Step1() (Querybuildertypesv5Step1, error) {
	var body Querybuildertypesv5Step1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromQuerybuildertypesv5Step1 overwrites any union data inside the Querybuildertypesv5Step as the provided Querybuildertypesv5Step1
func (t *Querybuildertypesv5Step) FromQuerybuildertypesv5Step1(v Querybuildertypesv5Step1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeQuerybuildertypesv5Step1 performs a merge with any union data inside the Querybuildertypesv5Step, using the provided Querybuildertypesv5Step1
func (t *Querybuildertypesv5Step) MergeQuerybuildertypesv5Step1(v Querybuildertypesv5Step1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Querybuildertypesv5Step) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Querybuildertypesv5Step) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsRuletypesEvaluationRolling returns the union data inside the RuletypesEvaluationEnvelope as a RuletypesEvaluationRolling
func (t RuletypesEvaluationEnvelope) AsRuletypesEvaluationRolling() (RuletypesEvaluationRolling, error) {
	var body RuletypesEvaluationRolling
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRuletypesEvaluationRolling overwrites any union data inside the RuletypesEvaluationEnvelope as the provided RuletypesEvaluationRolling
func (t *RuletypesEvaluationEnvelope) FromRuletypesEvaluationRolling(v RuletypesEvaluationRolling) error {
	v.Kind = "rolling"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRuletypesEvaluationRolling performs a merge with any union data inside the RuletypesEvaluationEnvelope, using the provided RuletypesEvaluationRolling
func (t *RuletypesEvaluationEnvelope) MergeRuletypesEvaluationRolling(v RuletypesEvaluationRolling) error {
	v.Kind = "rolling"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsRuletypesEvaluationCumulative returns the union data inside the RuletypesEvaluationEnvelope as a RuletypesEvaluationCumulative
func (t RuletypesEvaluationEnvelope) AsRuletypesEvaluationCumulative() (RuletypesEvaluationCumulative, error) {
	var body RuletypesEvaluationCumulative
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRuletypesEvaluationCumulative overwrites any union data inside the RuletypesEvaluationEnvelope as the provided RuletypesEvaluationCumulative
func (t *RuletypesEvaluationEnvelope) FromRuletypesEvaluationCumulative(v RuletypesEvaluationCumulative) error {
	v.Kind = "cumulative"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRuletypesEvaluationCumulative performs a merge with any union data inside the RuletypesEvaluationEnvelope, using the provided RuletypesEvaluationCumulative
func (t *RuletypesEvaluationEnvelope) MergeRuletypesEvaluationCumulative(v RuletypesEvaluationCumulative) error {
	v.Kind = "cumulative"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t RuletypesEvaluationEnvelope) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"kind"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t RuletypesEvaluationEnvelope) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "cumulative":
		return t.AsRuletypesEvaluationCumulative()
	case "rolling":
		return t.AsRuletypesEvaluationRolling()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t RuletypesEvaluationEnvelope) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *RuletypesEvaluationEnvelope) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsRuletypesThresholdBasic returns the union data inside the RuletypesRuleThresholdData as a RuletypesThresholdBasic
func (t RuletypesRuleThresholdData) AsRuletypesThresholdBasic() (RuletypesThresholdBasic, error) {
	var body RuletypesThresholdBasic
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRuletypesThresholdBasic overwrites any union data inside the RuletypesRuleThresholdData as the provided RuletypesThresholdBasic
func (t *RuletypesRuleThresholdData) FromRuletypesThresholdBasic(v RuletypesThresholdBasic) error {
	v.Kind = "basic"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRuletypesThresholdBasic performs a merge with any union data inside the RuletypesRuleThresholdData, using the provided RuletypesThresholdBasic
func (t *RuletypesRuleThresholdData) MergeRuletypesThresholdBasic(v RuletypesThresholdBasic) error {
	v.Kind = "basic"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t RuletypesRuleThresholdData) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"kind"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t RuletypesRuleThresholdData) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "basic":
		return t.AsRuletypesThresholdBasic()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t RuletypesRuleThresholdData) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *RuletypesRuleThresholdData) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListRules request
	ListRules(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateRuleWithBody request with any body
	CreateRuleWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateRule(ctx context.Context, body CreateRuleJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteRuleByID request
	DeleteRuleByID(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetRuleByID request
	GetRuleByID(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateRuleByIDWithBody request with any body
	UpdateRuleByIDWithBody(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateRuleByID(ctx context.Context, id string, body UpdateRuleByIDJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListRules(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListRulesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateRuleWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateRuleRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateRule(ctx context.Context, body CreateRuleJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateRuleRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteRuleByID(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteRuleByIDRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetRuleByID(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetRuleByIDRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateRuleByIDWithBody(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateRuleByIDRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateRuleByID(ctx context.Context, id string, body UpdateRuleByIDJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateRuleByIDRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListRulesRequest generates requests for ListRules
func NewListRulesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v2/rules")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateRuleRequest calls the generic CreateRule builder with application/json body
func NewCreateRuleRequest(server string, body CreateRuleJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateRuleRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateRuleRequestWithBody generates requests for CreateRule with any type of body
func NewCreateRuleRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v2/rules")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteRuleByIDRequest generates requests for DeleteRuleByID
func NewDeleteRuleByIDRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v2/rules/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetRuleByIDRequest generates requests for GetRuleByID
func NewGetRuleByIDRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v2/rules/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdateRuleByIDRequest calls the generic UpdateRuleByID builder with application/json body
func NewUpdateRuleByIDRequest(server string, id string, body UpdateRuleByIDJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateRuleByIDRequestWithBody(server, id, "application/json", bodyReader)
}

// NewUpdateRuleByIDRequestWithBody generates requests for UpdateRuleByID with any type of body
func NewUpdateRuleByIDRequestWithBody(server string, id string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v2/rules/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListRulesWithResponse request
	ListRulesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListRulesResponse, error)

	// CreateRuleWithBodyWithResponse request with any body
	CreateRuleWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateRuleResponse, error)

	CreateRuleWithResponse(ctx context.Context, body CreateRuleJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateRuleResponse, error)

	// DeleteRuleByIDWithResponse request
	DeleteRuleByIDWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*DeleteRuleByIDResponse, error)

	// GetRuleByIDWithResponse request
	GetRuleByIDWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetRuleByIDResponse, error)

	// UpdateRuleByIDWithBodyWithResponse request with any body
	UpdateRuleByIDWithBodyWithResponse(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateRuleByIDResponse, error)

	UpdateRuleByIDWithResponse(ctx context.Context, id string, body UpdateRuleByIDJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateRuleByIDResponse, error)
}

type ListRulesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Data   []RuletypesRule `json:"data"`
		Status string          `json:"status"`
	}
	JSON401 *RenderErrorResponse
	JSON403 *RenderErrorResponse
	JSON500 *RenderErrorResponse
}

// Status returns HTTPResponse.Status
func (r ListRulesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListRulesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateRuleResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *struct {
		Data   RuletypesRule `json:"data"`
		Status string        `json:"status"`
	}
	JSON400 *RenderErrorResponse
	JSON401 *RenderErrorResponse
	JSON403 *RenderErrorResponse
	JSON500 *RenderErrorResponse
}

// Status returns HTTPResponse.Status
func (r CreateRuleResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateRuleResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteRuleByIDResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON401      *RenderErrorResponse
	JSON403      *RenderErrorResponse
	JSON404      *RenderErrorResponse
	JSON500      *RenderErrorResponse
}

// Status returns HTTPResponse.Status
func (r DeleteRuleByIDResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteRuleByIDResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetRuleByIDResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Data   RuletypesRule `json:"data"`
		Status string        `json:"status"`
	}
	JSON401 *RenderErrorResponse
	JSON403 *RenderErrorResponse
	JSON404 *RenderErrorResponse
	JSON500 *RenderErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetRuleByIDResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetRuleByIDResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UpdateRuleByIDResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *RenderErrorResponse
	JSON401      *RenderErrorResponse
	JSON403      *RenderErrorResponse
	JSON404      *RenderErrorResponse
	JSON500      *RenderErrorResponse
}

// Status returns HTTPResponse.Status
func (r UpdateRuleByIDResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateRuleByIDResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ListRulesWithResponse request returning *ListRulesResponse
func (c *ClientWithResponses) ListRulesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListRulesResponse, error) {
	rsp, err := c.ListRules(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListRulesResponse(rsp)
}

// CreateRuleWithBodyWithResponse request with arbitrary body returning *CreateRuleResponse
func (c *ClientWithResponses) CreateRuleWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateRuleResponse, error) {
	rsp, err := c.CreateRuleWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateRuleResponse(rsp)
}

func (c *ClientWithResponses) CreateRuleWithResponse(ctx context.Context, body CreateRuleJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateRuleResponse, error) {
	rsp, err := c.CreateRule(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateRuleResponse(rsp)
}

// DeleteRuleByIDWithResponse request returning *DeleteRuleByIDResponse
func (c *ClientWithResponses) DeleteRuleByIDWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*DeleteRuleByIDResponse, error) {
	rsp, err := c.DeleteRuleByID(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteRuleByIDResponse(rsp)
}

// GetRuleByIDWithResponse request returning *GetRuleByIDResponse
func (c *ClientWithResponses) GetRuleByIDWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetRuleByIDResponse, error) {
	rsp, err := c.GetRuleByID(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetRuleByIDResponse(rsp)
}

// UpdateRuleByIDWithBodyWithResponse request with arbitrary body returning *UpdateRuleByIDResponse
func (c *ClientWithResponses) UpdateRuleByIDWithBodyWithResponse(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateRuleByIDResponse, error) {
	rsp, err := c.UpdateRuleByIDWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateRuleByIDResponse(rsp)
}

func (c *ClientWithResponses) UpdateRuleByIDWithResponse(ctx context.Context, id string, body UpdateRuleByIDJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateRuleByIDResponse, error) {
	rsp, err := c.UpdateRuleByID(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateRuleByIDResponse(rsp)
}

// ParseListRulesResponse parses an HTTP response from a ListRulesWithResponse call
func ParseListRulesResponse(rsp *http.Response) (*ListRulesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListRulesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Data   []RuletypesRule `json:"data"`
			Status string          `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest RenderErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest RenderErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest RenderErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseCreateRuleResponse parses an HTTP response from a CreateRuleWithResponse call
func ParseCreateRuleResponse(rsp *http.Response) (*CreateRuleResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateRuleResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest struct {
			Data   RuletypesRule `json:"data"`
			Status string        `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest RenderErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest RenderErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest RenderErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest RenderErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseDeleteRuleByIDResponse parses an HTTP response from a DeleteRuleByIDWithResponse call
func ParseDeleteRuleByIDResponse(rsp *http.Response) (*DeleteRuleByIDResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteRuleByIDResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest RenderErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest RenderErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest RenderErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest RenderErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetRuleByIDResponse parses an HTTP response from a GetRuleByIDWithResponse call
func ParseGetRuleByIDResponse(rsp *http.Response) (*GetRuleByIDResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetRuleByIDResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Data   RuletypesRule `json:"data"`
			Status string        `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest RenderErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest RenderErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest RenderErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest RenderErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseUpdateRuleByIDResponse parses an HTTP response from a UpdateRuleByIDWithResponse call
func ParseUpdateRuleByIDResponse(rsp *http.Response) (*UpdateRuleByIDResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateRuleByIDResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest RenderErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest RenderErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest RenderErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest RenderErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest RenderErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
